{
  "hash": "40c74dfcadceb6af5446fc175bdf9b61",
  "result": {
    "engine": "jupyter",
    "markdown": "# Định giá doanh nghiệp, kiệt quệ tài chính và mức độ trưởng thành của công ty\n\nHiểu rõ về định giá doanh nghiệp, sức khỏe tài chính và mức độ trưởng thành của doanh nghiệp là nền tảng của phân tích tài chính và việc ra quyết định đầu tư. Ba thước đo được sử dụng rộng rãi (chẳng hạn Q của Tobin, điểm Z của Altman và tuổi công ty) phản ánh những khía cạnh khác nhau nhưng bổ sung cho nhau về vị thế kinh tế của doanh nghiệp. Q của Tobin phản ánh đánh giá của thị trường về giá trị doanh nghiệp so với cơ sở tài sản của nó, điểm Z của Altman dự báo khả năng xảy ra kiệt quệ tài chính, còn tuổi công ty là đại diện cho mức độ trưởng thành về tổ chức và sự ổn định hoạt động.\n\nMặc dù các thước đo này đã được nghiên cứu rộng rãi ở các thị trường phát triển, đặc biệt là Hoa Kỳ [xem @lindenberg1981tobin; @altman1968financial; @gompers2003corporate], việc áp dụng chúng ở các thị trường mới nổi như Việt Nam đặt ra những thách thức và cơ hội riêng. Thị trường chứng khoán Việt Nam tăng trưởng nhanh nhưng vẫn mang những đặc điểm cấu trúc, như mức độ tập trung sở hữu, sự chi phối của doanh nghiệp nhà nước, thị trường trái phiếu còn thiếu chiều sâu và chuẩn mực kế toán đang tiếp tục phát triển, đòi hỏi phải điều chỉnh cẩn trọng các thước đo định giá và kiệt quệ tài chính tiêu chuẩn.\n\n## Các gói cần thiết\n\n::: {#setup .cell message='false' execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport matplotlib.ticker as mticker\nimport seaborn as sns\nfrom matplotlib.colors import LinearSegmentedColormap\nimport warnings\n\nwarnings.filterwarnings(\"ignore\")\nplt.rcParams.update({\n    \"figure.figsize\": (10, 6),\n    \"font.size\": 12,\n    \"axes.titlesize\": 14,\n    \"axes.labelsize\": 12,\n    \"xtick.labelsize\": 10,\n    \"ytick.labelsize\": 10,\n    \"legend.fontsize\": 10,\n    \"figure.dpi\": 150,\n    \"axes.spines.top\": False,\n    \"axes.spines.right\": False,\n})\n\n# Color palette consistent with Tidy Finance style\ncolors = {\n    \"primary\": \"#1f77b4\",\n    \"secondary\": \"#ff7f0e\",\n    \"tertiary\": \"#2ca02c\",\n    \"quaternary\": \"#d62728\",\n    \"quinary\": \"#9467bd\",\n    \"safe\": \"#2ca02c\",\n    \"alert\": \"#ff7f0e\",\n    \"danger\": \"#d62728\",\n    \"distress\": \"#8b0000\",\n}\n```\n:::\n\n\n# Nền tảng lý thuyết {#sec-valuation-theory}\n\n## Q của Tobin: Giá trị thị trường của doanh nghiệp {#sec-valuation-tobinq-theory}\n\n### Khái niệm gốc\n\nQ của Tobin được @tobin1969general giới thiệu như một mối liên kết lý thuyết giữa thị trường tài chính và các quyết định đầu tư thực. Ý tưởng cốt lõi rất đơn giản mà tinh tế: nếu thị trường định giá tài sản của doanh nghiệp cao hơn chi phí thay thế của chúng, doanh nghiệp có động cơ đầu tư thêm vốn mới; nếu thị trường định giá thấp hơn, doanh nghiệp không nên đầu tư, thậm chí có thể có lợi khi bán bớt tài sản.\n\nMột cách hình thức, Q của Tobin được định nghĩa như sau:\n\n$$\nQ = \\frac{\\text{Market Value of the Firm}}{\\text{Replacement Cost of Assets}}\n$$ {#eq-tobinq-basic}\n\nKhi $Q > 1$, thị trường nhận thấy doanh nghiệp sở hữu các tài sản vô hình có giá trị, như giá trị thương hiệu, năng lực quản lý, công nghệ độc quyền hoặc cơ hội tăng trưởng, vượt quá chi phí của cơ sở tài sản hữu hình. Khi $Q < 1$, thị trường thực chất định giá doanh nghiệp thấp hơn chi phí để xây dựng lại tài sản của nó, gợi ý khả năng bị định giá thấp hoặc sự hiện diện của chi phí đại diện và sự kém hiệu quả về tổ chức.\n\n### Phân rã giá trị thị trường\n\nTử số của Q của Tobin biểu diễn tổng giá trị thị trường của mọi quyền đòi đối với doanh nghiệp:\n\n$$\nMV = CS + PS + ST + LT\n$$ {#eq-mv-decomposition}\n\ntrong đó:\n\n-   $CS$ = Giá trị thị trường của cổ phiếu phổ thông (số cổ phiếu đang lưu hành $\\times$ giá thị trường)\n-   $PS$ = Giá trị thị trường của cổ phiếu ưu đãi\n-   $ST$ = Giá trị thị trường của nợ ngắn hạn\n-   $LT$ = Giá trị thị trường của nợ dài hạn\n\n### Chi phí thay thế của tài sản\n\nMẫu số phản ánh chi phí thay thế của cơ sở tài sản của doanh nghiệp:\n\n$$\nRC = TA + (RNP - HNP) + (RINV - HINV)\n$$ {#eq-replacement-cost}\n\ntrong đó:\n\n-   $TA$ = Tổng tài sản theo báo cáo\n-   $RNP$ = Chi phí thay thế của nhà xưởng và thiết bị ròng\n-   $HNP$ = Giá trị lịch sử (sổ sách) của nhà xưởng và thiết bị ròng\n-   $RINV$ = Chi phí thay thế của hàng tồn kho\n-   $HINV$ = Giá trị lịch sử (sổ sách) của hàng tồn kho\n\nViệc điều chỉnh chi phí thay thế đối với nhà xưởng và thiết bị đòi hỏi các phép tính đệ quy có tính đến tỷ lệ khấu hao và, trong các ước lượng chi tiết hơn, tỷ lệ tiến bộ kỹ thuật [@lindenberg1981tobin]. Đối với hàng tồn kho, việc điều chỉnh phụ thuộc vào phương pháp kế toán hàng tồn kho: LIFO (nhập sau, xuất trước), FIFO (nhập trước, xuất trước), giá bình quân hoặc giá bán lẻ.\n\n### Q của Tobin giản lược\n\nTrong thực tế, việc tính đầy đủ chi phí thay thế đòi hỏi dữ liệu thường không có sẵn, đặc biệt ở các thị trường mới nổi. @gompers2003corporate phổ biến một phiên bản giản lược:\n\n$$\nQ_{\\text{simple}} = \\frac{TA + ME - BE}{TA}\n$$ {#eq-tobinq-simple}\n\ntrong đó $ME$ là giá trị thị trường của vốn chủ sở hữu và $BE$ là giá trị sổ sách của vốn chủ sở hữu. Cách xây dựng này giả định rằng giá trị sổ sách của nợ và cổ phiếu ưu đãi xấp xỉ giá trị thị trường của chúng, và tổng tài sản xấp xỉ chi phí thay thế của cơ sở tài sản của doanh nghiệp. Dù đơn giản, thước đo này được chứng minh là tương quan tốt với các cách xây dựng phức tạp hơn và đã trở thành chuẩn mực trong nghiên cứu tài chính doanh nghiệp thực nghiệm.\n\n### Xấp xỉ của Chung và Pruitt\n\n@chung1994simple đề xuất một phép xấp xỉ khác được sử dụng rộng rãi:\n\n$$\nQ_{\\text{CP}} = \\frac{ME + PS + DEBT}{TA}\n$$ {#eq-tobinq-cp}\n\ntrong đó $DEBT = \\text{Current Liabilities} - \\text{Current Assets} + \\text{Book Value of Inventories} + \\text{Long-term Debt}$. Cách xây dựng này nắm bắt vị thế nợ ròng chính xác hơn so với phiên bản của @gompers2003corporate.\n\n------------------------------------------------------------------------\n\n## Điểm Z của Altman: Dự báo kiệt quệ tài chính {#sec-valuation-zscore-theory}\n\n### Mô hình gốc\n\nĐiểm Z của Altman, do @altman1968financial phát triển, là một mô hình phân tích phân biệt đa biến dự báo xác suất phá sản của doanh nghiệp trong khoảng thời gian hai năm. Mô hình ban đầu được ước lượng bằng một mẫu ghép cặp gồm các doanh nghiệp sản xuất của Hoa Kỳ đã phá sản và chưa phá sản, và có dạng:\n\n$$\nZ = 3.3 \\cdot X_1 + 0.999 \\cdot X_2 + 0.6 \\cdot X_3 + 1.2 \\cdot X_4 + 1.4 \\cdot X_5\n$$ {#eq-zscore-original}\n\ntrong đó năm tỷ số tài chính được nêu trong @tbl-zscore-components\n\n| Biến | Công thức | Diễn giải |\n|---------------------|-------------------|--------------------------------|\n| $X_1$ | $\\frac{\\text{EBIT}}{\\text{Total Assets}}$ | Khả năng sinh lời của tài sản |\n| $X_2$ | $\\frac{\\text{Net Sales}}{\\text{Total Assets}}$ | Vòng quay tổng tài sản |\n| $X_3$ | $\\frac{\\text{Market Value of Equity}}{\\text{Total Liabilities}}$ | Tỷ số đòn bẩy (nghịch đảo) |\n| $X_4$ | $\\frac{\\text{Working Capital}}{\\text{Total Assets}}$ | Thanh khoản ngắn hạn |\n| $X_5$ | $\\frac{\\text{Retained Earnings}}{\\text{Total Assets}}$ | Khả năng sinh lời tích lũy |\n\n: Các thành phần của điểm Z của Altman {#tbl-zscore-components}\n\nCác vùng diễn giải được nêu trong @tbl-zscore-zones\n\n| Khoảng điểm Z | Diễn giải |\n|-----------------------------------|-------------------------------------|\n| $Z > 2.99$ | Vùng an toàn-xác suất kiệt quệ tài chính thấp |\n| $2.70 \\leq Z \\leq 2.99$ | Vùng xám-cần cảnh giác, rủi ro trung bình |\n| $1.80 \\leq Z < 2.70$ | Vùng kiệt quệ-rủi ro phá sản đáng kể trong vòng 2 năm |\n| $Z < 1.80$ | Kiệt quệ nghiêm trọng-xác suất thất bại tài chính rất cao |\n\n: Các vùng diễn giải điểm Z của Altman {#tbl-zscore-zones}\n\n### Mô hình điểm Z' cho doanh nghiệp chưa niêm yết\n\nVì mô hình gốc dùng giá trị thị trường của vốn chủ sở hữu trong $X_3$, @altman2010corporate phát triển điểm Z' cho các doanh nghiệp chưa niêm yết (không giao dịch công khai) bằng cách thay vốn hóa thị trường bằng giá trị sổ sách của vốn chủ sở hữu:\n\n$$\nZ' = 0.717 \\cdot X_1' + 0.847 \\cdot X_2' + 3.107 \\cdot X_3' + 0.420 \\cdot X_4' + 0.998 \\cdot X_5'\n$$ {#eq-zscore-private}\n\ntrong đó $X_4' = \\frac{\\text{Book Value of Equity}}{\\text{Total Liabilities}}$, và các biến còn lại được định nghĩa như trong mô hình gốc nhưng với các hệ số được ước lượng lại.\n\n### Mô hình điểm Z'' cho thị trường mới nổi\n\nPhù hợp nhất với Việt Nam, @altman2010corporate cũng phát triển điểm Z'' cho các doanh nghiệp phi sản xuất và doanh nghiệp ở thị trường mới nổi:\n\n$$\nZ'' = 3.25 + 6.56 \\cdot X_1'' + 3.26 \\cdot X_2'' + 6.72 \\cdot X_3'' + 1.05 \\cdot X_4''\n$$ {#eq-zscore-emerging}\n\ntrong đó:\n\n-   $X_1'' = \\frac{\\text{Working Capital}}{\\text{Total Assets}}$\n-   $X_2'' = \\frac{\\text{Retained Earnings}}{\\text{Total Assets}}$\n-   $X_3'' = \\frac{\\text{EBIT}}{\\text{Total Assets}}$\n-   $X_4'' = \\frac{\\text{Book Value of Equity}}{\\text{Total Liabilities}}$\n\nLưu ý rằng mô hình này loại bỏ tỷ số doanh thu/tổng tài sản ($X_2$ trong mô hình gốc) để giảm thiểu hiệu ứng ngành và bổ sung một hệ số chặn. Các vùng phân loại được dịch chuyển tương ứng (@tbl-zscore-em-zones).\n\n| Khoảng điểm Z''           | Diễn giải |\n|---------------------------|----------------|\n| $Z'' > 2.60$              | Vùng an toàn   |\n| $1.10 \\leq Z'' \\leq 2.60$ | Vùng xám       |\n| $Z'' < 1.10$              | Vùng kiệt quệ  |\n\n: Các vùng diễn giải điểm Z'' cho thị trường mới nổi {#tbl-zscore-em-zones}\n\n## Tuổi công ty: Đo lường mức độ trưởng thành của doanh nghiệp {#sec-valuation-age-theory}\n\nTuổi công ty phản ánh kinh nghiệm tích lũy, uy tín và vốn tổ chức của doanh nghiệp. Các doanh nghiệp lâu đời thường có hoạt động ổn định hơn, lợi thế cạnh tranh vững chắc và dòng tiền dễ dự báo [@coad2018firm]. Tuổi thường được dùng làm biến kiểm soát trong nghiên cứu tài chính doanh nghiệp, và mối quan hệ của nó với hiệu quả hoạt động là mơ hồ về mặt lý thuyết: doanh nghiệp lâu đời được hưởng lợi từ hiệu ứng học hỏi và uy tín nhưng có thể chịu sự cứng nhắc về tổ chức và suy giảm đổi mới [@huergo2004firms].\n\nThước đo lý tưởng là số năm kể từ khi thành lập. Khi không có ngày thành lập, các đại diện thông dụng gồm:\n\n1.  **Tuổi niêm yết**: Số năm kể từ lần IPO hoặc niêm yết đầu tiên trên một sở giao dịch chứng khoán.\n2.  **Tuổi dữ liệu**: Số năm kể từ lần xuất hiện đầu tiên trong các cơ sở dữ liệu tài chính.\n3.  **Tuổi đăng ký thành lập**: Số năm kể từ ngày đăng ký thành lập pháp lý.\n\nTrong bối cảnh Việt Nam, chúng ta có thể sử dụng nhiều đại diện, bao gồm ngày niêm yết lần đầu trên HOSE hoặc HNX, ngày báo cáo tài chính đầu tiên có sẵn, và (khi có) ngày thành lập từ hồ sơ công ty.\n\n# Bối cảnh thị trường Việt Nam {#sec-valuation-vietnam-context}\n\n## Các đặc điểm thể chế ảnh hưởng đến thước đo định giá\n\nThị trường chứng khoán Việt Nam có một số đặc điểm thể chế quan trọng cần xem xét khi tính toán và diễn giải Q của Tobin, điểm Z của Altman và tuổi công ty.\n\n### Sở hữu nhà nước và cổ phần hóa\n\nA significant proportion of Vietnamese listed firms are former state-owned enterprises (SOEs) that underwent equitization (cổ phần hóa). These firms often retain substantial state ownership, which can affect:\n\n-   **Q của Tobin**: Sở hữu nhà nước có thể làm giảm Q nếu thị trường cho rằng sự can thiệp của chính phủ làm giảm hiệu quả, hoặc có thể làm tăng Q nếu các mối liên hệ với nhà nước mang lại khả năng tiếp cận ưu đãi đối với nguồn lực và hợp đồng.\n-   **Điểm Z**: Các doanh nghiệp nhà nước (SOE) có thể có bảo lãnh ngầm của chính phủ làm giảm rủi ro phá sản thực tế xuống thấp hơn mức điểm Z dự báo.\n-   **Tuổi**: Tuổi hoạt động thực của các SOE đã cổ phần hóa có thể vượt xa tuổi niêm yết của chúng, gây ra khó khăn trong đo lường.\n\n### Giới hạn sở hữu nước ngoài\n\nViệt Nam áp đặt giới hạn sở hữu nước ngoài (FOL) đối với các công ty niêm yết, thường được giới hạn ở mức 49% đối với hầu hết các ngành (có một số ngoại lệ). Ràng buộc này có thể tạo ra phần bù giá đối với các cổ phiếu tiến gần trần FOL, có khả năng làm tăng Q của Tobin của các doanh nghiệp này [@vo2015foreign].\n\n### Chuẩn mực kế toán\n\nChuẩn mực Kế toán Việt Nam (VAS) khác với Chuẩn mực Báo cáo Tài chính Quốc tế (IFRS) ở một số điểm liên quan đến các thước đo của chúng ta:\n\n-   **Cơ sở giá gốc**: VAS dựa nhiều hơn vào giá gốc, có thể khiến giá trị sổ sách lệch đáng kể so với chi phí thay thế, ảnh hưởng đến cả phép tính Q lẫn điểm Z.\n-   **Hạn chế đo lường theo giá trị hợp lý**: Không như IFRS, VAS hạn chế việc đo lường theo giá trị hợp lý đối với nhiều loại tài sản, khiến các đại diện dựa trên giá trị sổ sách kém tin cậy hơn.\n-   **Phương pháp hàng tồn kho**: Các doanh nghiệp Việt Nam dùng nhiều phương pháp định giá hàng tồn kho (FIFO, bình quân gia quyền), ảnh hưởng đến giá trị sổ sách của hàng tồn kho và do đó đến thành phần vốn lưu động của điểm Z.\n\n### Vi cấu trúc thị trường\n\nThị trường Việt Nam có biên độ giá hằng ngày (hiện là $\\pm$ 7% trên HOSE, $\\pm$ 10% trên HNX, $\\pm$ 15% trên UPCoM), có thể ngăn giá đạt tới giá trị cân bằng một cách nhanh chóng. Điều này có nghĩa là vốn hóa thị trường tại một thời điểm có thể không phản ánh đầy đủ thông tin sẵn có, đưa nhiễu vào các thước đo dựa trên giá trị thị trường như Q của Tobin.\n\n```{=html}\n<!-- ## DataCore.vn Dataset Structure\n\nDataCore.vn provides comprehensive financial data for Vietnamese listed companies. For this chapter, we assume access to the following datasets:\n\n1.  **Financial statements** (`financial_statements`): Annual and quarterly balance sheets, income statements, and cash flow statements for all listed firms.\n2.  **Market data** (`market_data`): Daily stock prices, shares outstanding, and market capitalization.\n3.  **Company profiles** (`company_profiles`): Firm characteristics including listing date, founding date, industry classification, exchange, and ownership structure.\n4.  **Delisting information** (`delisting_info`): Records of firms that have been delisted, including dates and reasons. -->\n```\n\n# Chuẩn bị dữ liệu {#sec-valuation-data-prep}\n\n## Tải và làm sạch dữ liệu báo cáo tài chính\n\nChúng ta bắt đầu bằng việc tải dữ liệu báo cáo tài chính hằng năm và xây dựng các biến cần thiết cho ba thước đo.\n\n::: {#simulate-data .cell execution_count=2}\n``` {.python .cell-code code-summary=\"Simulate Vietnamese financial data (replace with DataCore.vn API calls)\"}\n# ============================================================================\n# In practice, replace this section with actual DataCore.vn API calls:\n#\n#   from datacore import DataCoreClient\n#   client = DataCoreClient(api_key=\"your_api_key\")\n#   financials = client.get_financial_statements(\n#       frequency=\"annual\",\n#       start_date=\"2005-01-01\",\n#       end_date=\"2024-12-31\"\n#   )\n#   market = client.get_market_data(frequency=\"daily\")\n#   profiles = client.get_company_profiles()\n#\n# For demonstration purposes, we simulate realistic Vietnamese market data.\n# ============================================================================\n\nnp.random.seed(42)\n\nn_firms = 300\nyears = range(2008, 2025)\nexchanges = [\"HOSE\", \"HNX\", \"UPCoM\"]\nindustries = [\n    \"Bất động sản\", \"Ngân hàng\", \"Thực phẩm & Đồ uống\",\n    \"Xây dựng & Vật liệu\", \"Công nghệ thông tin\", \"Bán lẻ\",\n    \"Dầu khí\", \"Thép\", \"Dệt may\", \"Dược phẩm\",\n    \"Điện lực\", \"Vận tải & Logistics\", \"Hóa chất\",\n    \"Chứng khoán\", \"Bảo hiểm\"\n]\n\n# Generate firm profiles\nfirm_ids = [f\"VN{str(i).zfill(4)}\" for i in range(1, n_firms + 1)]\nfirm_profiles = pd.DataFrame({\n    \"ticker\": firm_ids,\n    \"exchange\": np.random.choice(exchanges, n_firms, p=[0.5, 0.3, 0.2]),\n    \"industry\": np.random.choice(industries, n_firms),\n    \"founding_year\": np.random.randint(1975, 2015, n_firms),\n    \"listing_year\": np.random.randint(2000, 2020, n_firms),\n    \"state_ownership_pct\": np.clip(\n        np.random.beta(2, 5, n_firms) * 100, 0, 75\n    ).round(1),\n})\nfirm_profiles[\"listing_year\"] = np.maximum(\n    firm_profiles[\"listing_year\"],\n    firm_profiles[\"founding_year\"] + 1\n)\n\n# Generate panel data\nrecords = []\nfor _, firm in firm_profiles.iterrows():\n    start_year = max(firm[\"listing_year\"], 2008)\n    # Base financial characteristics (firm fixed effects)\n    base_ta = np.exp(np.random.normal(14, 1.5))  # Total assets in VND millions\n    base_profitability = np.random.normal(0.08, 0.05)\n    base_leverage = np.random.beta(3, 3)\n    base_turnover = np.random.gamma(2, 0.4)\n\n    for year in years:\n        if year < start_year:\n            continue\n        if np.random.random() < 0.02:  # 2% chance of delisting\n            break\n\n        # Time-varying components with persistence\n        shock = np.random.normal(0, 0.15)\n        growth = np.random.normal(0.08, 0.05)\n\n        ta = base_ta * (1 + growth) ** (year - start_year) * np.exp(shock)\n        profitability = np.clip(base_profitability + np.random.normal(0, 0.03), -0.3, 0.5)\n        leverage = np.clip(base_leverage + np.random.normal(0, 0.05), 0.05, 0.95)\n\n        lt = ta * leverage * np.random.uniform(0.4, 0.7)\n        total_liabilities = ta * leverage\n        ct_liabilities = total_liabilities - lt\n\n        seq = ta * (1 - leverage)\n        sale = ta * np.clip(base_turnover + np.random.normal(0, 0.1), 0.1, 5)\n        ebit = ta * profitability\n        ni = ebit * np.random.uniform(0.6, 0.9)\n        re = seq * np.random.uniform(-0.2, 0.8)\n        act = ta * np.random.uniform(0.2, 0.7)\n        lct = ct_liabilities\n\n        # Market value with noise and sentiment\n        market_premium = np.random.lognormal(0, 0.4)\n        me = seq * market_premium\n        prcc = me / max(np.random.uniform(50, 500), 1)\n        csho = me / max(prcc, 0.01)\n\n        # Preferred stock (rare in Vietnam, mostly zero)\n        pstk = 0 if np.random.random() > 0.05 else seq * np.random.uniform(0, 0.1)\n\n        # Net plant and equipment\n        ppent = ta * np.random.uniform(0.1, 0.6)\n        invt = ta * np.random.uniform(0.05, 0.3)\n\n        # Deferred taxes and investment tax credit (typically small in VN)\n        txdb = ta * np.random.uniform(0, 0.02)\n        itcb = 0\n\n        records.append({\n            \"ticker\": firm[\"ticker\"],\n            \"year\": year,\n            \"datadate\": pd.Timestamp(year, 12, 31),\n            \"at\": ta,            # Total Assets\n            \"seq\": seq,          # Stockholders' Equity\n            \"lt\": lt,            # Long-term Debt\n            \"lct\": lct,          # Current Liabilities\n            \"tlb\": total_liabilities,  # Total Liabilities\n            \"sale\": sale,        # Net Sales/Revenue\n            \"ebit\": ebit,        # EBIT\n            \"ni\": ni,            # Net Income\n            \"re_var\": re,        # Retained Earnings\n            \"act\": act,          # Current Assets\n            \"ppent\": ppent,      # Net Plant & Equipment\n            \"invt\": invt,        # Inventories\n            \"txdb\": txdb,        # Deferred Taxes\n            \"itcb\": itcb,        # Investment Tax Credit\n            \"pstk\": pstk,        # Preferred Stock\n            \"me\": me,            # Market Value of Equity\n            \"prcc\": prcc,        # Price at Calendar Year End\n            \"csho\": csho,        # Shares Outstanding\n        })\n\ndf = pd.DataFrame(records)\ndf = df.merge(firm_profiles[[\"ticker\", \"exchange\", \"industry\",\n                              \"founding_year\", \"listing_year\",\n                              \"state_ownership_pct\"]],\n              on=\"ticker\", how=\"left\")\n\nprint(f\"Panel dimensions: {df.shape[0]:,} firm-year observations\")\nprint(f\"Number of unique firms: {df['ticker'].nunique()}\")\nprint(f\"Year range: {df['year'].min()}–{df['year'].max()}\")\nprint(f\"Exchanges: {df['exchange'].value_counts().to_dict()}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPanel dimensions: 3,484 firm-year observations\nNumber of unique firms: 297\nYear range: 2008–2024\nExchanges: {'HOSE': 1701, 'HNX': 1118, 'UPCoM': 665}\n```\n:::\n:::\n\n\n## Định nghĩa biến và ánh xạ\n\n@tbl-variable-mapping trình bày ánh xạ giữa tên biến chuẩn và các trường tương ứng.\n\n::: {#tbl-variable-mapping .cell tbl-cap='Ánh xạ biến' execution_count=3}\n``` {.python .cell-code}\nvariable_map = pd.DataFrame({\n    \"Compustat Variable\": [\n        \"AT\", \"SEQ\", \"LT\", \"LCT\", \"SALE\", \"EBIT\", \"NI\",\n        \"RE\", \"ACT\", \"PPENT\", \"INVT\", \"TXDB\", \"ITCB\",\n        \"PSTK/PSTKRV/PSTKL\", \"PRCC_C\", \"CSHO\", \"DLDTE\", \"DLRSN\"\n    ],\n    \"Description\": [\n        \"Total Assets\", \"Stockholders' Equity\", \"Long-term Debt\",\n        \"Current Liabilities\", \"Net Sales/Revenue\",\n        \"Earnings Before Interest & Taxes\", \"Net Income\",\n        \"Retained Earnings\", \"Current Assets\",\n        \"Net Plant & Equipment\", \"Total Inventories\",\n        \"Deferred Taxes\", \"Investment Tax Credit\",\n        \"Preferred Stock (various)\", \"Price Close (Calendar Year)\",\n        \"Common Shares Outstanding\", \"Delisting Date\",\n        \"Delisting Reason\"\n    ],\n    \"DataCore.vn Equivalent\": [\n        \"tong_tai_san\", \"von_chu_so_huu\", \"no_dai_han\",\n        \"no_ngan_han\", \"doanh_thu_thuan\",\n        \"loi_nhuan_truoc_thue_va_lai_vay\", \"loi_nhuan_sau_thue\",\n        \"loi_nhuan_chua_phan_phoi\", \"tai_san_ngan_han\",\n        \"tai_san_co_dinh_huu_hinh\", \"hang_ton_kho\",\n        \"thue_thu_nhap_hoan_lai\", \"N/A (not applicable in VAS)\",\n        \"co_phieu_uu_dai\", \"gia_dong_cua_cuoi_nam\",\n        \"so_luong_co_phieu_luu_hanh\", \"ngay_huy_niem_yet\",\n        \"ly_do_huy_niem_yet\"\n    ],\n    \"VAS Account\": [\n        \"BS.100\", \"BS.400\", \"BS.330\", \"BS.310\",\n        \"IS.10\", \"Computed\", \"IS.60\",\n        \"BS.421\", \"BS.100\", \"BS.221\", \"BS.141\",\n        \"BS.262\", \"—\", \"BS.411b\", \"Market\", \"Market\",\n        \"Profile\", \"Profile\"\n    ]\n})\n\nvariable_map.style.set_properties(**{\n    \"text-align\": \"left\",\n    \"font-size\": \"10pt\"\n}).set_table_styles([\n    {\"selector\": \"th\", \"props\": [\n        (\"background-color\", \"#1f77b4\"),\n        (\"color\", \"white\"),\n        (\"font-weight\", \"bold\"),\n        (\"text-align\", \"left\"),\n        (\"padding\", \"8px\")\n    ]},\n    {\"selector\": \"td\", \"props\": [(\"padding\", \"6px\")]},\n])\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```{=html}\n<style type=\"text/css\">\n#T_e2fdd th {\n  background-color: #1f77b4;\n  color: white;\n  font-weight: bold;\n  text-align: left;\n  padding: 8px;\n}\n#T_e2fdd td {\n  padding: 6px;\n}\n#T_e2fdd_row0_col0, #T_e2fdd_row0_col1, #T_e2fdd_row0_col2, #T_e2fdd_row0_col3, #T_e2fdd_row1_col0, #T_e2fdd_row1_col1, #T_e2fdd_row1_col2, #T_e2fdd_row1_col3, #T_e2fdd_row2_col0, #T_e2fdd_row2_col1, #T_e2fdd_row2_col2, #T_e2fdd_row2_col3, #T_e2fdd_row3_col0, #T_e2fdd_row3_col1, #T_e2fdd_row3_col2, #T_e2fdd_row3_col3, #T_e2fdd_row4_col0, #T_e2fdd_row4_col1, #T_e2fdd_row4_col2, #T_e2fdd_row4_col3, #T_e2fdd_row5_col0, #T_e2fdd_row5_col1, #T_e2fdd_row5_col2, #T_e2fdd_row5_col3, #T_e2fdd_row6_col0, #T_e2fdd_row6_col1, #T_e2fdd_row6_col2, #T_e2fdd_row6_col3, #T_e2fdd_row7_col0, #T_e2fdd_row7_col1, #T_e2fdd_row7_col2, #T_e2fdd_row7_col3, #T_e2fdd_row8_col0, #T_e2fdd_row8_col1, #T_e2fdd_row8_col2, #T_e2fdd_row8_col3, #T_e2fdd_row9_col0, #T_e2fdd_row9_col1, #T_e2fdd_row9_col2, #T_e2fdd_row9_col3, #T_e2fdd_row10_col0, #T_e2fdd_row10_col1, #T_e2fdd_row10_col2, #T_e2fdd_row10_col3, #T_e2fdd_row11_col0, #T_e2fdd_row11_col1, #T_e2fdd_row11_col2, #T_e2fdd_row11_col3, #T_e2fdd_row12_col0, #T_e2fdd_row12_col1, #T_e2fdd_row12_col2, #T_e2fdd_row12_col3, #T_e2fdd_row13_col0, #T_e2fdd_row13_col1, #T_e2fdd_row13_col2, #T_e2fdd_row13_col3, #T_e2fdd_row14_col0, #T_e2fdd_row14_col1, #T_e2fdd_row14_col2, #T_e2fdd_row14_col3, #T_e2fdd_row15_col0, #T_e2fdd_row15_col1, #T_e2fdd_row15_col2, #T_e2fdd_row15_col3, #T_e2fdd_row16_col0, #T_e2fdd_row16_col1, #T_e2fdd_row16_col2, #T_e2fdd_row16_col3, #T_e2fdd_row17_col0, #T_e2fdd_row17_col1, #T_e2fdd_row17_col2, #T_e2fdd_row17_col3 {\n  text-align: left;\n  font-size: 10pt;\n}\n</style>\n<table id=\"T_e2fdd\">\n  <thead>\n    <tr>\n      <th class=\"blank level0\" >&nbsp;</th>\n      <th id=\"T_e2fdd_level0_col0\" class=\"col_heading level0 col0\" >Compustat Variable</th>\n      <th id=\"T_e2fdd_level0_col1\" class=\"col_heading level0 col1\" >Description</th>\n      <th id=\"T_e2fdd_level0_col2\" class=\"col_heading level0 col2\" >DataCore.vn Equivalent</th>\n      <th id=\"T_e2fdd_level0_col3\" class=\"col_heading level0 col3\" >VAS Account</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th id=\"T_e2fdd_level0_row0\" class=\"row_heading level0 row0\" >0</th>\n      <td id=\"T_e2fdd_row0_col0\" class=\"data row0 col0\" >AT</td>\n      <td id=\"T_e2fdd_row0_col1\" class=\"data row0 col1\" >Total Assets</td>\n      <td id=\"T_e2fdd_row0_col2\" class=\"data row0 col2\" >tong_tai_san</td>\n      <td id=\"T_e2fdd_row0_col3\" class=\"data row0 col3\" >BS.100</td>\n    </tr>\n    <tr>\n      <th id=\"T_e2fdd_level0_row1\" class=\"row_heading level0 row1\" >1</th>\n      <td id=\"T_e2fdd_row1_col0\" class=\"data row1 col0\" >SEQ</td>\n      <td id=\"T_e2fdd_row1_col1\" class=\"data row1 col1\" >Stockholders' Equity</td>\n      <td id=\"T_e2fdd_row1_col2\" class=\"data row1 col2\" >von_chu_so_huu</td>\n      <td id=\"T_e2fdd_row1_col3\" class=\"data row1 col3\" >BS.400</td>\n    </tr>\n    <tr>\n      <th id=\"T_e2fdd_level0_row2\" class=\"row_heading level0 row2\" >2</th>\n      <td id=\"T_e2fdd_row2_col0\" class=\"data row2 col0\" >LT</td>\n      <td id=\"T_e2fdd_row2_col1\" class=\"data row2 col1\" >Long-term Debt</td>\n      <td id=\"T_e2fdd_row2_col2\" class=\"data row2 col2\" >no_dai_han</td>\n      <td id=\"T_e2fdd_row2_col3\" class=\"data row2 col3\" >BS.330</td>\n    </tr>\n    <tr>\n      <th id=\"T_e2fdd_level0_row3\" class=\"row_heading level0 row3\" >3</th>\n      <td id=\"T_e2fdd_row3_col0\" class=\"data row3 col0\" >LCT</td>\n      <td id=\"T_e2fdd_row3_col1\" class=\"data row3 col1\" >Current Liabilities</td>\n      <td id=\"T_e2fdd_row3_col2\" class=\"data row3 col2\" >no_ngan_han</td>\n      <td id=\"T_e2fdd_row3_col3\" class=\"data row3 col3\" >BS.310</td>\n    </tr>\n    <tr>\n      <th id=\"T_e2fdd_level0_row4\" class=\"row_heading level0 row4\" >4</th>\n      <td id=\"T_e2fdd_row4_col0\" class=\"data row4 col0\" >SALE</td>\n      <td id=\"T_e2fdd_row4_col1\" class=\"data row4 col1\" >Net Sales/Revenue</td>\n      <td id=\"T_e2fdd_row4_col2\" class=\"data row4 col2\" >doanh_thu_thuan</td>\n      <td id=\"T_e2fdd_row4_col3\" class=\"data row4 col3\" >IS.10</td>\n    </tr>\n    <tr>\n      <th id=\"T_e2fdd_level0_row5\" class=\"row_heading level0 row5\" >5</th>\n      <td id=\"T_e2fdd_row5_col0\" class=\"data row5 col0\" >EBIT</td>\n      <td id=\"T_e2fdd_row5_col1\" class=\"data row5 col1\" >Earnings Before Interest & Taxes</td>\n      <td id=\"T_e2fdd_row5_col2\" class=\"data row5 col2\" >loi_nhuan_truoc_thue_va_lai_vay</td>\n      <td id=\"T_e2fdd_row5_col3\" class=\"data row5 col3\" >Computed</td>\n    </tr>\n    <tr>\n      <th id=\"T_e2fdd_level0_row6\" class=\"row_heading level0 row6\" >6</th>\n      <td id=\"T_e2fdd_row6_col0\" class=\"data row6 col0\" >NI</td>\n      <td id=\"T_e2fdd_row6_col1\" class=\"data row6 col1\" >Net Income</td>\n      <td id=\"T_e2fdd_row6_col2\" class=\"data row6 col2\" >loi_nhuan_sau_thue</td>\n      <td id=\"T_e2fdd_row6_col3\" class=\"data row6 col3\" >IS.60</td>\n    </tr>\n    <tr>\n      <th id=\"T_e2fdd_level0_row7\" class=\"row_heading level0 row7\" >7</th>\n      <td id=\"T_e2fdd_row7_col0\" class=\"data row7 col0\" >RE</td>\n      <td id=\"T_e2fdd_row7_col1\" class=\"data row7 col1\" >Retained Earnings</td>\n      <td id=\"T_e2fdd_row7_col2\" class=\"data row7 col2\" >loi_nhuan_chua_phan_phoi</td>\n      <td id=\"T_e2fdd_row7_col3\" class=\"data row7 col3\" >BS.421</td>\n    </tr>\n    <tr>\n      <th id=\"T_e2fdd_level0_row8\" class=\"row_heading level0 row8\" >8</th>\n      <td id=\"T_e2fdd_row8_col0\" class=\"data row8 col0\" >ACT</td>\n      <td id=\"T_e2fdd_row8_col1\" class=\"data row8 col1\" >Current Assets</td>\n      <td id=\"T_e2fdd_row8_col2\" class=\"data row8 col2\" >tai_san_ngan_han</td>\n      <td id=\"T_e2fdd_row8_col3\" class=\"data row8 col3\" >BS.100</td>\n    </tr>\n    <tr>\n      <th id=\"T_e2fdd_level0_row9\" class=\"row_heading level0 row9\" >9</th>\n      <td id=\"T_e2fdd_row9_col0\" class=\"data row9 col0\" >PPENT</td>\n      <td id=\"T_e2fdd_row9_col1\" class=\"data row9 col1\" >Net Plant & Equipment</td>\n      <td id=\"T_e2fdd_row9_col2\" class=\"data row9 col2\" >tai_san_co_dinh_huu_hinh</td>\n      <td id=\"T_e2fdd_row9_col3\" class=\"data row9 col3\" >BS.221</td>\n    </tr>\n    <tr>\n      <th id=\"T_e2fdd_level0_row10\" class=\"row_heading level0 row10\" >10</th>\n      <td id=\"T_e2fdd_row10_col0\" class=\"data row10 col0\" >INVT</td>\n      <td id=\"T_e2fdd_row10_col1\" class=\"data row10 col1\" >Total Inventories</td>\n      <td id=\"T_e2fdd_row10_col2\" class=\"data row10 col2\" >hang_ton_kho</td>\n      <td id=\"T_e2fdd_row10_col3\" class=\"data row10 col3\" >BS.141</td>\n    </tr>\n    <tr>\n      <th id=\"T_e2fdd_level0_row11\" class=\"row_heading level0 row11\" >11</th>\n      <td id=\"T_e2fdd_row11_col0\" class=\"data row11 col0\" >TXDB</td>\n      <td id=\"T_e2fdd_row11_col1\" class=\"data row11 col1\" >Deferred Taxes</td>\n      <td id=\"T_e2fdd_row11_col2\" class=\"data row11 col2\" >thue_thu_nhap_hoan_lai</td>\n      <td id=\"T_e2fdd_row11_col3\" class=\"data row11 col3\" >BS.262</td>\n    </tr>\n    <tr>\n      <th id=\"T_e2fdd_level0_row12\" class=\"row_heading level0 row12\" >12</th>\n      <td id=\"T_e2fdd_row12_col0\" class=\"data row12 col0\" >ITCB</td>\n      <td id=\"T_e2fdd_row12_col1\" class=\"data row12 col1\" >Investment Tax Credit</td>\n      <td id=\"T_e2fdd_row12_col2\" class=\"data row12 col2\" >N/A (not applicable in VAS)</td>\n      <td id=\"T_e2fdd_row12_col3\" class=\"data row12 col3\" >—</td>\n    </tr>\n    <tr>\n      <th id=\"T_e2fdd_level0_row13\" class=\"row_heading level0 row13\" >13</th>\n      <td id=\"T_e2fdd_row13_col0\" class=\"data row13 col0\" >PSTK/PSTKRV/PSTKL</td>\n      <td id=\"T_e2fdd_row13_col1\" class=\"data row13 col1\" >Preferred Stock (various)</td>\n      <td id=\"T_e2fdd_row13_col2\" class=\"data row13 col2\" >co_phieu_uu_dai</td>\n      <td id=\"T_e2fdd_row13_col3\" class=\"data row13 col3\" >BS.411b</td>\n    </tr>\n    <tr>\n      <th id=\"T_e2fdd_level0_row14\" class=\"row_heading level0 row14\" >14</th>\n      <td id=\"T_e2fdd_row14_col0\" class=\"data row14 col0\" >PRCC_C</td>\n      <td id=\"T_e2fdd_row14_col1\" class=\"data row14 col1\" >Price Close (Calendar Year)</td>\n      <td id=\"T_e2fdd_row14_col2\" class=\"data row14 col2\" >gia_dong_cua_cuoi_nam</td>\n      <td id=\"T_e2fdd_row14_col3\" class=\"data row14 col3\" >Market</td>\n    </tr>\n    <tr>\n      <th id=\"T_e2fdd_level0_row15\" class=\"row_heading level0 row15\" >15</th>\n      <td id=\"T_e2fdd_row15_col0\" class=\"data row15 col0\" >CSHO</td>\n      <td id=\"T_e2fdd_row15_col1\" class=\"data row15 col1\" >Common Shares Outstanding</td>\n      <td id=\"T_e2fdd_row15_col2\" class=\"data row15 col2\" >so_luong_co_phieu_luu_hanh</td>\n      <td id=\"T_e2fdd_row15_col3\" class=\"data row15 col3\" >Market</td>\n    </tr>\n    <tr>\n      <th id=\"T_e2fdd_level0_row16\" class=\"row_heading level0 row16\" >16</th>\n      <td id=\"T_e2fdd_row16_col0\" class=\"data row16 col0\" >DLDTE</td>\n      <td id=\"T_e2fdd_row16_col1\" class=\"data row16 col1\" >Delisting Date</td>\n      <td id=\"T_e2fdd_row16_col2\" class=\"data row16 col2\" >ngay_huy_niem_yet</td>\n      <td id=\"T_e2fdd_row16_col3\" class=\"data row16 col3\" >Profile</td>\n    </tr>\n    <tr>\n      <th id=\"T_e2fdd_level0_row17\" class=\"row_heading level0 row17\" >17</th>\n      <td id=\"T_e2fdd_row17_col0\" class=\"data row17 col0\" >DLRSN</td>\n      <td id=\"T_e2fdd_row17_col1\" class=\"data row17 col1\" >Delisting Reason</td>\n      <td id=\"T_e2fdd_row17_col2\" class=\"data row17 col2\" >ly_do_huy_niem_yet</td>\n      <td id=\"T_e2fdd_row17_col3\" class=\"data row17 col3\" >Profile</td>\n    </tr>\n  </tbody>\n</table>\n```\n:::\n:::\n\n\n## Kiểm tra chất lượng dữ liệu\n\nTrước khi tính bất kỳ thước đo nào, chúng ta thực hiện các kiểm tra chất lượng dữ liệu thiết yếu, đặc biệt quan trọng đối với dữ liệu Việt Nam.\n\n::: {#data-quality-checks .cell execution_count=4}\n``` {.python .cell-code code-summary=\"Data quality validation\"}\ndef data_quality_report(df):\n    \"\"\"Generate a comprehensive data quality report.\"\"\"\n    report = {}\n\n    # Check for negative total assets\n    report[\"Negative total assets\"] = (df[\"at\"] < 0).sum()\n\n    # Check for negative equity (acceptable but noteworthy)\n    report[\"Negative equity\"] = (df[\"seq\"] <= 0).sum()\n\n    # Check for missing critical variables\n    critical_vars = [\"at\", \"seq\", \"sale\", \"ebit\", \"me\"]\n    for var in critical_vars:\n        report[f\"Missing {var}\"] = df[var].isna().sum()\n\n    # Check for extreme values (potential data errors)\n    report[\"Extreme leverage (>100%)\"] = (df[\"tlb\"] / df[\"at\"] > 1.0).sum()\n    report[\"Extreme sales/assets (>10)\"] = (df[\"sale\"] / df[\"at\"] > 10).sum()\n\n    return pd.Series(report, name=\"Count\")\n\nquality = data_quality_report(df)\nprint(\"Data Quality Report\")\nprint(\"=\" * 45)\nfor item, count in quality.items():\n    status = \"✓\" if count == 0 else \"⚠\"\n    print(f\"  {status} {item}: {count:,}\")\n\n# Apply filters\ndf_clean = df.copy()\ndf_clean = df_clean[df_clean[\"at\"] > 0]  # Positive total assets\ndf_clean = df_clean[df_clean[\"seq\"] > 0]  # Positive equity (for BE calculation)\nprint(f\"\\nObservations after cleaning: {len(df_clean):,} \"\n      f\"(dropped {len(df) - len(df_clean):,})\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nData Quality Report\n=============================================\n  ✓ Negative total assets: 0\n  ✓ Negative equity: 0\n  ✓ Missing at: 0\n  ✓ Missing seq: 0\n  ✓ Missing sale: 0\n  ✓ Missing ebit: 0\n  ✓ Missing me: 0\n  ✓ Extreme leverage (>100%): 0\n  ✓ Extreme sales/assets (>10): 0\n\nObservations after cleaning: 3,484 (dropped 0)\n```\n:::\n:::\n\n\n# Tính Q của Tobin {#sec-valuation-tobinq-computation}\n\n## Giá trị sổ sách của vốn chủ sở hữu\n\nTheo @daniel1997evidence, chúng ta tính giá trị sổ sách của vốn chủ sở hữu như sau:\n\n$$\nBE = SEQ + TXDB + ITCB - PREF\n$$ {#eq-book-equity}\n\ntrong đó $PREF$ là giá trị cổ phiếu ưu đãi, sử dụng giá trị hoàn lại nếu có, nếu không thì dùng giá trị thanh lý, và sau cùng là giá trị ghi sổ như phương án dự phòng cuối cùng. Trong bối cảnh Việt Nam, cổ phiếu ưu đãi tương đối hiếm trong các công ty niêm yết, nên $PREF$ thường bằng không.\n\n::: {#compute-book-equity .cell execution_count=5}\n``` {.python .cell-code code-summary=\"Book value of equity computation\"}\ndef compute_book_equity(df):\n    \"\"\"\n    Compute book value of equity following Daniel and Titman (1997).\n\n    In Vietnam, preferred stock is uncommon among listed firms.\n    The investment tax credit (ITCB) is not applicable under VAS,\n    so we set it to zero when missing.\n    \"\"\"\n    result = df.copy()\n\n    # Preferred stock: use coalesce logic\n    result[\"pref\"] = result[\"pstk\"].fillna(0)\n\n    # Book equity = Shareholders' equity + Deferred taxes + ITC - Preferred\n    result[\"be\"] = (\n        result[\"seq\"]\n        + result[\"txdb\"].fillna(0)\n        + result[\"itcb\"].fillna(0)\n        - result[\"pref\"]\n    )\n\n    return result\n\ndf_clean = compute_book_equity(df_clean)\n\nprint(\"Book Equity Summary Statistics (VND millions)\")\nprint(df_clean[\"be\"].describe().apply(lambda x: f\"{x:,.0f}\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBook Equity Summary Statistics (VND millions)\ncount          3,484\nmean       3,521,607\nstd        9,055,435\nmin            4,633\n25%          386,441\n50%        1,112,062\n75%        3,210,269\nmax      247,845,397\nName: be, dtype: str\n```\n:::\n:::\n\n\n## Giá trị thị trường của vốn chủ sở hữu\n\nGiá trị thị trường của vốn chủ sở hữu được tính bằng giá cổ phiếu cuối năm dương lịch và số cổ phiếu đang lưu hành:\n\n$$\nME = P_{\\text{close}} \\times \\text{CSHO}\n$$ {#eq-market-equity}\n\nĐối với các doanh nghiệp Việt Nam, giá trị này lấy từ giá đóng cửa vào ngày giao dịch cuối cùng của năm tài chính. Hầu hết doanh nghiệp Việt Nam kết thúc năm tài chính vào ngày 31 tháng 12, dù một số (đặc biệt trong nông nghiệp và ngân hàng) có thể khác.\n\n::: {#compute-market-equity .cell execution_count=6}\n``` {.python .cell-code code-summary=\"Market value of equity computation\"}\n# ME is already computed in our simulated data as prcc * csho\n# In practice with DataCore.vn:\n#   me = df[\"gia_dong_cua_cuoi_nam\"] * df[\"so_luong_co_phieu_luu_hanh\"]\n\ndf_clean[\"me\"] = df_clean[\"prcc\"] * df_clean[\"csho\"]\n\nprint(\"Market Equity Summary Statistics (VND millions)\")\nprint(df_clean[\"me\"].describe().apply(lambda x: f\"{x:,.0f}\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMarket Equity Summary Statistics (VND millions)\ncount          3,484\nmean       3,653,445\nstd        9,747,318\nmin            3,379\n25%          370,119\n50%        1,106,646\n75%        3,029,093\nmax      286,258,816\nName: me, dtype: str\n```\n:::\n:::\n\n\n## Q của Tobin giản lược\n\nChúng ta triển khai phiên bản giản lược của @gompers2003corporate:\n\n$$\nQ_{\\text{simple}} = \\frac{AT + ME - BE}{AT}\n$$ {#eq-tobinq-implementation}\n\nCông thức này có thể viết lại thành:\n\n$$\nQ_{\\text{simple}} = 1 + \\frac{ME - BE}{AT}\n$$ {#eq-tobinq-rewritten}\n\ngiúp cách diễn giải trở nên rõ ràng: Q của Tobin bằng một cộng với phần bù (hoặc chiết khấu) giữa giá trị thị trường và giá trị sổ sách, chia cho tổng tài sản.\n\n::: {#compute-tobinq .cell execution_count=7}\n``` {.python .cell-code code-summary=\"Tobin's Q computation with multiple variants\"}\ndef compute_tobins_q(df):\n    \"\"\"\n    Compute multiple variants of Tobin's Q.\n\n    Variants:\n    1. Simple Q (Gompers et al., 2003)\n    2. Chung-Pruitt Q\n    3. Market-to-Book ratio (for comparison)\n    \"\"\"\n    result = df.copy()\n\n    # --- Variant 1: Simple Q (Gompers, Ishii, Metrick 2003) ---\n    result[\"tobin_q_simple\"] = (result[\"at\"] + result[\"me\"] - result[\"be\"]) / result[\"at\"]\n\n    # --- Variant 2: Chung-Pruitt Approximation ---\n    # DEBT = Current Liabilities - Current Assets + Inventories + LT Debt\n    result[\"debt_cp\"] = (\n        result[\"lct\"].fillna(0)\n        - result[\"act\"].fillna(0)\n        + result[\"invt\"].fillna(0)\n        + result[\"lt\"].fillna(0)\n    )\n    result[\"tobin_q_cp\"] = (\n        (result[\"me\"] + result[\"pstk\"].fillna(0) + result[\"debt_cp\"]) / result[\"at\"]\n    )\n\n    # --- Market-to-Book Ratio ---\n    result[\"mtb\"] = np.where(result[\"be\"] > 0, result[\"me\"] / result[\"be\"], np.nan)\n\n    return result\n\ndf_clean = compute_tobins_q(df_clean)\n\n# Summary statistics\nq_vars = [\"tobin_q_simple\", \"tobin_q_cp\", \"mtb\"]\nq_summary = df_clean[q_vars].describe(percentiles=[0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99])\nq_summary = q_summary.round(3)\nq_summary.columns = [\"Simple Q\", \"Chung-Pruitt Q\", \"Market-to-Book\"]\n\nprint(\"Tobin's Q Summary Statistics\")\nprint(q_summary.to_string())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTobin's Q Summary Statistics\n       Simple Q  Chung-Pruitt Q  Market-to-Book\ncount  3484.000        3484.000        3484.000\nmean      1.031           0.766           1.058\nstd       0.243           0.296           0.445\nmin       0.357           0.008           0.233\n1%        0.602           0.189           0.382\n5%        0.713           0.332           0.496\n25%       0.886           0.568           0.742\n50%       0.989           0.738           0.974\n75%       1.132           0.926           1.287\n95%       1.481           1.290           1.904\n99%       1.916           1.668           2.492\nmax       2.804           2.433           3.189\n```\n:::\n:::\n\n\n## Áp dụng winsorization cho các giá trị cực đoan\n\nGiá trị Q của Tobin có thể bị ảnh hưởng nặng bởi các giá trị ngoại lai, đặc biệt ở các thị trường mới nổi nơi chất lượng dữ liệu có thể không đồng đều. Chúng ta thực hiện winsorization tại phân vị thứ 1 và thứ 99.\n\n::: {#winsorize .cell execution_count=8}\n``` {.python .cell-code code-summary=\"Winsorization of extreme values\"}\ndef winsorize(series, lower=0.01, upper=0.99):\n    \"\"\"Winsorize a pandas Series at specified percentiles.\"\"\"\n    low = series.quantile(lower)\n    high = series.quantile(upper)\n    return series.clip(lower=low, upper=high)\n\n# Winsorize Q measures\nfor var in [\"tobin_q_simple\", \"tobin_q_cp\", \"mtb\"]:\n    df_clean[f\"{var}_w\"] = winsorize(df_clean[var])\n\nprint(\"Effect of Winsorization on Simple Tobin's Q:\")\nprint(f\"  Before: mean={df_clean['tobin_q_simple'].mean():.3f}, \"\n      f\"std={df_clean['tobin_q_simple'].std():.3f}\")\nprint(f\"  After:  mean={df_clean['tobin_q_simple_w'].mean():.3f}, \"\n      f\"std={df_clean['tobin_q_simple_w'].std():.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEffect of Winsorization on Simple Tobin's Q:\n  Before: mean=1.031, std=0.243\n  After:  mean=1.030, std=0.233\n```\n:::\n:::\n\n\n## Phân phối chéo của Q của Tobin\n\n::: {#cell-fig-tobinq-distribution .cell execution_count=9}\n``` {.python .cell-code}\nfig, axes = plt.subplots(1, 2, figsize=(14, 5))\n\n# Latest year distribution\nlatest_year = df_clean[\"year\"].max()\nlatest_data = df_clean[df_clean[\"year\"] == latest_year]\n\n# Histogram\naxes[0].hist(\n    latest_data[\"tobin_q_simple_w\"].dropna(),\n    bins=50, color=colors[\"primary\"], alpha=0.7, edgecolor=\"white\"\n)\naxes[0].axvline(x=1, color=colors[\"quaternary\"], linestyle=\"--\", linewidth=2, label=\"Q = 1\")\naxes[0].set_xlabel(\"Tobin's Q (Simple)\")\naxes[0].set_ylabel(\"Number of Firms\")\naxes[0].set_title(f\"Cross-Sectional Distribution ({latest_year})\")\naxes[0].legend()\n\n# Box plot by exchange\nexchange_data = latest_data[[\"exchange\", \"tobin_q_simple_w\"]].dropna()\nexchanges_sorted = exchange_data.groupby(\"exchange\")[\"tobin_q_simple_w\"].median().sort_values().index\n\nbox_data = [exchange_data[exchange_data[\"exchange\"] == ex][\"tobin_q_simple_w\"].values\n            for ex in exchanges_sorted]\n\nbp = axes[1].boxplot(box_data, labels=exchanges_sorted, patch_artist=True,\n                     medianprops=dict(color=\"black\", linewidth=2))\nbox_colors = [colors[\"primary\"], colors[\"secondary\"], colors[\"tertiary\"]]\nfor patch, color in zip(bp[\"boxes\"], box_colors):\n    patch.set_facecolor(color)\n    patch.set_alpha(0.7)\n\naxes[1].axhline(y=1, color=colors[\"quaternary\"], linestyle=\"--\", linewidth=1.5, alpha=0.7)\naxes[1].set_ylabel(\"Tobin's Q (Simple)\")\naxes[1].set_title(f\"Tobin's Q by Exchange ({latest_year})\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Phân phối của Q của Tobin trên các doanh nghiệp niêm yết Việt Nam (2024). Đường nét đứt thẳng đứng tại Q=1 biểu thị ngưỡng lý thuyết mà tại đó giá trị thị trường bằng chi phí thay thế.](36_valuation_files/figure-html/fig-tobinq-distribution-output-1.png){#fig-tobinq-distribution width=2076 height=727}\n:::\n:::\n\n\n## Diễn biến chuỗi thời gian của Q của Tobin\n\n::: {#cell-fig-tobinq-timeseries .cell execution_count=10}\n``` {.python .cell-code}\n# Compute annual statistics by exchange\nannual_q = (\n    df_clean\n    .groupby([\"year\", \"exchange\"])[\"tobin_q_simple_w\"]\n    .agg([\"median\", lambda x: x.quantile(0.25), lambda x: x.quantile(0.75)])\n    .reset_index()\n)\nannual_q.columns = [\"year\", \"exchange\", \"median\", \"q25\", \"q75\"]\n\nfig, ax = plt.subplots(figsize=(12, 6))\n\nexchange_colors = {\"HOSE\": colors[\"primary\"], \"HNX\": colors[\"secondary\"],\n                   \"UPCoM\": colors[\"tertiary\"]}\n\nfor exchange, color in exchange_colors.items():\n    data = annual_q[annual_q[\"exchange\"] == exchange]\n    ax.plot(data[\"year\"], data[\"median\"], color=color, linewidth=2.5,\n            label=exchange, marker=\"o\", markersize=4)\n    ax.fill_between(data[\"year\"], data[\"q25\"], data[\"q75\"],\n                    color=color, alpha=0.15)\n\nax.axhline(y=1, color=\"gray\", linestyle=\"--\", linewidth=1, alpha=0.7, label=\"Q = 1\")\nax.set_xlabel(\"Year\")\nax.set_ylabel(\"Tobin's Q (Median)\")\nax.set_title(\"Evolution of Tobin's Q in the Vietnamese Market\")\nax.legend(loc=\"upper right\")\nax.set_xlim(2008, latest_year)\nax.xaxis.set_major_locator(mticker.MultipleLocator(2))\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Diễn biến của Q của Tobin trung vị trên các sàn giao dịch Việt Nam (2008–2024). Vùng tô bóng biểu thị khoảng tứ phân vị.](36_valuation_files/figure-html/fig-tobinq-timeseries-output-1.png){#fig-tobinq-timeseries width=1775 height=877}\n:::\n:::\n\n\n## Q của Tobin theo ngành\n\n::: {#cell-fig-tobinq-industry .cell execution_count=11}\n``` {.python .cell-code}\nlatest_industry_q = (\n    latest_data\n    .groupby(\"industry\")[\"tobin_q_simple_w\"]\n    .agg([\"median\", \"mean\", \"count\"])\n    .reset_index()\n    .sort_values(\"median\", ascending=True)\n)\n\nfig, ax = plt.subplots(figsize=(10, 8))\n\nbar_colors = [colors[\"quaternary\"] if m < 1 else colors[\"primary\"]\n              for m in latest_industry_q[\"median\"]]\n\nax.barh(\n    latest_industry_q[\"industry\"],\n    latest_industry_q[\"median\"],\n    color=bar_colors, alpha=0.8, edgecolor=\"white\"\n)\nax.axvline(x=1, color=\"gray\", linestyle=\"--\", linewidth=1.5, alpha=0.7)\nax.set_xlabel(\"Median Tobin's Q\")\nax.set_title(f\"Tobin's Q by Industry ({latest_year})\")\n\n# Add count annotations\nfor i, (_, row) in enumerate(latest_industry_q.iterrows()):\n    ax.text(row[\"median\"] + 0.02, i, f'n={int(row[\"count\"])}',\n            va=\"center\", fontsize=9, color=\"gray\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Q của Tobin trung vị theo ngành ở Việt Nam (năm gần nhất có sẵn). Các ngành được sắp xếp theo giá trị Q trung vị.](36_valuation_files/figure-html/fig-tobinq-industry-output-1.png){#fig-tobinq-industry width=1474 height=1177}\n:::\n:::\n\n\n# Tính điểm Z của Altman {#sec-valuation-zscore-computation}\n\n## Điểm Z gốc cho doanh nghiệp niêm yết\n\n::: {#compute-zscore .cell execution_count=12}\n``` {.python .cell-code code-summary=\"Altman Z-Score computation (all three variants)\"}\ndef compute_altman_z(df):\n    \"\"\"\n    Compute three variants of the Altman Z-Score:\n    1. Original Z-Score (for listed manufacturing firms)\n    2. Z'-Score (for private firms, using book equity)\n    3. Z''-Score (for emerging markets / non-manufacturing)\n    \"\"\"\n    result = df.copy()\n\n    # Common components\n    result[\"wc\"] = result[\"act\"].fillna(0) - result[\"lct\"].fillna(0)  # Working Capital\n\n    # --- Original Z-Score ---\n    # Z = 3.3*(EBIT/TA) + 0.999*(Sales/TA) + 0.6*(ME/TL) + 1.2*(WC/TA) + 1.4*(RE/TA)\n    x1 = result[\"ebit\"] / result[\"at\"]\n    x2 = result[\"sale\"] / result[\"at\"]\n    x3 = np.where(result[\"tlb\"] > 0, result[\"me\"] / result[\"tlb\"], np.nan)\n    x4 = result[\"wc\"] / result[\"at\"]\n    x5 = result[\"re_var\"].fillna(0) / result[\"at\"]\n\n    result[\"z_x1\"] = x1  # Earning power\n    result[\"z_x2\"] = x2  # Asset turnover\n    result[\"z_x3\"] = x3  # Leverage (inverse)\n    result[\"z_x4\"] = x4  # Liquidity\n    result[\"z_x5\"] = x5  # Cumulative profitability\n\n    result[\"altman_z\"] = (3.3 * x1 + 0.999 * x2 + 0.6 * x3 + 1.2 * x4 + 1.4 * x5)\n\n    # --- Z'-Score (Private firms) ---\n    x3_prime = np.where(result[\"tlb\"] > 0, result[\"be\"] / result[\"tlb\"], np.nan)\n    result[\"altman_z_prime\"] = (\n        0.717 * x4 + 0.847 * x5 + 3.107 * x1 + 0.420 * x3_prime + 0.998 * x2\n    )\n\n    # --- Z''-Score (Emerging Markets) ---\n    result[\"altman_z_em\"] = (\n        3.25\n        + 6.56 * x4   # Working Capital / TA\n        + 3.26 * x5   # Retained Earnings / TA\n        + 6.72 * x1   # EBIT / TA\n        + 1.05 * x3_prime  # Book Equity / TL\n    )\n\n    # Classify risk zones\n    result[\"z_zone\"] = pd.cut(\n        result[\"altman_z\"],\n        bins=[-np.inf, 1.80, 2.70, 2.99, np.inf],\n        labels=[\"High Distress\", \"Distress\", \"Grey Zone\", \"Safe\"]\n    )\n\n    result[\"z_em_zone\"] = pd.cut(\n        result[\"altman_z_em\"],\n        bins=[-np.inf, 1.10, 2.60, np.inf],\n        labels=[\"Distress\", \"Grey Zone\", \"Safe\"]\n    )\n\n    return result\n\ndf_clean = compute_altman_z(df_clean)\n\n# Winsorize Z-scores\nfor var in [\"altman_z\", \"altman_z_prime\", \"altman_z_em\"]:\n    df_clean[f\"{var}_w\"] = winsorize(df_clean[var])\n\nprint(\"Z-Score Summary Statistics\")\nz_summary = df_clean[[\"altman_z\", \"altman_z_prime\", \"altman_z_em\"]].describe().round(3)\nz_summary.columns = [\"Original Z\", \"Z' (Private)\", \"Z'' (Emerging)\"]\nprint(z_summary.to_string())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nZ-Score Summary Statistics\n       Original Z  Z' (Private)  Z'' (Emerging)\ncount    3484.000      3484.000        3484.000\nmean        2.610         2.042           7.467\nstd         1.896         1.194           3.137\nmin         0.059         0.155           1.578\n25%         1.595         1.314           5.670\n50%         2.212         1.806           6.987\n75%         3.028         2.410           8.549\nmax        28.640        11.119          29.686\n```\n:::\n:::\n\n\n## Phân tích các thành phần của điểm Z\n\nViệc hiểu thành phần nào chi phối điểm Z đặc biệt hữu ích trong bối cảnh Việt Nam, nơi một số tỷ số có thể hành xử khác với các thị trường phát triển.\n\n::: {#cell-fig-zscore-components .cell execution_count=13}\n``` {.python .cell-code}\nfig, axes = plt.subplots(2, 3, figsize=(15, 9))\n\ncomponents = [\n    (\"z_x1\", 3.3, \"$3.3 \\\\times$ EBIT/TA\\n(Earning Power)\"),\n    (\"z_x2\", 0.999, \"$0.999 \\\\times$ Sales/TA\\n(Asset Turnover)\"),\n    (\"z_x3\", 0.6, \"$0.6 \\\\times$ ME/TL\\n(Leverage)\"),\n    (\"z_x4\", 1.2, \"$1.2 \\\\times$ WC/TA\\n(Liquidity)\"),\n    (\"z_x5\", 1.4, \"$1.4 \\\\times$ RE/TA\\n(Cum. Profitability)\"),\n]\n\nlatest_z = df_clean[df_clean[\"year\"] == latest_year]\n\nfor idx, (var, weight, label) in enumerate(components):\n    ax = axes[idx // 3, idx % 3]\n    weighted_vals = (latest_z[var] * weight).dropna()\n    weighted_vals = weighted_vals[weighted_vals.between(\n        weighted_vals.quantile(0.01), weighted_vals.quantile(0.99)\n    )]\n    ax.hist(weighted_vals, bins=40, color=colors[\"primary\"], alpha=0.7, edgecolor=\"white\")\n    ax.axvline(x=weighted_vals.median(), color=colors[\"quaternary\"],\n               linestyle=\"--\", linewidth=2, label=f\"Median: {weighted_vals.median():.2f}\")\n    ax.set_title(label, fontsize=11)\n    ax.legend(fontsize=9)\n\n# Remove empty subplot\naxes[1, 2].set_visible(False)\n\nplt.suptitle(f\"Z-Score Component Distributions ({latest_year})\", fontsize=14, y=1.02)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Phân phối các tỷ số thành phần của điểm Z của Altman đối với các doanh nghiệp niêm yết Việt Nam. Mỗi biểu đồ con thể hiện một thành phần được gia quyền theo hệ số của nó trong công thức điểm Z gốc.](36_valuation_files/figure-html/fig-zscore-components-output-1.png){#fig-zscore-components width=2226 height=1381}\n:::\n:::\n\n\n## Phân phối các vùng rủi ro\n\n::: {#cell-fig-zscore-zones .cell execution_count=14}\n``` {.python .cell-code}\nfig, axes = plt.subplots(1, 2, figsize=(14, 6))\n\n# --- Original Z-Score Zones ---\nzone_counts = (\n    df_clean\n    .groupby([\"year\", \"z_zone\"])\n    .size()\n    .unstack(fill_value=0)\n)\nzone_pcts = zone_counts.div(zone_counts.sum(axis=1), axis=0) * 100\n\nzone_colors = {\n    \"Safe\": colors[\"safe\"],\n    \"Grey Zone\": colors[\"alert\"],\n    \"Distress\": colors[\"quaternary\"],\n    \"High Distress\": colors[\"distress\"],\n}\n\naxes[0].stackplot(\n    zone_pcts.index,\n    *[zone_pcts[col] for col in [\"Safe\", \"Grey Zone\", \"Distress\", \"High Distress\"]\n      if col in zone_pcts.columns],\n    labels=[col for col in [\"Safe\", \"Grey Zone\", \"Distress\", \"High Distress\"]\n            if col in zone_pcts.columns],\n    colors=[zone_colors[col] for col in [\"Safe\", \"Grey Zone\", \"Distress\", \"High Distress\"]\n            if col in zone_pcts.columns],\n    alpha=0.8\n)\naxes[0].set_xlabel(\"Year\")\naxes[0].set_ylabel(\"Percentage of Firms\")\naxes[0].set_title(\"Original Z-Score Risk Zones\")\naxes[0].legend(loc=\"upper right\", fontsize=9)\naxes[0].set_ylim(0, 100)\n\n# --- Emerging Market Z''-Score Zones ---\nem_zone_counts = (\n    df_clean\n    .groupby([\"year\", \"z_em_zone\"])\n    .size()\n    .unstack(fill_value=0)\n)\nem_zone_pcts = em_zone_counts.div(em_zone_counts.sum(axis=1), axis=0) * 100\n\nem_zone_colors = {\"Safe\": colors[\"safe\"], \"Grey Zone\": colors[\"alert\"],\n                  \"Distress\": colors[\"quaternary\"]}\n\naxes[1].stackplot(\n    em_zone_pcts.index,\n    *[em_zone_pcts[col] for col in [\"Safe\", \"Grey Zone\", \"Distress\"]\n      if col in em_zone_pcts.columns],\n    labels=[col for col in [\"Safe\", \"Grey Zone\", \"Distress\"]\n            if col in em_zone_pcts.columns],\n    colors=[em_zone_colors[col] for col in [\"Safe\", \"Grey Zone\", \"Distress\"]\n            if col in em_zone_pcts.columns],\n    alpha=0.8\n)\naxes[1].set_xlabel(\"Year\")\naxes[1].set_ylabel(\"Percentage of Firms\")\naxes[1].set_title(\"Emerging Market Z''-Score Risk Zones\")\naxes[1].legend(loc=\"upper right\", fontsize=9)\naxes[1].set_ylim(0, 100)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Tỷ lệ các doanh nghiệp niêm yết Việt Nam trong từng vùng rủi ro của điểm Z của Altman theo thời gian. Hình thể hiện cả các vùng điểm Z gốc và các vùng điểm Z'' cho thị trường mới nổi.](36_valuation_files/figure-html/fig-zscore-zones-output-1.png){#fig-zscore-zones width=2076 height=877}\n:::\n:::\n\n\n## So sánh các biến thể của điểm Z\n\nMột câu hỏi thực tiễn quan trọng là biến thể điểm Z nào phù hợp nhất với các doanh nghiệp Việt Nam. Mô hình gốc được hiệu chỉnh trên các doanh nghiệp sản xuất của Hoa Kỳ, trong khi điểm Z'' được thiết kế riêng cho thị trường mới nổi và các ngành phi sản xuất.\n\n::: {#cell-fig-zscore-comparison .cell execution_count=15}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(8, 8))\n\nsample = latest_z.dropna(subset=[\"altman_z_w\", \"altman_z_em_w\"]).sample(\n    min(500, len(latest_z)), random_state=42\n)\n\nscatter = ax.scatter(\n    sample[\"altman_z_w\"], sample[\"altman_z_em_w\"],\n    c=sample[\"tobin_q_simple_w\"], cmap=\"RdYlGn\",\n    alpha=0.6, s=30, edgecolor=\"white\", linewidth=0.3\n)\n\n# Add reference lines\nlims = [\n    min(ax.get_xlim()[0], ax.get_ylim()[0]),\n    max(ax.get_xlim()[1], ax.get_ylim()[1])\n]\nax.plot(lims, lims, \"k--\", alpha=0.3, linewidth=1, label=\"45° line\")\n\n# Add zone boundaries\nax.axvline(x=1.80, color=\"red\", linestyle=\":\", alpha=0.5, linewidth=1)\nax.axvline(x=2.99, color=\"green\", linestyle=\":\", alpha=0.5, linewidth=1)\nax.axhline(y=1.10, color=\"red\", linestyle=\":\", alpha=0.5, linewidth=1)\nax.axhline(y=2.60, color=\"green\", linestyle=\":\", alpha=0.5, linewidth=1)\n\nax.set_xlabel(\"Original Z-Score\")\nax.set_ylabel(\"Emerging Market Z''-Score\")\nax.set_title(\"Z-Score vs Z''-Score for Vietnamese Firms\")\n\ncbar = plt.colorbar(scatter, ax=ax, shrink=0.8)\ncbar.set_label(\"Tobin's Q\")\n\nax.legend(loc=\"upper left\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![So sánh điểm Z gốc và điểm Z'' cho thị trường mới nổi đối với các doanh nghiệp niêm yết Việt Nam. Các điểm nằm trên (dưới) đường 45 độ có điểm Z'' (điểm Z) cao hơn thước đo còn lại.](36_valuation_files/figure-html/fig-zscore-comparison-output-1.png){#fig-zscore-comparison width=1136 height=1177}\n:::\n:::\n\n\n# Tính tuổi công ty {#sec-valuation-age-computation}\n\n## Nhiều đại diện cho tuổi\n\nĐối với các doanh nghiệp Việt Nam, chúng ta tính ba thước đo tuổi:\n\n$$\n\\text{Age}_{\\text{founding}} = \\text{Current Year} - \\text{Founding Year}\n$$ {#eq-age-founding}\n\n$$\n\\text{Age}_{\\text{listing}} = \\text{Current Year} - \\text{Listing Year}\n$$ {#eq-age-listing}\n\n$$\n\\text{Age}_{\\text{data}} = \\text{Current Year} - \\text{First Year with Data}\n$$ {#eq-age-data}\n\n::: {#compute-age .cell execution_count=16}\n``` {.python .cell-code code-summary=\"Company age computation with multiple proxies\"}\ndef compute_company_age(df):\n    \"\"\"\n    Compute multiple proxies for company age.\n\n    For Vietnamese firms:\n    - Founding age: based on founding/incorporation date\n    - Listing age: based on first listing on HOSE/HNX/UPCoM\n    - Data age: based on first year with available financial data\n    \"\"\"\n    result = df.copy()\n\n    # Founding age\n    result[\"age_founding\"] = result[\"year\"] - result[\"founding_year\"]\n\n    # Listing age\n    result[\"age_listing\"] = result[\"year\"] - result[\"listing_year\"]\n    result[\"age_listing\"] = result[\"age_listing\"].clip(lower=0)\n\n    # Data age (years since first available financial data)\n    first_year = result.groupby(\"ticker\")[\"year\"].transform(\"min\")\n    result[\"age_data\"] = result[\"year\"] - first_year\n\n    # Log of age (commonly used in regressions)\n    result[\"ln_age_founding\"] = np.log1p(result[\"age_founding\"])\n    result[\"ln_age_listing\"] = np.log1p(result[\"age_listing\"])\n\n    return result\n\ndf_clean = compute_company_age(df_clean)\n\nprint(\"Company Age Summary Statistics\")\nage_summary = df_clean[df_clean[\"year\"] == latest_year][\n    [\"age_founding\", \"age_listing\", \"age_data\"]\n].describe().round(1)\nage_summary.columns = [\"Founding Age\", \"Listing Age\", \"Data Age\"]\nprint(age_summary.to_string())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCompany Age Summary Statistics\n       Founding Age  Listing Age  Data Age\ncount         232.0        232.0     232.0\nmean           30.1         13.9      12.3\nstd            11.6          5.8       3.9\nmin            10.0          5.0       5.0\n25%            20.0          9.0       9.0\n50%            30.0         13.0      13.0\n75%            40.0         19.0      16.0\nmax            49.0         24.0      16.0\n```\n:::\n:::\n\n\n## Phân phối tuổi\n\n::: {#cell-fig-age-distribution .cell execution_count=17}\n``` {.python .cell-code}\nfig, axes = plt.subplots(1, 3, figsize=(15, 5))\n\nage_vars = [\n    (\"age_founding\", \"Founding Age (years)\", colors[\"primary\"]),\n    (\"age_listing\", \"Listing Age (years)\", colors[\"secondary\"]),\n    (\"age_data\", \"Data Age (years)\", colors[\"tertiary\"]),\n]\n\nlatest = df_clean[df_clean[\"year\"] == latest_year]\n\nfor ax, (var, label, color) in zip(axes, age_vars):\n    data = latest[var].dropna()\n    ax.hist(data, bins=30, color=color, alpha=0.7, edgecolor=\"white\")\n    ax.axvline(x=data.median(), color=\"black\", linestyle=\"--\",\n               linewidth=2, label=f\"Median: {data.median():.0f}\")\n    ax.set_xlabel(label)\n    ax.set_ylabel(\"Number of Firms\")\n    ax.legend()\n\naxes[0].set_title(\"Founding Age\")\naxes[1].set_title(\"Listing Age\")\naxes[2].set_title(\"Data Age\")\n\nplt.suptitle(f\"Company Age Distributions ({latest_year})\", fontsize=14, y=1.02)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Phân phối các thước đo tuổi công ty đối với các doanh nghiệp niêm yết Việt Nam. Tuổi thành lập phản ánh mức độ trưởng thành thực sự của tổ chức, trong khi tuổi niêm yết phản ánh kinh nghiệm trên thị trường vốn.](36_valuation_files/figure-html/fig-age-distribution-output-1.png){#fig-age-distribution width=2226 height=769}\n:::\n:::\n\n\n## Tuổi và hiệu ứng cổ phần hóa\n\nMột đặc điểm riêng của thị trường Việt Nam là việc cổ phần hóa các SOE. Nhiều doanh nghiệp có ngày thành lập sớm hơn thị trường chứng khoán hàng chục năm, tạo ra khoảng cách lớn giữa tuổi thành lập và tuổi niêm yết.\n\n::: {#cell-fig-age-gap .cell execution_count=18}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(8, 8))\n\nlatest = df_clean[df_clean[\"year\"] == latest_year].copy()\nlatest[\"soe_flag\"] = latest[\"state_ownership_pct\"] > 30  # SOE proxy\n\nfor soe, label, color, marker in [\n    (True, \"SOE (>30% state)\", colors[\"quaternary\"], \"s\"),\n    (False, \"Non-SOE\", colors[\"primary\"], \"o\"),\n]:\n    subset = latest[latest[\"soe_flag\"] == soe]\n    ax.scatter(\n        subset[\"age_listing\"], subset[\"age_founding\"],\n        c=color, alpha=0.5, s=25, marker=marker, label=label, edgecolor=\"white\"\n    )\n\n# 45-degree line\nmax_age = max(latest[\"age_founding\"].max(), latest[\"age_listing\"].max())\nax.plot([0, max_age], [0, max_age], \"k--\", alpha=0.3, label=\"Founding = Listing age\")\n\nax.set_xlabel(\"Listing Age (years)\")\nax.set_ylabel(\"Founding Age (years)\")\nax.set_title(\"Founding vs. Listing Age: The Equitization Gap\")\nax.legend()\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Mối quan hệ giữa tuổi thành lập và tuổi niêm yết của các doanh nghiệp Việt Nam. Khoảng cách phản ánh số năm hoạt động trước khi niêm yết, đặc biệt lớn đối với các doanh nghiệp nhà nước đã cổ phần hóa.](36_valuation_files/figure-html/fig-age-gap-output-1.png){#fig-age-gap width=1176 height=1177}\n:::\n:::\n\n\n# Phân tích kết hợp: Định giá, kiệt quệ và mức độ trưởng thành {#sec-valuation-joint-analysis}\n\n## Mối quan hệ giữa Q, điểm Z và tuổi\n\nBa thước đo này phản ánh những khía cạnh khác nhau về vị thế tài chính của doanh nghiệp, nhưng chúng không độc lập với nhau. Về mặt lý thuyết, chúng ta kỳ vọng:\n\n-   **Q và Z**: Các doanh nghiệp có nhiều cơ hội tăng trưởng (Q cao) thường khỏe mạnh hơn về tài chính (Z cao), nhưng mối quan hệ không đơn điệu, giá trị Q rất cao có thể cho thấy sự định giá quá cao mang tính đầu cơ.\n-   **Q và tuổi**: Các doanh nghiệp trẻ có thể có Q cao hơn (kỳ vọng tăng trưởng) hoặc thấp hơn (mô hình kinh doanh chưa được kiểm chứng). Mối quan hệ phụ thuộc vào vòng đời của ngành.\n-   **Z và tuổi**: Các doanh nghiệp lâu đời thường có lợi nhuận ổn định hơn và lợi nhuận giữ lại cao hơn, góp phần làm điểm Z cao hơn, dù các doanh nghiệp rất lâu đời có thể đối mặt với năng lực cạnh tranh suy giảm.\n\n::: {#cell-fig-joint-analysis .cell execution_count=19}\n``` {.python .cell-code}\nfig, axes = plt.subplots(1, 3, figsize=(16, 5))\n\nsample = latest.dropna(subset=[\"tobin_q_simple_w\", \"altman_z_w\", \"age_founding\"])\nsample = sample.sample(min(300, len(sample)), random_state=42)\n\n# Q vs Z\naxes[0].scatter(\n    sample[\"altman_z_w\"], sample[\"tobin_q_simple_w\"],\n    c=sample[\"age_founding\"], cmap=\"viridis\", alpha=0.6,\n    s=np.log1p(sample[\"at\"]) * 3, edgecolor=\"white\", linewidth=0.3\n)\naxes[0].set_xlabel(\"Altman Z-Score\")\naxes[0].set_ylabel(\"Tobin's Q\")\naxes[0].set_title(\"Valuation vs. Distress Risk\")\naxes[0].axhline(y=1, color=\"gray\", linestyle=\"--\", alpha=0.5)\naxes[0].axvline(x=1.80, color=\"red\", linestyle=\":\", alpha=0.5)\naxes[0].axvline(x=2.99, color=\"green\", linestyle=\":\", alpha=0.5)\n\n# Q vs Age\naxes[1].scatter(\n    sample[\"age_founding\"], sample[\"tobin_q_simple_w\"],\n    c=sample[\"altman_z_w\"], cmap=\"RdYlGn\", alpha=0.6,\n    s=np.log1p(sample[\"at\"]) * 3, edgecolor=\"white\", linewidth=0.3\n)\naxes[1].set_xlabel(\"Founding Age (years)\")\naxes[1].set_ylabel(\"Tobin's Q\")\naxes[1].set_title(\"Valuation vs. Maturity\")\naxes[1].axhline(y=1, color=\"gray\", linestyle=\"--\", alpha=0.5)\n\n# Z vs Age\nscatter = axes[2].scatter(\n    sample[\"age_founding\"], sample[\"altman_z_w\"],\n    c=sample[\"tobin_q_simple_w\"], cmap=\"coolwarm\", alpha=0.6,\n    s=np.log1p(sample[\"at\"]) * 3, edgecolor=\"white\", linewidth=0.3\n)\naxes[2].set_xlabel(\"Founding Age (years)\")\naxes[2].set_ylabel(\"Altman Z-Score\")\naxes[2].set_title(\"Distress Risk vs. Maturity\")\naxes[2].axhline(y=1.80, color=\"red\", linestyle=\":\", alpha=0.5)\naxes[2].axhline(y=2.99, color=\"green\", linestyle=\":\", alpha=0.5)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Mối quan hệ giữa Q của Tobin, điểm Z của Altman và tuổi công ty đối với các doanh nghiệp niêm yết Việt Nam. Kích thước bong bóng phản ánh tổng tài sản; màu sắc cho biết vùng rủi ro điểm Z'' cho thị trường mới nổi.](36_valuation_files/figure-html/fig-joint-analysis-output-1.png){#fig-joint-analysis width=2374 height=727}\n:::\n:::\n\n\n## Cấu trúc tương quan\n\n::: {#cell-fig-correlation-matrix .cell execution_count=20}\n``` {.python .cell-code}\ncorr_vars = [\n    \"tobin_q_simple_w\", \"mtb_w\", \"altman_z_w\", \"altman_z_em_w\",\n    \"age_founding\", \"age_listing\",\n    \"z_x1\", \"z_x2\", \"z_x3\", \"z_x4\", \"z_x5\"\n]\ncorr_labels = [\n    \"Tobin's Q\", \"M/B Ratio\", \"Z-Score\", \"Z'' (EM)\",\n    \"Age (Found.)\", \"Age (List.)\",\n    \"EBIT/TA\", \"Sales/TA\", \"ME/TL\", \"WC/TA\", \"RE/TA\"\n]\n\ncorr_matrix = df_clean[corr_vars].corr()\ncorr_matrix.index = corr_labels\ncorr_matrix.columns = corr_labels\n\nfig, ax = plt.subplots(figsize=(12, 10))\n\nmask = np.triu(np.ones_like(corr_matrix, dtype=bool), k=1)\ncmap = sns.diverging_palette(250, 15, s=75, l=40, n=9, center=\"light\", as_cmap=True)\n\nsns.heatmap(\n    corr_matrix, mask=mask, cmap=cmap, center=0,\n    annot=True, fmt=\".2f\", square=True,\n    linewidths=0.5, cbar_kws={\"shrink\": 0.8},\n    ax=ax, vmin=-1, vmax=1,\n    annot_kws={\"size\": 9}\n)\nax.set_title(\"Correlation Matrix of Key Financial Measures\", fontsize=14, pad=20)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Ma trận tương quan của các thước đo chính về định giá, kiệt quệ và mức độ trưởng thành đối với các doanh nghiệp niêm yết Việt Nam.](36_valuation_files/figure-html/fig-correlation-matrix-output-1.png){#fig-correlation-matrix width=1660 height=1515}\n:::\n:::\n\n\n## Phân tích hồi quy dữ liệu chéo\n\nChúng ta ước lượng một mô hình hồi quy dữ liệu chéo đơn giản để xem xét các yếu tố quyết định Q của Tobin trên thị trường Việt Nam:\n\n$$\nQ_{i,t} = \\alpha + \\beta_1 \\ln(\\text{Age}_{i}) + \\beta_2 Z''_{i,t} + \\beta_3 \\text{SOE}_{i} + \\beta_4 \\ln(\\text{TA}_{i,t}) + \\varepsilon_{i,t}\n$$ {#eq-regression-q}\n\n::: {#regression-analysis .cell execution_count=21}\n``` {.python .cell-code code-summary=\"Cross-sectional regression of Tobin's Q\"}\nfrom numpy.linalg import lstsq\n\n# Prepare regression data\nreg_data = latest.dropna(\n    subset=[\"tobin_q_simple_w\", \"ln_age_founding\", \"altman_z_em_w\", \"at\"]\n).copy()\n\nreg_data[\"ln_at\"] = np.log(reg_data[\"at\"])\nreg_data[\"soe_dummy\"] = (reg_data[\"state_ownership_pct\"] > 30).astype(int)\nreg_data[\"constant\"] = 1.0\n\n# OLS estimation\ny = reg_data[\"tobin_q_simple_w\"].values\nX = reg_data[[\"constant\", \"ln_age_founding\", \"altman_z_em_w\",\n              \"soe_dummy\", \"ln_at\"]].values\n\nbetas, residuals, rank, sv = lstsq(X, y, rcond=None)\ny_hat = X @ betas\nresid = y - y_hat\nn, k = X.shape\n\n# Standard errors (heteroskedasticity-robust would be better)\nsigma2 = np.sum(resid**2) / (n - k)\nvar_beta = sigma2 * np.linalg.inv(X.T @ X)\nse = np.sqrt(np.diag(var_beta))\nt_stats = betas / se\nr_squared = 1 - np.sum(resid**2) / np.sum((y - y.mean())**2)\nadj_r2 = 1 - (1 - r_squared) * (n - 1) / (n - k - 1)\n\n# Display results\nvar_names = [\"Constant\", \"ln(Age)\", \"Z''-Score (EM)\", \"SOE Dummy\", \"ln(Total Assets)\"]\nprint(\"=\" * 65)\nprint(\"  Cross-Sectional Regression: Determinants of Tobin's Q\")\nprint(f\"  Dependent Variable: Tobin's Q (Simple, Winsorized)\")\nprint(f\"  Sample: {n} firms ({latest_year})\")\nprint(\"=\" * 65)\nprint(f\"  {'Variable':<22} {'Coef':>10} {'Std.Err':>10} {'t-stat':>10}\")\nprint(\"-\" * 65)\nfor name, b, s, t in zip(var_names, betas, se, t_stats):\n    sig = \"***\" if abs(t) > 2.576 else \"**\" if abs(t) > 1.96 else \"*\" if abs(t) > 1.645 else \"\"\n    print(f\"  {name:<22} {b:>10.4f} {s:>10.4f} {t:>8.2f} {sig}\")\nprint(\"-\" * 65)\nprint(f\"  R-squared: {r_squared:.4f}\")\nprint(f\"  Adjusted R-squared: {adj_r2:.4f}\")\nprint(f\"  Observations: {n}\")\nprint(\"=\" * 65)\nprint(\"  Significance: *** p<0.01, ** p<0.05, * p<0.10\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n=================================================================\n  Cross-Sectional Regression: Determinants of Tobin's Q\n  Dependent Variable: Tobin's Q (Simple, Winsorized)\n  Sample: 232 firms (2024)\n=================================================================\n  Variable                     Coef    Std.Err     t-stat\n-----------------------------------------------------------------\n  Constant                   0.9686     0.1959     4.94 ***\n  ln(Age)                   -0.0064     0.0365    -0.18 \n  Z''-Score (EM)             0.0067     0.0050     1.34 \n  SOE Dummy                  0.0327     0.0315     1.04 \n  ln(Total Assets)           0.0018     0.0096     0.19 \n-----------------------------------------------------------------\n  R-squared: 0.0126\n  Adjusted R-squared: -0.0092\n  Observations: 232\n=================================================================\n  Significance: *** p<0.01, ** p<0.05, * p<0.10\n```\n:::\n:::\n\n\n# Quy trình hoàn chỉnh {#sec-valuation-pipeline}\n\n## Tổng hợp tất cả\n\nỞ đây chúng tôi cung cấp một hàm gọn gàng duy nhất nhận dữ liệu tài chính thô từ DataCore.vn và tạo ra bộ dữ liệu hoàn chỉnh với cả ba thước đo đã được tính.\n\n::: {#complete-pipeline .cell execution_count=22}\n``` {.python .cell-code code-summary=\"Complete pipeline for computing Tobin's Q, Z-Score, and Company Age\"}\ndef compute_valuation_distress_age(df, firm_profiles=None):\n    \"\"\"\n    Complete pipeline to compute Tobin's Q, Altman Z-Score variants,\n    and Company Age for Vietnamese listed firms.\n\n    Parameters\n    ----------\n    df : pd.DataFrame\n        Panel of firm-year financial data with columns:\n        at, seq, lt, lct, tlb, sale, ebit, ni, re_var, act,\n        ppent, invt, txdb, itcb, pstk, me, prcc, csho, year, ticker\n    firm_profiles : pd.DataFrame, optional\n        Company profiles with founding_year, listing_year\n\n    Returns\n    -------\n    pd.DataFrame\n        Input data augmented with computed measures\n    \"\"\"\n    result = df.copy()\n\n    # === Data Quality Filters ===\n    result = result[result[\"at\"] > 0]\n    result = result[result[\"seq\"] > 0]\n\n    # === Book Value of Equity (Daniel & Titman 1997) ===\n    result[\"pref\"] = result[\"pstk\"].fillna(0)\n    result[\"be\"] = (\n        result[\"seq\"]\n        + result[\"txdb\"].fillna(0)\n        + result[\"itcb\"].fillna(0)\n        - result[\"pref\"]\n    )\n\n    # === Market Value of Equity ===\n    if \"me\" not in result.columns or result[\"me\"].isna().all():\n        result[\"me\"] = result[\"prcc\"] * result[\"csho\"]\n\n    # === Tobin's Q Variants ===\n    # Simple Q (Gompers et al. 2003)\n    result[\"tobin_q\"] = (result[\"at\"] + result[\"me\"] - result[\"be\"]) / result[\"at\"]\n\n    # Chung-Pruitt Q\n    debt_cp = (\n        result[\"lct\"].fillna(0) - result[\"act\"].fillna(0)\n        + result[\"invt\"].fillna(0) + result[\"lt\"].fillna(0)\n    )\n    result[\"tobin_q_cp\"] = (\n        (result[\"me\"] + result[\"pstk\"].fillna(0) + debt_cp) / result[\"at\"]\n    )\n\n    # Market-to-Book\n    result[\"mtb\"] = np.where(result[\"be\"] > 0, result[\"me\"] / result[\"be\"], np.nan)\n\n    # === Altman Z-Score Variants ===\n    result[\"wc\"] = result[\"act\"].fillna(0) - result[\"lct\"].fillna(0)\n\n    x1 = result[\"ebit\"] / result[\"at\"]\n    x2 = result[\"sale\"] / result[\"at\"]\n    x3_market = np.where(result[\"tlb\"] > 0, result[\"me\"] / result[\"tlb\"], np.nan)\n    x3_book = np.where(result[\"tlb\"] > 0, result[\"be\"] / result[\"tlb\"], np.nan)\n    x4 = result[\"wc\"] / result[\"at\"]\n    x5 = result[\"re_var\"].fillna(0) / result[\"at\"]\n\n    # Original Z\n    result[\"altman_z\"] = 3.3 * x1 + 0.999 * x2 + 0.6 * x3_market + 1.2 * x4 + 1.4 * x5\n\n    # Z' (private firms)\n    result[\"altman_z_prime\"] = (\n        0.717 * x4 + 0.847 * x5 + 3.107 * x1 + 0.420 * x3_book + 0.998 * x2\n    )\n\n    # Z'' (emerging markets)\n    result[\"altman_z_em\"] = (\n        3.25 + 6.56 * x4 + 3.26 * x5 + 6.72 * x1 + 1.05 * x3_book\n    )\n\n    # Risk zones\n    result[\"z_zone\"] = pd.cut(\n        result[\"altman_z\"],\n        bins=[-np.inf, 1.80, 2.70, 2.99, np.inf],\n        labels=[\"High Distress\", \"Distress\", \"Grey Zone\", \"Safe\"]\n    )\n    result[\"z_em_zone\"] = pd.cut(\n        result[\"altman_z_em\"],\n        bins=[-np.inf, 1.10, 2.60, np.inf],\n        labels=[\"Distress\", \"Grey Zone\", \"Safe\"]\n    )\n\n    # === Company Age ===\n    if firm_profiles is not None:\n        result = result.merge(\n            firm_profiles[[\"ticker\", \"founding_year\", \"listing_year\"]],\n            on=\"ticker\", how=\"left\", suffixes=(\"\", \"_profile\")\n        )\n        result[\"age_founding\"] = result[\"year\"] - result[\"founding_year\"]\n        result[\"age_listing\"] = (result[\"year\"] - result[\"listing_year\"]).clip(lower=0)\n\n    first_year = result.groupby(\"ticker\")[\"year\"].transform(\"min\")\n    result[\"age_data\"] = result[\"year\"] - first_year\n\n    # === Winsorize ===\n    for var in [\"tobin_q\", \"tobin_q_cp\", \"mtb\", \"altman_z\", \"altman_z_prime\", \"altman_z_em\"]:\n        if var in result.columns:\n            result[f\"{var}_w\"] = winsorize(result[var])\n\n    return result\n\n# Demonstrate the pipeline\nfinal_df = compute_valuation_distress_age(df, firm_profiles)\nprint(f\"Final dataset: {final_df.shape[0]:,} observations, {final_df.shape[1]} variables\")\nprint(f\"Firms: {final_df['ticker'].nunique()}\")\nprint(f\"\\nKey variables computed:\")\nfor var in [\"tobin_q\", \"tobin_q_cp\", \"mtb\", \"altman_z\", \"altman_z_prime\",\n            \"altman_z_em\", \"age_founding\", \"age_listing\", \"age_data\"]:\n    if var in final_df.columns:\n        non_null = final_df[var].notna().sum()\n        print(f\"  {var}: {non_null:,} non-null values\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFinal dataset: 3,484 observations, 48 variables\nFirms: 297\n\nKey variables computed:\n  tobin_q: 3,484 non-null values\n  tobin_q_cp: 3,484 non-null values\n  mtb: 3,484 non-null values\n  altman_z: 3,484 non-null values\n  altman_z_prime: 3,484 non-null values\n  altman_z_em: 3,484 non-null values\n  age_founding: 3,484 non-null values\n  age_listing: 3,484 non-null values\n  age_data: 3,484 non-null values\n```\n:::\n:::\n\n\n## Xuất kết quả\n\n::: {#export-results .cell execution_count=23}\n``` {.python .cell-code code-summary=\"Export computed measures to CSV\"}\n# Select key output variables\noutput_vars = [\n    \"ticker\", \"year\", \"datadate\", \"exchange\", \"industry\",\n    \"at\", \"be\", \"me\", \"tobin_q\", \"tobin_q_w\", \"mtb\", \"mtb_w\",\n    \"altman_z\", \"altman_z_w\", \"altman_z_em\", \"altman_z_em_w\",\n    \"z_zone\", \"z_em_zone\",\n    \"age_founding\", \"age_listing\", \"age_data\",\n    \"state_ownership_pct\"\n]\n\nexport_cols = [v for v in output_vars if v in final_df.columns]\nexport_df = final_df[export_cols].copy()\n\n# export_df.to_csv(\"vn_valuation_distress_age.csv\", index=False)\n# export_df.to_parquet(\"vn_valuation_distress_age.parquet\", index=False)\n\nprint(f\"Export dataset: {export_df.shape[0]:,} rows × {export_df.shape[1]} columns\")\nprint(f\"\\nSample output (first 5 rows):\")\ndisplay_cols = [\"ticker\", \"year\", \"tobin_q\", \"altman_z\", \"altman_z_em\",\n                \"z_zone\", \"age_founding\"]\ndisplay_cols = [c for c in display_cols if c in export_df.columns]\nprint(export_df[display_cols].head().to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nExport dataset: 3,484 rows × 22 columns\n\nSample output (first 5 rows):\nticker  year  tobin_q  altman_z  altman_z_em z_zone  age_founding\nVN0001  2017 0.905928  3.345941     5.605169   Safe             4\nVN0001  2018 1.270114  5.324082     9.228846   Safe             5\nVN0001  2019 1.866493  5.478529     6.264178   Safe             6\nVN0001  2020 1.016979  5.612289    10.445449   Safe             7\nVN0001  2021 0.805818  4.220869     7.588273   Safe             8\n```\n:::\n:::\n\n\n# Các chủ đề đặc biệt cho thị trường Việt Nam {#sec-valuation-special-topics}\n\n## Sở hữu nhà nước và định giá\n\nSở hữu nhà nước là đặc điểm nổi bật của bức tranh doanh nghiệp Việt Nam. Chúng ta xem xét sở hữu nhà nước ảnh hưởng thế nào đến cả Q của Tobin lẫn rủi ro kiệt quệ tài chính.\n\n::: {#cell-fig-soe-analysis .cell execution_count=24}\n``` {.python .cell-code}\nfig, axes = plt.subplots(1, 2, figsize=(14, 6))\n\nlatest = final_df[final_df[\"year\"] == latest_year].dropna(\n    subset=[\"tobin_q_w\", \"altman_z_em_w\", \"state_ownership_pct\"]\n)\n\n# Q vs State Ownership\naxes[0].scatter(\n    latest[\"state_ownership_pct\"], latest[\"tobin_q_w\"],\n    alpha=0.4, s=20, color=colors[\"primary\"], edgecolor=\"white\"\n)\n\n# Binned means\nbins = pd.cut(latest[\"state_ownership_pct\"], bins=10)\nbinned = latest.groupby(bins)[\"tobin_q_w\"].mean()\nbin_centers = [(b.left + b.right) / 2 for b in binned.index]\naxes[0].plot(bin_centers, binned.values, color=colors[\"quaternary\"],\n             linewidth=3, label=\"Binned Mean\")\n\naxes[0].set_xlabel(\"State Ownership (%)\")\naxes[0].set_ylabel(\"Tobin's Q\")\naxes[0].set_title(\"State Ownership and Firm Valuation\")\naxes[0].axhline(y=1, color=\"gray\", linestyle=\"--\", alpha=0.5)\naxes[0].legend()\n\n# Z''-Score by SOE quartile\nlatest[\"soe_quartile\"] = pd.qcut(\n    latest[\"state_ownership_pct\"],\n    q=4, labels=[\"Q1 (Low)\", \"Q2\", \"Q3\", \"Q4 (High)\"],\n    duplicates=\"drop\"\n)\n\nsoe_groups = latest.groupby(\"soe_quartile\")[\"altman_z_em_w\"]\nbox_data = [group.values for name, group in soe_groups]\nbp = axes[1].boxplot(\n    box_data,\n    labels=[name for name, _ in soe_groups],\n    patch_artist=True,\n    medianprops=dict(color=\"black\", linewidth=2)\n)\n\ngradient_colors = plt.cm.Blues(np.linspace(0.3, 0.8, len(bp[\"boxes\"])))\nfor patch, color in zip(bp[\"boxes\"], gradient_colors):\n    patch.set_facecolor(color)\n\naxes[1].axhline(y=2.60, color=\"green\", linestyle=\":\", alpha=0.5, label=\"Safe threshold\")\naxes[1].axhline(y=1.10, color=\"red\", linestyle=\":\", alpha=0.5, label=\"Distress threshold\")\naxes[1].set_xlabel(\"State Ownership Quartile\")\naxes[1].set_ylabel(\"Z''-Score (Emerging Market)\")\naxes[1].set_title(\"Financial Health by State Ownership\")\naxes[1].legend(fontsize=9)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Mối quan hệ giữa tỷ lệ sở hữu nhà nước và các thước đo định giá/kiệt quệ của doanh nghiệp. Biểu đồ bên trái thể hiện Q của Tobin theo sở hữu nhà nước, với đường làm trơn LOWESS. Biểu đồ bên phải thể hiện điểm Z'' theo tứ phân vị sở hữu nhà nước.](36_valuation_files/figure-html/fig-soe-analysis-output-1.png){#fig-soe-analysis width=2075 height=877}\n:::\n:::\n\n\n## Phân tích theo sàn giao dịch\n\n::: {#tbl-exchange-summary .cell tbl-cap='Thống kê mô tả theo sàn giao dịch đối với các doanh nghiệp niêm yết Việt Nam (năm gần nhất)' execution_count=25}\n``` {.python .cell-code}\nexchange_summary = (\n    latest\n    .groupby(\"exchange\")\n    .agg(\n        n_firms=(\"ticker\", \"nunique\"),\n        median_q=(\"tobin_q_w\", \"median\"),\n        mean_q=(\"tobin_q_w\", \"mean\"),\n        median_z=(\"altman_z_w\", \"median\"),\n        mean_z_em=(\"altman_z_em_w\", \"mean\"),\n        pct_distress_z=(\"z_zone\", lambda x: (x == \"High Distress\").mean() * 100),\n        pct_distress_em=(\"z_em_zone\", lambda x: (x == \"Distress\").mean() * 100),\n        median_age=(\"age_founding\", \"median\"),\n        median_soe=(\"state_ownership_pct\", \"median\"),\n    )\n    .round(2)\n)\n\nexchange_summary.columns = [\n    \"N Firms\", \"Median Q\", \"Mean Q\", \"Median Z\", \"Mean Z'' (EM)\",\n    \"% Distress (Z)\", \"% Distress (Z'')\", \"Median Age\", \"Median SOE %\"\n]\n\nexchange_summary.style.set_properties(**{\n    \"text-align\": \"center\",\n    \"font-size\": \"10pt\"\n}).set_table_styles([\n    {\"selector\": \"th\", \"props\": [\n        (\"background-color\", \"#1f77b4\"),\n        (\"color\", \"white\"),\n        (\"text-align\", \"center\"),\n        (\"padding\", \"8px\")\n    ]},\n]).format({\n    \"Median Q\": \"{:.2f}\", \"Mean Q\": \"{:.2f}\",\n    \"Median Z\": \"{:.2f}\", \"Mean Z'' (EM)\": \"{:.2f}\",\n    \"% Distress (Z)\": \"{:.1f}%\", \"% Distress (Z'')\": \"{:.1f}%\",\n    \"Median Age\": \"{:.0f}\", \"Median SOE %\": \"{:.1f}%\"\n})\n```\n\n::: {.cell-output .cell-output-display execution_count=25}\n```{=html}\n<style type=\"text/css\">\n#T_c4d9f th {\n  background-color: #1f77b4;\n  color: white;\n  text-align: center;\n  padding: 8px;\n}\n#T_c4d9f_row0_col0, #T_c4d9f_row0_col1, #T_c4d9f_row0_col2, #T_c4d9f_row0_col3, #T_c4d9f_row0_col4, #T_c4d9f_row0_col5, #T_c4d9f_row0_col6, #T_c4d9f_row0_col7, #T_c4d9f_row0_col8, #T_c4d9f_row1_col0, #T_c4d9f_row1_col1, #T_c4d9f_row1_col2, #T_c4d9f_row1_col3, #T_c4d9f_row1_col4, #T_c4d9f_row1_col5, #T_c4d9f_row1_col6, #T_c4d9f_row1_col7, #T_c4d9f_row1_col8, #T_c4d9f_row2_col0, #T_c4d9f_row2_col1, #T_c4d9f_row2_col2, #T_c4d9f_row2_col3, #T_c4d9f_row2_col4, #T_c4d9f_row2_col5, #T_c4d9f_row2_col6, #T_c4d9f_row2_col7, #T_c4d9f_row2_col8 {\n  text-align: center;\n  font-size: 10pt;\n}\n</style>\n<table id=\"T_c4d9f\">\n  <thead>\n    <tr>\n      <th class=\"blank level0\" >&nbsp;</th>\n      <th id=\"T_c4d9f_level0_col0\" class=\"col_heading level0 col0\" >N Firms</th>\n      <th id=\"T_c4d9f_level0_col1\" class=\"col_heading level0 col1\" >Median Q</th>\n      <th id=\"T_c4d9f_level0_col2\" class=\"col_heading level0 col2\" >Mean Q</th>\n      <th id=\"T_c4d9f_level0_col3\" class=\"col_heading level0 col3\" >Median Z</th>\n      <th id=\"T_c4d9f_level0_col4\" class=\"col_heading level0 col4\" >Mean Z'' (EM)</th>\n      <th id=\"T_c4d9f_level0_col5\" class=\"col_heading level0 col5\" >% Distress (Z)</th>\n      <th id=\"T_c4d9f_level0_col6\" class=\"col_heading level0 col6\" >% Distress (Z'')</th>\n      <th id=\"T_c4d9f_level0_col7\" class=\"col_heading level0 col7\" >Median Age</th>\n      <th id=\"T_c4d9f_level0_col8\" class=\"col_heading level0 col8\" >Median SOE %</th>\n    </tr>\n    <tr>\n      <th class=\"index_name level0\" >exchange</th>\n      <th class=\"blank col0\" >&nbsp;</th>\n      <th class=\"blank col1\" >&nbsp;</th>\n      <th class=\"blank col2\" >&nbsp;</th>\n      <th class=\"blank col3\" >&nbsp;</th>\n      <th class=\"blank col4\" >&nbsp;</th>\n      <th class=\"blank col5\" >&nbsp;</th>\n      <th class=\"blank col6\" >&nbsp;</th>\n      <th class=\"blank col7\" >&nbsp;</th>\n      <th class=\"blank col8\" >&nbsp;</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th id=\"T_c4d9f_level0_row0\" class=\"row_heading level0 row0\" >HNX</th>\n      <td id=\"T_c4d9f_row0_col0\" class=\"data row0 col0\" >77</td>\n      <td id=\"T_c4d9f_row0_col1\" class=\"data row0 col1\" >0.99</td>\n      <td id=\"T_c4d9f_row0_col2\" class=\"data row0 col2\" >1.02</td>\n      <td id=\"T_c4d9f_row0_col3\" class=\"data row0 col3\" >2.07</td>\n      <td id=\"T_c4d9f_row0_col4\" class=\"data row0 col4\" >7.25</td>\n      <td id=\"T_c4d9f_row0_col5\" class=\"data row0 col5\" >32.5%</td>\n      <td id=\"T_c4d9f_row0_col6\" class=\"data row0 col6\" >0.0%</td>\n      <td id=\"T_c4d9f_row0_col7\" class=\"data row0 col7\" >33</td>\n      <td id=\"T_c4d9f_row0_col8\" class=\"data row0 col8\" >22.1%</td>\n    </tr>\n    <tr>\n      <th id=\"T_c4d9f_level0_row1\" class=\"row_heading level0 row1\" >HOSE</th>\n      <td id=\"T_c4d9f_row1_col0\" class=\"data row1 col0\" >113</td>\n      <td id=\"T_c4d9f_row1_col1\" class=\"data row1 col1\" >1.00</td>\n      <td id=\"T_c4d9f_row1_col2\" class=\"data row1 col2\" >1.04</td>\n      <td id=\"T_c4d9f_row1_col3\" class=\"data row1 col3\" >2.06</td>\n      <td id=\"T_c4d9f_row1_col4\" class=\"data row1 col4\" >7.24</td>\n      <td id=\"T_c4d9f_row1_col5\" class=\"data row1 col5\" >40.7%</td>\n      <td id=\"T_c4d9f_row1_col6\" class=\"data row1 col6\" >0.0%</td>\n      <td id=\"T_c4d9f_row1_col7\" class=\"data row1 col7\" >29</td>\n      <td id=\"T_c4d9f_row1_col8\" class=\"data row1 col8\" >26.8%</td>\n    </tr>\n    <tr>\n      <th id=\"T_c4d9f_level0_row2\" class=\"row_heading level0 row2\" >UPCoM</th>\n      <td id=\"T_c4d9f_row2_col0\" class=\"data row2 col0\" >42</td>\n      <td id=\"T_c4d9f_row2_col1\" class=\"data row2 col1\" >0.98</td>\n      <td id=\"T_c4d9f_row2_col2\" class=\"data row2 col2\" >1.05</td>\n      <td id=\"T_c4d9f_row2_col3\" class=\"data row2 col3\" >2.13</td>\n      <td id=\"T_c4d9f_row2_col4\" class=\"data row2 col4\" >7.80</td>\n      <td id=\"T_c4d9f_row2_col5\" class=\"data row2 col5\" >30.9%</td>\n      <td id=\"T_c4d9f_row2_col6\" class=\"data row2 col6\" >0.0%</td>\n      <td id=\"T_c4d9f_row2_col7\" class=\"data row2 col7\" >26</td>\n      <td id=\"T_c4d9f_row2_col8\" class=\"data row2 col8\" >27.6%</td>\n    </tr>\n  </tbody>\n</table>\n```\n:::\n:::\n\n\n## Bản đồ nhiệt theo ngành: Định giá và kiệt quệ\n\n::: {#cell-fig-sector-heatmap .cell execution_count=26}\n``` {.python .cell-code}\nfig, axes = plt.subplots(1, 2, figsize=(16, 8))\n\n# Tobin's Q heatmap\nq_pivot = (\n    final_df\n    .groupby([\"industry\", \"year\"])[\"tobin_q_w\"]\n    .median()\n    .unstack(fill_value=np.nan)\n)\n\nsns.heatmap(\n    q_pivot, cmap=\"RdYlGn\", center=1, ax=axes[0],\n    cbar_kws={\"label\": \"Median Q\", \"shrink\": 0.8},\n    linewidths=0.5, linecolor=\"white\",\n    xticklabels=2\n)\naxes[0].set_title(\"Tobin's Q by Industry and Year\")\naxes[0].set_xlabel(\"Year\")\naxes[0].set_ylabel(\"\")\n\n# Z''-Score heatmap\nz_pivot = (\n    final_df\n    .groupby([\"industry\", \"year\"])[\"altman_z_em_w\"]\n    .median()\n    .unstack(fill_value=np.nan)\n)\n\nsns.heatmap(\n    z_pivot, cmap=\"RdYlGn\", center=2.6, ax=axes[1],\n    cbar_kws={\"label\": \"Median Z''\", \"shrink\": 0.8},\n    linewidths=0.5, linecolor=\"white\",\n    xticklabels=2\n)\naxes[1].set_title(\"Z''-Score (EM) by Industry and Year\")\naxes[1].set_xlabel(\"Year\")\naxes[1].set_ylabel(\"\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Q của Tobin và điểm Z'' trung vị theo ngành và năm đối với các doanh nghiệp niêm yết Việt Nam. Màu ấm hơn biểu thị giá trị cao hơn.](36_valuation_files/figure-html/fig-sector-heatmap-output-1.png){#fig-sector-heatmap width=2360 height=1177}\n:::\n:::\n\n\n## Xử lý các doanh nghiệp bị hủy niêm yết: Thiên kiến sống sót\n\nMột vấn đề then chốt khi đo lường kiệt quệ tài chính là thiên kiến sống sót. Nếu chỉ phân tích các doanh nghiệp hiện đang niêm yết, chúng ta bỏ sót chính những doanh nghiệp mà điểm Z được thiết kế để nhận diện, tức những doanh nghiệp đã phá sản hoặc bị hủy niêm yết.\n\n::: {#survivorship-bias .cell execution_count=27}\n``` {.python .cell-code code-summary=\"Analysis of delisted firms and survivorship bias\"}\n# Simulate delisting data (replace with DataCore.vn delisting records)\nnp.random.seed(123)\nn_delisted = 50\ndelisted_firms = pd.DataFrame({\n    \"ticker\": [f\"VN{str(i).zfill(4)}\" for i in range(n_firms + 1, n_firms + n_delisted + 1)],\n    \"delist_year\": np.random.randint(2010, 2024, n_delisted),\n    \"delist_reason\": np.random.choice(\n        [\"Bankruptcy/Liquidation\", \"Merger/Acquisition\", \"Voluntary Delisting\",\n         \"Regulatory Non-compliance\", \"Below Minimum Requirements\"],\n        n_delisted,\n        p=[0.15, 0.25, 0.20, 0.20, 0.20]\n    )\n})\n\n# Summary of delisting reasons\nprint(\"Delisting Reasons Summary\")\nprint(\"=\" * 50)\nreason_counts = delisted_firms[\"delist_reason\"].value_counts()\nfor reason, count in reason_counts.items():\n    print(f\"  {reason}: {count} ({count/n_delisted*100:.0f}%)\")\nprint(f\"\\nTotal delisted: {n_delisted}\")\nprint(f\"Currently listed: {final_df['ticker'].nunique()}\")\nprint(f\"\\nSurvivorship rate: \"\n      f\"{final_df['ticker'].nunique()/(final_df['ticker'].nunique()+n_delisted)*100:.1f}%\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDelisting Reasons Summary\n==================================================\n  Merger/Acquisition: 16 (32%)\n  Voluntary Delisting: 14 (28%)\n  Regulatory Non-compliance: 9 (18%)\n  Below Minimum Requirements: 7 (14%)\n  Bankruptcy/Liquidation: 4 (8%)\n\nTotal delisted: 50\nCurrently listed: 297\n\nSurvivorship rate: 85.6%\n```\n:::\n:::\n\n\n# Kiểm tra độ vững và mở rộng {#sec-valuation-robustness}\n\n## Các cách xác định Q của Tobin thay thế\n\n::: {#cell-fig-q-variants-comparison .cell execution_count=28}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(7, 7))\n\nsample = latest.dropna(subset=[\"tobin_q_w\", \"tobin_q_cp\"]).copy()\nsample[\"tobin_q_cp_w\"] = winsorize(sample[\"tobin_q_cp\"])\n\nax.scatter(\n    sample[\"tobin_q_w\"], sample[\"tobin_q_cp_w\"],\n    alpha=0.4, s=15, color=colors[\"primary\"], edgecolor=\"white\"\n)\n\n# 45-degree line\nlims = [\n    min(ax.get_xlim()[0], ax.get_ylim()[0]),\n    max(ax.get_xlim()[1], ax.get_ylim()[1])\n]\nax.plot(lims, lims, \"k--\", alpha=0.3)\n\ncorr = sample[\"tobin_q_w\"].corr(sample[\"tobin_q_cp_w\"])\nax.text(0.05, 0.95, f\"Correlation: {corr:.3f}\",\n        transform=ax.transAxes, fontsize=12,\n        verticalalignment=\"top\",\n        bbox=dict(boxstyle=\"round\", facecolor=\"wheat\", alpha=0.5))\n\nax.set_xlabel(\"Simple Q (Gompers et al.)\")\nax.set_ylabel(\"Chung-Pruitt Q\")\nax.set_title(\"Comparison of Tobin's Q Variants\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![So sánh các biến thể của Q của Tobin: Q đơn giản (Gompers et al. 2003) so với xấp xỉ Chung-Pruitt. Tương quan cao ủng hộ việc sử dụng thước đo đơn giản hơn.](36_valuation_files/figure-html/fig-q-variants-comparison-output-1.png){#fig-q-variants-comparison width=1026 height=1027}\n:::\n:::\n\n\n## Các thước đo điều chỉnh theo ngành\n\nQ của Tobin và điểm Z thô có thể phản ánh đặc điểm ngành hơn là thuộc tính riêng của doanh nghiệp. Chúng ta tính các phiên bản điều chỉnh theo ngành:\n\n$$\nQ^{\\text{adj}}_{i,t} = Q_{i,t} - \\overline{Q}_{j(i),t}\n$$ {#eq-industry-adj-q}\n\ntrong đó $\\overline{Q}_{j(i),t}$ là Q của Tobin trung vị của ngành $j$ mà doanh nghiệp $i$ thuộc về trong năm $t$.\n\n::: {#industry-adjusted .cell execution_count=29}\n``` {.python .cell-code code-summary=\"Industry-adjusted measures\"}\ndef industry_adjust(df, var, group_var=\"industry\"):\n    \"\"\"Compute industry-adjusted measure (deviation from industry median).\"\"\"\n    industry_median = df.groupby([\"year\", group_var])[var].transform(\"median\")\n    return df[var] - industry_median\n\nfinal_df[\"tobin_q_adj\"] = industry_adjust(final_df, \"tobin_q_w\")\nfinal_df[\"altman_z_em_adj\"] = industry_adjust(final_df, \"altman_z_em_w\")\n\nlatest_adj = final_df[final_df[\"year\"] == latest_year]\n\nprint(\"Industry-Adjusted Measures (Latest Year)\")\nprint(f\"  Tobin's Q (adjusted): mean={latest_adj['tobin_q_adj'].mean():.4f}, \"\n      f\"std={latest_adj['tobin_q_adj'].std():.3f}\")\nprint(f\"  Z''-Score (adjusted): mean={latest_adj['altman_z_em_adj'].mean():.4f}, \"\n      f\"std={latest_adj['altman_z_em_adj'].std():.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nIndustry-Adjusted Measures (Latest Year)\n  Tobin's Q (adjusted): mean=0.0352, std=0.226\n  Z''-Score (adjusted): mean=0.4840, std=3.030\n```\n:::\n:::\n\n\n## Hồi quy dữ liệu bảng với hiệu ứng cố định\n\nĐể phân tích chặt chẽ hơn, chúng ta ước lượng một mô hình dữ liệu bảng với hiệu ứng cố định theo doanh nghiệp và theo năm:\n\n$$\nQ_{i,t} = \\alpha_i + \\gamma_t + \\beta_1 Z''_{i,t} + \\beta_2 \\ln(\\text{Age}_{i,t}) + \\beta_3 \\text{Size}_{i,t} + \\varepsilon_{i,t}\n$$ {#eq-panel-regression}\n\n::: {#panel-regression .cell execution_count=30}\n``` {.python .cell-code code-summary=\"Panel regression with year and industry fixed effects\"}\n# Simplified within-estimator (year and industry demeaning)\npanel = final_df.dropna(\n    subset=[\"tobin_q_w\", \"altman_z_em_w\", \"age_founding\", \"at\"]\n).copy()\n\npanel[\"ln_at\"] = np.log(panel[\"at\"])\npanel[\"ln_age\"] = np.log1p(panel[\"age_founding\"])\n\n# Demean by year-industry (proxy for fixed effects)\nfe_vars = [\"tobin_q_w\", \"altman_z_em_w\", \"ln_age\", \"ln_at\"]\nfor var in fe_vars:\n    group_mean = panel.groupby([\"year\", \"industry\"])[var].transform(\"mean\")\n    panel[f\"{var}_dm\"] = panel[var] - group_mean\n\n# OLS on demeaned data\ny = panel[\"tobin_q_w_dm\"].values\nX = np.column_stack([\n    np.ones(len(panel)),\n    panel[\"altman_z_em_w_dm\"].values,\n    panel[\"ln_age_dm\"].values,\n    panel[\"ln_at_dm\"].values,\n])\n\nbetas, _, _, _ = lstsq(X, y, rcond=None)\ny_hat = X @ betas\nresid = y - y_hat\nn, k = X.shape\n\nsigma2 = np.sum(resid**2) / (n - k)\nvar_beta = sigma2 * np.linalg.inv(X.T @ X)\nse = np.sqrt(np.diag(var_beta))\nt_stats = betas / se\nr_squared = 1 - np.sum(resid**2) / np.sum((y - y.mean())**2)\n\nvar_names = [\"Constant\", \"Z''-Score (EM)\", \"ln(Age)\", \"ln(Total Assets)\"]\nprint(\"=\" * 65)\nprint(\"  Panel Regression: Tobin's Q with Year-Industry FE\")\nprint(f\"  (Within estimator via year×industry demeaning)\")\nprint(\"=\" * 65)\nprint(f\"  {'Variable':<22} {'Coef':>10} {'Std.Err':>10} {'t-stat':>10}\")\nprint(\"-\" * 65)\nfor name, b, s, t in zip(var_names, betas, se, t_stats):\n    sig = \"***\" if abs(t) > 2.576 else \"**\" if abs(t) > 1.96 else \"*\" if abs(t) > 1.645 else \"\"\n    print(f\"  {name:<22} {b:>10.4f} {s:>10.4f} {t:>8.2f} {sig}\")\nprint(\"-\" * 65)\nprint(f\"  R-squared (within): {r_squared:.4f}\")\nprint(f\"  Observations: {n:,}\")\nprint(\"=\" * 65)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n=================================================================\n  Panel Regression: Tobin's Q with Year-Industry FE\n  (Within estimator via year×industry demeaning)\n=================================================================\n  Variable                     Coef    Std.Err     t-stat\n-----------------------------------------------------------------\n  Constant                   0.0000     0.0038     0.00 \n  Z''-Score (EM)             0.0034     0.0014     2.45 **\n  ln(Age)                   -0.0055     0.0063    -0.88 \n  ln(Total Assets)          -0.0031     0.0026    -1.16 \n-----------------------------------------------------------------\n  R-squared (within): 0.0024\n  Observations: 3,484\n=================================================================\n```\n:::\n:::\n\n\n# Giải quyết kiệt quệ: Chế độ pháp lý đằng sau điểm Z {#sec-valuation-resolution}\n\n## Điểm Z thực sự dự báo điều gì\n\nHàm phân biệt của @altman1968financial được ước lượng trên một mẫu ghép cặp gồm các doanh nghiệp đã nộp và chưa nộp đơn phá sản. Do đó, sự kiện mà nó chấm điểm là *việc bước vào một thủ tục pháp lý cụ thể*, chứ không phải cái chết về mặt kinh tế, và càng không phải mức tổn thất khi xảy ra kiệt quệ. Sự phân biệt này dễ bị bỏ qua vì các vùng diễn giải trong @tbl-zscore-zones được diễn đạt bằng ngôn ngữ xác suất thất bại, nhưng đối với bất kỳ ai định giá một quyền đòi đối với doanh nghiệp, đối tượng liên quan là\n\n$$\n\\mathbb{E}[\\text{Loss}_i] \\;=\\; \\underbrace{\\Pr(\\text{distress}_i)}_{\\text{what } Z \\text{ scores}} \\times \\underbrace{\\mathbb{E}\\!\\left[\\text{Loss}_i \\mid \\text{distress}_i\\right]}_{\\text{set by the insolvency regime}} .\n$$ {#eq-loss-decomposition}\n\nNhân tố thứ hai không phải là thuộc tính của doanh nghiệp. Nó là thuộc tính của các quy tắc quy định ai kiểm soát một doanh nghiệp kiệt quệ, chi phí tái cơ cấu là bao nhiêu, chủ nợ có thể buộc thanh lý hay không, và chủ sở hữu hiện hữu có thể giữ lại vốn chủ sở hữu hay không. Việc chuyển một hàm phân biệt được ước lượng ở một khu vực pháp lý sang nơi khác đồng nghĩa với việc chuyển theo một nhân tố thứ hai ngầm định. Việc nhân tố thứ hai thực sự thay đổi đã được ghi nhận rõ: @davydenko2008bankruptcy cho thấy các vụ vỡ nợ đối với các khoản vay tương tự ở Pháp, Đức và Anh được giải quyết khác nhau đến mức các ngân hàng điều chỉnh yêu cầu tài sản đảm bảo theo bộ luật, và @schoenherr2022when chứng minh cả về lý thuyết lẫn thực nghiệm rằng mức độ thân thiện tối ưu đối với con nợ phụ thuộc vào môi trường xung quanh chứ không phải là một hằng số phổ quát.\n\nĐối với nghiên cứu về Việt Nam, điều này quan trọng gấp đôi. Các hệ số của điểm Z'' được sử dụng trong @sec-valuation-zscore-computation được hiệu chỉnh bên ngoài Việt Nam, và phân phối kết cục mà chúng ngầm định lấy làm điều kiện được tạo ra bởi một hệ thống phá sản mà Việt Nam không có.\n\n## Thí nghiệm Subchapter V {#sec-valuation-subchapterv}\n\n@hotchkiss2026can cung cấp bằng chứng gần đây rõ ràng nhất rằng nhân tố thứ hai trong @eq-loss-decomposition là một lựa chọn chính sách chứ không phải một hằng số công nghệ, và họ làm điều đó ở phân khúc mà câu hỏi này gay gắt nhất: các doanh nghiệp nhỏ.\n\nThực tế cách điệu hóa (stylized fact) làm động lực cho bài nghiên cứu lại đảo ngược thực tế quen thuộc. Đối với các công ty đại chúng lớn của Hoa Kỳ, các vụ thanh lý theo Chapter 11 hiếm khi xảy ra và hầu hết các doanh nghiệp nộp đơn thoát ra với một phần hoặc toàn bộ hoạt động còn nguyên vẹn. Đối với doanh nghiệp nhỏ, bức tranh đảo ngược: 70% doanh nghiệp nhỏ bước vào thủ tục phá sản giai đoạn 2010-2019 nộp đơn thẳng vào thanh lý theo Chapter 7, và trong số những doanh nghiệp đã vào Chapter 11, chỉ khoảng một phần ba được xác nhận kế hoạch. Phần còn lại bị chuyển sang Chapter 7 hoặc bị tòa bác đơn. Việc bị bác đơn không phải là một cú hạ cánh mềm, vì doanh nghiệp quay lại với các chủ nợ mà không được xóa nợ và thường ngừng hoạt động [@morrison2007bankruptcy; @iverson2018get].\n\nBa ma sát giải thích khoảng cách này. Thứ nhất, các chi phí trực tiếp của Chapter 11 phần lớn là cố định, nên chúng trở nên quá nặng nề so với một cơ sở tài sản nhỏ [@bris2006costs; @dou2021dissecting]. Thứ hai, nguyên tắc ưu tiên tuyệt đối xóa sạch vốn chủ sở hữu trước phá sản, nhưng trong một doanh nghiệp nhỏ, các mối quan hệ của chủ sở hữu kiêm nhà quản lý với nhà cung cấp và khách hàng thường *chính là* giá trị hoạt động liên tục; các chủ nợ kiêm chủ sở hữu mới không thể dễ dàng thay thế những gì họ vừa tước đoạt, và các chủ nợ thương mại cùng các ngân hàng địa phương hiếm khi muốn nắm giữ vốn chủ sở hữu ngay từ đầu. Thứ ba, các chủ nợ phân tán với thứ tự ưu tiên khác nhau tạo ra các vấn đề phối hợp, và một chủ nợ có bảo đảm ưu tiên với khoản nợ nhỏ thường thích phát mại nhanh hơn một kế hoạch được thương lượng, ngay cả khi việc tiếp tục hoạt động có giá trị hơn xét trên tổng thể.\n\nĐạo luật Tái cơ cấu Doanh nghiệp Nhỏ năm 2019 (Small Business Reorganization Act of 2019) đã tạo ra Subchapter V của Chapter 11, có hiệu lực từ ngày 19 tháng 2 năm 2020, giải quyết đồng thời cả ba ma sát này đối với các con nợ có tổng nợ không phụ thuộc điều kiện và đã xác định không vượt quá \\$7.5 triệu. Mức trần để đủ điều kiện ban đầu là \\$2.725 triệu và được CARES Act nâng lên \\$7.5 triệu vào ngày 27 tháng 3 năm 2020, một tháng sau khi thủ tục này mở ra. Ba thay đổi then chốt là: một kế hoạch có thể được xác nhận bất chấp sự phản đối của chủ nợ mà không xóa bỏ vốn chủ sở hữu của chủ doanh nghiệp, với điều kiện doanh nghiệp cam kết dành thu nhập khả dụng dự kiến của mình để trả nợ trong ba đến năm năm; ủy ban chủ nợ và bản công bố thông tin không còn bắt buộc; và một người được ủy thác Subchapter V được chỉ định để hòa giải thay vì thay thế ban quản lý.\n\nChính mức trần đủ điều kiện khiến đây trở thành một thí nghiệm chứ không phải một giai thoại. @tbl-subv-estimates tổng hợp các ước lượng chính.\n\n| Kết cục | Thiết kế | Ước lượng | Mức tham chiếu |\n|:---|:---|---:|:---|\n| Kế hoạch được xác nhận | OLS, 6,431 vụ dưới \\$15m | $+18.4$ pp | tỷ lệ cơ sở $31.9\\%$ |\n| Kế hoạch được xác nhận | Fuzzy RDD, \\$4--11m ($n=999$) | $+32.0$ pp | $17.3\\%$ đối với không thuộc SubV |\n| Kế hoạch được xác nhận | Fuzzy RDD, \\$6--9m | $+49.5$ pp | $17.3\\%$ đối với không thuộc SubV |\n| Kế hoạch được xác nhận | DiD, ý định điều trị | $+12.5$ pp | --- |\n| Số ngày đến khi xác nhận | OLS / fuzzy RDD | $-24\\%$ / $-35\\%$ | trung bình 319 ngày |\n| Tỷ lệ thu hồi của chủ nợ không bảo đảm | Fuzzy RDD | $+11.9$ pp | --- |\n| Khả năng tồn tại sau phá sản | Fuzzy RDD, \\$4--11m | $+21$ pp | không có ý nghĩa ở \\$6--9m |\n\n: Tác động ước lượng của điều kiện đủ hưởng Subchapter V đối với kết cục Chapter 11 của doanh nghiệp nhỏ, từ @hotchkiss2026can. \"pp\" là điểm phần trăm. Giai đoạn một là mức nhảy $41.9$ pp trong việc sử dụng Subchapter V tại ngưỡng ($F = 71.2$) ở băng thông rộng và $37.1$ pp ($F = 19.7$) ở băng thông hẹp. {#tbl-subv-estimates}\n\nHai đặc điểm của bảng này đáng được nhấn mạnh, ngoài các con số riêng lẻ.\n\nThứ nhất là tác động rất lớn so với tỷ lệ cơ sở. Một doanh nghiệp ngay dưới ngưỡng có xác suất tái cơ cấu cao gấp hơn hai lần so với một doanh nghiệp tương tự ngay trên ngưỡng. Trong khoảng này, việc một doanh nghiệp nhỏ kiệt quệ có tồn tại được hay không phụ thuộc vào thủ tục mà nó được phép sử dụng nhiều hơn là bất cứ điều gì trên bảng cân đối kế toán. Hệ quả đối với @eq-loss-decomposition là nhân tố tổn thất có điều kiện là một tham số chính sách.\n\nThứ hai là phản bác hiển nhiên không đứng vững. Một chế độ cho phép chủ sở hữu giữ vốn chủ sở hữu bất chấp sự phản đối của chủ nợ, theo lập luận chuẩn, sẽ giữ cho các doanh nghiệp không khả thi tiếp tục tồn tại gây thiệt hại cho chủ nợ; hiệu quả hoạt động kém sau phá sản của các doanh nghiệp lớn đã thoát khỏi thủ tục phá sản từ lâu đã được xem là bằng chứng cho chính thiên lệch duy trì hoạt động đó [@hotchkiss1995postbankruptcy; @morrison2007bankruptcy]. Ở đây, tỷ lệ thu hồi kỳ vọng của chủ nợ không bảo đảm *tăng* 11.9 điểm phần trăm và khả năng tồn tại sau phá sản tăng lên chứ không giảm. Lợi ích từ việc tránh một cuộc thanh lý tốn kém dường như được chia sẻ chứ không bị tái phân phối, đúng như kỳ vọng nếu tỷ lệ thanh lý trước cải cách phản ánh chi phí giao dịch và thất bại phối hợp chứ không phải việc phân loại đúng giữa doanh nghiệp khả thi và không khả thi.\n\n## Đọc bằng chứng từ góc nhìn Việt Nam\n\nBốn hàm ý được áp dụng sang bối cảnh Việt Nam, nhưng không hàm ý nào áp dụng một cách máy móc.\n\n**Vùng kiệt quệ mang một ý nghĩa khác ở đây.** Khung pháp lý chính thức về mất khả năng thanh toán của Việt Nam là Luật Phá sản số 51/2014/QH13, có hiệu lực từ ngày 1 tháng 1 năm 2015, quy định cả thủ tục phục hồi kinh doanh và thanh lý. Tuy nhiên, như đã trình bày trong @sec-missing-delisting, các trường hợp rời khỏi nhóm doanh nghiệp niêm yết Việt Nam quan sát được chủ yếu là hủy niêm yết bắt buộc do lỗ vượt vốn điều lệ, không nộp báo cáo tài chính và xử lý vi phạm của cơ quan quản lý, chứ không phải các thủ tục tái cơ cấu dưới sự giám sát của tòa án tạo ra một tỷ lệ thu hồi quan sát được. Do đó, nội dung thực nghiệm của điểm Z'' dưới 1.10 ở Việt Nam gần với \"kỳ vọng bị hủy niêm yết và lợi nhuận cuối kỳ âm lớn\" hơn là \"kỳ vọng một quy trình có giám sát với tỷ lệ thu hồi của chủ nợ đo lường được\". Đây chính là lý do việc ước tính lợi nhuận hủy niêm yết trong @sec-missing-delisting không phải là một chi tiết kỹ thuật: đối với các doanh nghiệp Việt Nam, nó đang làm công việc mà hồ sơ vụ án của tòa án phá sản đảm nhiệm trong dữ liệu của Hoa Kỳ.\n\n**Việt Nam không có cơ sở dữ liệu tương đương FJC.** Thiết kế của Hotchkiss--Iverson--Zheng dựa trên một cuộc điều tra toàn bộ công khai, ở cấp độ từng vụ việc, về các hồ sơ nộp đơn với nợ phải trả được ghi nhận tại thời điểm nộp đơn, bổ sung bằng các bảng kê thu thập thủ công từ hồ sơ tòa án. Việt Nam không có dữ liệu nào tương đương, và việc xây dựng nó sẽ là một đóng góp nghiên cứu độc lập. Cho đến khi nó tồn tại, nghiên cứu kiệt quệ tài chính ở Việt Nam phần lớn bị giới hạn trong nhóm doanh nghiệp niêm yết, vốn là lát cắt *kém* đại diện nhất của tổng thể doanh nghiệp nhỏ mà lý thuyết hướng đến.\n\n**Ma sát tái triển khai tài sản có thể lớn hơn.** @bernstein2019asset cho thấy tài sản của các doanh nghiệp nhỏ bị thanh lý ở Hoa Kỳ được tái triển khai kém và cuối cùng bị sử dụng dưới công suất, đó là cơ chế khiến việc thanh lý quá mức gây tốn kém cho xã hội. Thị trường thứ cấp mỏng đối với thiết bị vốn đã qua sử dụng và sự phức tạp về hành chính khi chuyển nhượng quyền sử dụng đất khiến ma sát này nhiều khả năng nghiêm trọng hơn ở Việt Nam, dù chúng tôi không biết có ước lượng trực tiếp nào.\n\n**Dư địa cải cách vẫn còn rộng mở.** @hotchkiss2026can ghi nhận rằng ít nhất mười một quốc gia đã áp dụng các thủ tục mất khả năng thanh toán đơn giản hóa cho doanh nghiệp nhỏ trong thập kỷ qua, một số trong khu vực, và @gurrea2024reinventing khảo sát cải cách mất khả năng thanh toán ở các nền kinh tế mới nổi một cách cụ thể. Việt Nam không nằm trong nhóm áp dụng. Đối với nhà nghiên cứu, điều này có hai mặt: không có thí nghiệm tự nhiên sẵn có kiểu này ở Việt Nam để khai thác, nhưng câu hỏi đánh giá ex-ante hoàn toàn bỏ ngỏ và khuôn mẫu nhận diện dưới đây có thể chuyển giao.\n\n## Quy tắc ngưỡng như thiết kế nghiên cứu {#sec-valuation-threshold-designs}\n\nNội dung phương pháp luận của @hotchkiss2026can đáng được tách khỏi nội dung thể chế, vì các ngưỡng đủ điều kiện có ở khắp nơi trong quy định của Việt Nam và thiết kế này có thể chuyển giao ngay cả khi nội dung cụ thể thì không.\n\n### Gián đoạn hồi quy mờ (Fuzzy Regression Discontinuity)\n\nĐiều kiện đủ hưởng là một hàm tất định của biến chạy, nhưng *việc tham gia* thì không: 39% doanh nghiệp đủ điều kiện trong mẫu của bài nghiên cứu vẫn chọn Chapter 11 truyền thống, và một số ít doanh nghiệp có vẻ không đủ điều kiện đã được chấp nhận sau khi tòa án phân loại lại một phần nợ phải trả của họ thành nợ phụ thuộc điều kiện. Do đó, việc điều trị nhảy tại ngưỡng mà không đi từ không lên một, đó là trường hợp mờ. Đặt $s_i = L_i - c$ cho biến chạy đã được dời gốc về ngưỡng và $B_i = \\mathbf{1}\\{s_i \\leq 0\\}$ cho điều kiện đủ hưởng. Thiết kế là bình phương tối thiểu hai giai đoạn với $B_i$ là biến công cụ bị loại trừ:\n\n$$\nD_i = \\alpha + \\pi B_i + f(s_i) + B_i \\cdot g(s_i) + X_i'\\gamma + u_i\n$$ {#eq-rdd-first-stage}\n\n$$\ny_i = \\tilde{\\alpha} + \\beta \\widehat{D}_i + \\tilde{f}(s_i) + B_i \\cdot \\tilde{g}(s_i) + X_i'\\tilde{\\gamma} + \\varepsilon_i\n$$ {#eq-rdd-second-stage}\n\ntrong đó $D_i$ chỉ thị việc sử dụng thực tế thủ tục đơn giản hóa, còn $f$ và $g$ là các đa thức bậc thấp được ước lượng riêng ở mỗi phía của ngưỡng [@imbens2008regression; @lee2010regression]. Trong trường hợp vừa đủ nhận diện, $\\beta$ bằng tỷ số giữa mức nhảy dạng rút gọn của $y$ và mức nhảy giai đoạn một $\\pi$, đó là dạng Wald của bộ ước lượng và là cách hữu ích nhất để đọc nó. Điều $\\beta$ nhận diện là một tác động điều trị trung bình cục bộ: tác động đối với các doanh nghiệp gần ngưỡng sử dụng thủ tục *vì* họ đủ điều kiện. Đó không phải là tác động đối với một doanh nghiệp có nợ phải trả \\$1 triệu, và cũng không phải là tác động của việc bắt buộc áp dụng thủ tục.\n\n### Điều gì làm thiết kế đáng tin cậy\n\nBốn kiểm tra đảm nhiệm vai trò này, và cả bốn đều được báo cáo trong bài nghiên cứu.\n\n1.  **Tính liên tục của mật độ.** Nếu các doanh nghiệp thao túng biến chạy để đủ điều kiện, mật độ của $s_i$ nhảy tại ngưỡng và phép so sánh diễn ra giữa các nhóm tự chọn. Kiểm định @mccrary2008manipulation không tìm thấy sự gián đoạn ($p = 0.25$). Lập luận thể chế củng cố lập luận thống kê: một doanh nghiệp kiệt quệ không thể dễ dàng thanh toán nợ để xuống dưới một mức trần, và bản thân mức trần được nâng lên bất ngờ một tháng sau khi thủ tục mở ra.\n\n2.  **Tính trơn của các hiệp biến.** Đòn bẩy, tỷ trọng nợ có bảo đảm, tổng tài sản, tình trạng nộp đơn chung và số lượng chủ nợ đều liên tục qua ngưỡng, cả riêng lẻ lẫn đồng thời.\n\n3.  **Độ vững theo đặc tả donut-hole.** Loại bỏ các vụ việc trong dải \\$7--7.5 triệu, nơi mọi sự thao túng sẽ tập trung, hầu như không làm thay đổi các hệ số.\n\n4.  **Độ nhạy theo băng thông, được báo cáo trung thực.** Tác động xác nhận là $+32.0$ pp trong khoảng \\$4--11 triệu và $+49.5$ pp trong khoảng \\$6--9 triệu. Thu hẹp cửa sổ củng cố nhận diện nhưng làm giảm sức mạnh thống kê, và bài nghiên cứu cho thấy cả hai mặt của sự đánh đổi đó: ước lượng điểm tăng, nhưng tác động lên khả năng tồn tại có ý nghĩa ở cửa sổ rộng lại không có ý nghĩa ở cửa sổ hẹp. Báo cáo đường đi của băng thông không phải là một nghi thức kiểm tra độ vững; nó là kết quả chính. Lựa chọn băng thông theo dữ liệu với suy luận hiệu chỉnh thiên lệch [@calonico2014robust] là phần bổ sung tự nhiên, không phải là sự thay thế cho việc trình bày đường đi đó.\n\nCó một mối đe dọa mà không kiểm tra nội bộ nào có thể giải quyết, đó là sự chọn lọc vào chính mẫu. Nếu điều kiện đủ hưởng khiến các doanh nghiệp lẽ ra sẽ tái cơ cấu ngoài tòa phải nộp đơn, thì phép so sánh bị nhiễm ngay cả khi có sự gián đoạn hoàn hảo. Phản hồi của bài nghiên cứu là một khuôn mẫu hữu ích: thay vì bác bỏ mối đe dọa bằng lập luận, nó định lượng mức độ chọn lọc cần thiết để lật ngược kết quả, và cho thấy việc loại bỏ ngẫu nhiên 29 vụ Subchapter V tái cơ cấu làm ước lượng chuyển từ 32.0 sang 29.1 điểm phần trăm, trong khi để đưa nó về không cần loại bỏ ít nhất 120 vụ.\n\n### Sai biệt trong sai biệt như ý định điều trị\n\nVì thủ tục này chưa tồn tại trước tháng 2 năm 2020, cùng một ngưỡng hỗ trợ một thiết kế thứ hai,\n\n$$\ny_i = \\alpha + \\beta_1 \\text{Treated}_i + \\beta_2 \\text{Post}_t + \\beta_3\\,(\\text{Treated}_i \\times \\text{Post}_t) + X_i'\\gamma + \\varepsilon_i\n$$ {#eq-did-subv}\n\nvới các doanh nghiệp dưới mức trần là nhóm được điều trị và các doanh nghiệp ngay trên mức trần là nhóm đối chứng chưa bao giờ được điều trị. Ở đây $\\beta_3$ là tác động ý định điều trị, và nó nhỏ hơn ước lượng RDD vì hai lý do cộng dồn: không phải mọi doanh nghiệp đủ điều kiện đều sử dụng thủ tục, và mẫu trước năm 2020 chỉ có thể được chia theo *tổng* nợ phải trả chứ không phải nợ không phụ thuộc điều kiện, nên một số doanh nghiệp thực sự đủ điều kiện bị phân loại nhầm vào nhóm đối chứng. Sự đối chiếu này rất đáng học hỏi. Chia ITT là 12.5 điểm phần trăm cho giai đoạn một là 42 điểm phần trăm cho ra 29.8, gần với ước lượng RDD là 32.0. Một ITT và một LATE trông không nhất quán thường là cùng một tham số chia cho các mẫu số khác nhau.\n\n### Điều chỉnh thiết kế cho Việt Nam\n\nQuy định của Việt Nam có rất nhiều quy tắc ranh giới rõ ràng: các điều kiện niêm yết và hủy niêm yết gắn với lỗ lũy kế so với vốn điều lệ, với số năm thua lỗ liên tiếp và với ý kiến kiểm toán; các định nghĩa dựa trên quy mô quyết định khả năng tiếp cận các chương trình hỗ trợ và ưu đãi thuế; trần sở hữu nước ngoài. Mỗi quy tắc đều là một ứng viên cho biến chạy (forcing variable).\n\nLời cảnh báo là kiểm định thao túng, vốn gần như một thủ tục hình thức trong @hotchkiss2026can, trở thành yếu tố then chốt ở đây. Một doanh nghiệp Hoa Kỳ kiệt quệ không thể dễ dàng trả bớt nợ để lọt xuống dưới mức trần nợ phải trả. Một doanh nghiệp Việt Nam tiến gần ngưỡng được xác định theo lỗ lũy kế, doanh thu hoặc số lao động *được báo cáo* thường có thể làm được, và các động cơ quản trị dồn tích được ghi nhận trong chương quản trị lợi nhuận cung cấp cả động cơ lẫn phương tiện. Bất kỳ RDD nào của Việt Nam xây dựng trên một ngưỡng kế toán đều cần kiểm định mật độ, một đặc tả donut-hole (loại bỏ các quan sát sát ngưỡng) và một lập luận về lý do ngày báo cáo đi trước việc doanh nghiệp biết đến quy tắc --- và cần sẵn sàng kết luận rằng thiết kế không hiệu quả. Các quy tắc ngưỡng cũng thay đổi; nội dung chính xác và ngày có hiệu lực của thông tư điều chỉnh phải được đối chiếu với giai đoạn mẫu chứ không được mặc định.\n\n## Triển khai: Fuzzy RDD từ đầu {#sec-valuation-rdd-implementation}\n\nKhông tồn tại bảng dữ liệu phá sản cấp vụ việc nào của Việt Nam, vì vậy chúng ta mô phỏng một bảng mà quá trình sinh dữ liệu được hiệu chỉnh theo các ước lượng trong @tbl-subv-estimates: tỷ lệ xác nhận cơ sở $17\\%$, tỷ lệ tham gia khoảng $60\\%$ trong số các doanh nghiệp đủ điều kiện, và tác động cục bộ thực là $32$ điểm phần trăm. Vì biết trước giá trị thực, bộ ước lượng có thể được kiểm tra so với nó, và vấn đề chọn lọc thúc đẩy thiết kế này có thể được cố ý đưa vào. Độ phức tạp vụ việc không quan sát được làm tăng tỷ lệ tham gia và giảm xác suất xác nhận cơ sở, nên phép so sánh ngây thơ giữa doanh nghiệp sử dụng và không sử dụng thủ tục bị chệch *xuống dưới* --- cùng chiều mà @hotchkiss2026can lập luận là áp dụng trong dữ liệu của họ, nơi các doanh nghiệp nộp đơn theo Subchapter V thậm chí còn kiệt quệ hơn các doanh nghiệp nộp đơn theo Chapter 11 truyền thống.\n\n::: {#rdd-simulate .cell execution_count=31}\n``` {.python .cell-code code-summary=\"Simulate a threshold-eligibility insolvency regime\"}\nrng = np.random.default_rng(2026)\nCUTOFF = 7.5        # eligibility ceiling, in millions of currency units\nTAU = 0.32          # true local effect on the probability of confirmation\n\nn_draw = 2000\nliab = CUTOFF + rng.normal(0.0, 2.5, n_draw)\nliab = liab[(liab > 2.0) & (liab < 13.0)]\nn = liab.size\n\n# Unobserved case complexity: raises take-up, lowers baseline success.\ncomplexity = rng.normal(0.0, 1.0, n)\neligible = (liab <= CUTOFF).astype(float)\n\n# Take-up is imperfect on both sides: some eligible firms decline the\n# simplified track, and a few ineligible ones are admitted after the court\n# reclassifies part of their liabilities as contingent.\np_take = np.where(eligible == 1.0,\n                  np.clip(0.60 + 0.12 * complexity, 0.05, 0.95),\n                  0.03)\nsimplified = (rng.random(n) < p_take).astype(float)\n\np_conf = np.clip(\n    0.17 + 0.010 * (liab - CUTOFF) - 0.05 * complexity + TAU * simplified,\n    0.01, 0.99,\n)\nconfirmed = (rng.random(n) < p_conf).astype(float)\n\n# A covariate that is smooth through the threshold, for the placebo check.\nleverage = 3.0 + 0.15 * (liab - CUTOFF) + rng.normal(0.0, 1.2, n)\n\nprint(f\"Cases simulated:                 {n:,}\")\nprint(f\"Eligible (below cutoff):         {eligible.mean():6.1%}\")\nprint(f\"Use simplified track | eligible: {simplified[eligible == 1].mean():6.1%}\")\nprint(f\"Use simplified track | above:    {simplified[eligible == 0].mean():6.1%}\")\nprint(f\"Plan confirmed (overall):        {confirmed.mean():6.1%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCases simulated:                 1,940\nEligible (below cutoff):          50.8%\nUse simplified track | eligible:  58.9%\nUse simplified track | above:      2.5%\nPlan confirmed (overall):         27.5%\n```\n:::\n:::\n\n\nBộ máy ước lượng đủ ngắn để viết ra đầy đủ. Bình phương tối thiểu có trọng số với sai số chuẩn vững với phương sai thay đổi là khối xây dựng cơ bản; bình phương tối thiểu hai giai đoạn là cùng phép đại số được áp dụng cho phép chiếu của biến hồi quy nội sinh lên tập biến công cụ.\n\n::: {#rdd-estimators .cell execution_count=32}\n``` {.python .cell-code code-summary=\"Weighted least squares, weighted 2SLS, and the fuzzy RD wrapper\"}\nfrom math import erfc, sqrt\n\n\ndef tri_weights(s, h):\n    \"\"\"Triangular kernel weights on the centred running variable.\"\"\"\n    return np.clip(1.0 - np.abs(s) / h, 0.0, None)\n\n\ndef robust_wls(X, y, w):\n    \"\"\"WLS coefficients with HC1 standard errors.\"\"\"\n    Xw = X * w[:, None]\n    XtWX = X.T @ Xw\n    beta = np.linalg.solve(XtWX, Xw.T @ y)\n    e = y - X @ beta\n    G = X * (w * e)[:, None]\n    bread = np.linalg.inv(XtWX)\n    n_obs, k = X.shape\n    V = bread @ (G.T @ G) @ bread * (n_obs / max(n_obs - k, 1))\n    return beta, np.sqrt(np.diag(V))\n\n\ndef robust_2sls(X, Z, y, w):\n    \"\"\"Weighted 2SLS with HC1 standard errors; Z must have as many columns as X.\"\"\"\n    Zw = Z * w[:, None]\n    Xhat = Z @ np.linalg.solve(Z.T @ Zw, Zw.T @ X)\n    A = Xhat.T @ (X * w[:, None])\n    beta = np.linalg.solve(A, (Xhat * w[:, None]).T @ y)\n    e = y - X @ beta\n    G = Xhat * (w * e)[:, None]\n    Ainv = np.linalg.inv(A)\n    n_obs, k = X.shape\n    V = Ainv @ (G.T @ G) @ Ainv.T * (n_obs / max(n_obs - k, 1))\n    return beta, np.sqrt(np.diag(V))\n\n\ndef fuzzy_rd(running, treat, outcome, cutoff=CUTOFF, h=3.5, donut=0.0):\n    \"\"\"\n    Local-linear fuzzy RD with separate slopes on each side of the cutoff.\n\n    Returns the first stage, the reduced form (intent-to-treat), and the\n    2SLS local average treatment effect, all estimated on the same sample.\n    \"\"\"\n    s = running - cutoff\n    m = (np.abs(s) <= h) & (np.abs(s) >= donut)\n    s, d, y = s[m], treat[m], outcome[m]\n    below = (s <= 0).astype(float)\n    w = tri_weights(s, h)\n    one = np.ones_like(s)\n\n    Z = np.column_stack([one, below, s, below * s])   # instrument set\n    X = np.column_stack([one, d, s, below * s])       # structural regressors\n\n    b_fs, se_fs = robust_wls(Z, d, w)\n    b_rf, se_rf = robust_wls(Z, y, w)\n    b_iv, se_iv = robust_2sls(X, Z, y, w)\n\n    return {\n        \"h\": h, \"n\": int(m.sum()),\n        \"first_stage\": b_fs[1], \"first_stage_se\": se_fs[1],\n        \"F\": (b_fs[1] / se_fs[1]) ** 2,\n        \"itt\": b_rf[1], \"itt_se\": se_rf[1],\n        \"late\": b_iv[1], \"late_se\": se_iv[1],\n        \"wald\": b_rf[1] / b_fs[1],\n    }\n```\n:::\n\n\nGiờ đây có thể đặt phép so sánh ngây thơ và ước lượng RD cạnh nhau.\n\n::: {#rdd-main .cell execution_count=33}\n``` {.python .cell-code code-summary=\"Naive OLS versus the fuzzy RD estimate\"}\nb_naive, se_naive = robust_wls(\n    np.column_stack([np.ones(n), simplified]), confirmed, np.ones(n)\n)\nmain = fuzzy_rd(liab, simplified, confirmed, h=3.5)\n\nprint(\"=\" * 66)\nprint(\"  Effect on the probability of confirming a plan\")\nprint(\"=\" * 66)\nprint(f\"  True local effect (by construction)      {TAU:>10.3f}\")\nprint(f\"  Naive OLS, users vs non-users            {b_naive[1]:>10.3f}\"\n      f\"   (se {se_naive[1]:.3f})\")\nprint(\"-\" * 66)\nprint(f\"  Fuzzy RD, bandwidth +/-{main['h']:.1f}, n = {main['n']:,}\")\nprint(f\"    First stage (eligibility -> use)       {main['first_stage']:>10.3f}\"\n      f\"   (F = {main['F']:.1f})\")\nprint(f\"    Reduced form (intent-to-treat)         {main['itt']:>10.3f}\"\n      f\"   (se {main['itt_se']:.3f})\")\nprint(f\"    2SLS local average treatment effect    {main['late']:>10.3f}\"\n      f\"   (se {main['late_se']:.3f})\")\nprint(f\"    Wald ratio, ITT / first stage          {main['wald']:>10.3f}\")\nprint(\"=\" * 66)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n==================================================================\n  Effect on the probability of confirming a plan\n==================================================================\n  True local effect (by construction)           0.320\n  Naive OLS, users vs non-users                 0.298   (se 0.023)\n------------------------------------------------------------------\n  Fuzzy RD, bandwidth +/-3.5, n = 1,690\n    First stage (eligibility -> use)            0.562   (F = 253.7)\n    Reduced form (intent-to-treat)              0.232   (se 0.043)\n    2SLS local average treatment effect         0.414   (se 0.075)\n    Wald ratio, ITT / first stage               0.414\n==================================================================\n```\n:::\n:::\n\n\nTỷ số Wald và hệ số 2SLS trùng khớp đến độ chính xác của máy tính, vì mô hình vừa đủ nhận diện. Phép so sánh ngây thơ đánh giá thấp tác động thực, đúng như câu chuyện chọn lọc dự báo.\n\nTiếp theo là độ nhạy theo băng thông và đặc tả donut-hole. Mục đích của bảng không phải là tìm đặc tả có hệ số lớn nhất mà là xem ước lượng và độ chính xác của nó biến đổi cùng nhau như thế nào.\n\n::: {#rdd-bandwidth .cell execution_count=34}\n``` {.python .cell-code code-summary=\"Bandwidth path and donut-hole robustness\"}\nrows = []\nfor h in [1.5, 2.0, 2.5, 3.0, 3.5]:\n    r = fuzzy_rd(liab, simplified, confirmed, h=h)\n    rows.append({\"Bandwidth\": f\"+/-{h:.1f}\", \"N\": r[\"n\"],\n                 \"First stage\": r[\"first_stage\"], \"F\": r[\"F\"],\n                 \"LATE\": r[\"late\"], \"SE\": r[\"late_se\"],\n                 \"t\": r[\"late\"] / r[\"late_se\"]})\n\nr_donut = fuzzy_rd(liab, simplified, confirmed, h=3.5, donut=0.5)\nrows.append({\"Bandwidth\": \"+/-3.5 donut\", \"N\": r_donut[\"n\"],\n             \"First stage\": r_donut[\"first_stage\"], \"F\": r_donut[\"F\"],\n             \"LATE\": r_donut[\"late\"], \"SE\": r_donut[\"late_se\"],\n             \"t\": r_donut[\"late\"] / r_donut[\"late_se\"]})\n\nbw_table = pd.DataFrame(rows)\nprint(f\"Bandwidth path for the fuzzy RD estimate (true effect = {TAU:.2f})\")\nprint(bw_table.to_string(index=False, float_format=lambda v: f\"{v:8.3f}\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBandwidth path for the fuzzy RD estimate (true effect = 0.32)\n   Bandwidth    N  First stage        F     LATE       SE        t\n      +/-1.5  873        0.557  117.130    0.417    0.111    3.741\n      +/-2.0 1148        0.563  160.669    0.418    0.095    4.401\n      +/-2.5 1376        0.563  195.700    0.401    0.086    4.670\n      +/-3.0 1546        0.562  226.385    0.407    0.080    5.107\n      +/-3.5 1690        0.562  253.732    0.414    0.075    5.512\n+/-3.5 donut 1369        0.559  104.089    0.363    0.111    3.284\n```\n:::\n:::\n\n\nTiếp theo là hai kiểm tra tính hợp lệ. Kiểm định mật độ tìm sự dồn tụ (bunching) ngay dưới ngưỡng, vốn cho thấy các doanh nghiệp quản lý biến chạy để đủ điều kiện; kiểm tra hiệp biến ước lượng dạng rút gọn trên một biến mà việc điều trị không thể ảnh hưởng.\n\n::: {#rdd-validity .cell execution_count=35}\n``` {.python .cell-code code-summary=\"Density continuity test and covariate smoothness placebo\"}\ndef density_jump(x, cutoff=CUTOFF, h=3.5, binw=0.25, n_boot=400, seed=7):\n    \"\"\"\n    McCrary-style test: a local-linear density fitted separately on each side\n    of the cutoff, with a bootstrap standard error for the log difference.\n    \"\"\"\n    n_bins = int(round(2 * h / binw))\n    edges = np.linspace(-h, h, n_bins + 1)\n    mid = (edges[:-1] + edges[1:]) / 2.0\n\n    def one_jump(sample):\n        s = sample - cutoff\n        s = s[np.abs(s) <= h]\n        dens = np.histogram(s, bins=edges)[0] / (sample.size * binw)\n        fitted = []\n        for side in (-1.0, 1.0):\n            m = (mid * side) > 0\n            A = np.column_stack([np.ones(int(m.sum())), mid[m]])\n            b, _ = robust_wls(A, dens[m], tri_weights(mid[m], h))\n            fitted.append(max(b[0], 1e-12))\n        return np.log(fitted[1]) - np.log(fitted[0])\n\n    theta = one_jump(x)\n    boot_rng = np.random.default_rng(seed)\n    draws = np.array([\n        one_jump(x[boot_rng.integers(0, x.size, x.size)]) for _ in range(n_boot)\n    ])\n    se = draws.std(ddof=1)\n    z = theta / se if se > 0 else 0.0\n    return theta, se, erfc(abs(z) / sqrt(2.0))\n\n\ntheta, se_theta, p_density = density_jump(liab)\ncov_check = fuzzy_rd(liab, simplified, leverage, h=3.5)\n\nprint(\"Validity checks\")\nprint(\"-\" * 66)\nprint(f\"  Density log-jump at the cutoff   {theta:>8.3f}\"\n      f\"   (se {se_theta:.3f}, p = {p_density:.3f})\")\nprint(f\"  Leverage jump at the cutoff      {cov_check['itt']:>8.3f}\"\n      f\"   (se {cov_check['itt_se']:.3f}, \"\n      f\"t = {cov_check['itt'] / cov_check['itt_se']:.2f})\")\nprint(\"-\" * 66)\nprint(\"  Neither should be distinguishable from zero.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nValidity checks\n------------------------------------------------------------------\n  Density log-jump at the cutoff      0.034   (se 0.091, p = 0.706)\n  Leverage jump at the cutoff        -0.088   (se 0.122, t = -0.72)\n------------------------------------------------------------------\n  Neither should be distinguishable from zero.\n```\n:::\n:::\n\n\n::: {#cell-fig-rdd-discontinuity .cell execution_count=36}\n``` {.python .cell-code}\nbins = np.linspace(CUTOFF - 3.5, CUTOFF + 3.5, 29)\nidx = np.digitize(liab, bins) - 1\nmids = (bins[:-1] + bins[1:]) / 2.0\n\nfig, axes = plt.subplots(1, 2, figsize=(14, 5))\npanels = [\n    (axes[0], simplified, \"First stage: take-up of the simplified track\",\n     \"Share using the procedure\"),\n    (axes[1], confirmed, \"Reduced form: plan confirmation\",\n     \"Share confirming a plan\"),\n]\n\nfor ax, series, title, ylab in panels:\n    means = np.array([\n        series[idx == b].mean() if (idx == b).sum() > 0 else np.nan\n        for b in range(len(bins) - 1)\n    ])\n    ax.scatter(mids, means, s=34, color=colors[\"primary\"], alpha=0.85,\n               zorder=3, label=\"Binned mean\")\n    for side, col in [(-1.0, colors[\"tertiary\"]), (1.0, colors[\"quaternary\"])]:\n        m = ((mids - CUTOFF) * side > 0) & ~np.isnan(means)\n        A = np.column_stack([np.ones(int(m.sum())), mids[m] - CUTOFF])\n        b, _ = robust_wls(A, means[m], tri_weights(mids[m] - CUTOFF, 3.5))\n        grid = np.linspace(mids[m].min(), mids[m].max(), 50)\n        ax.plot(grid, b[0] + b[1] * (grid - CUTOFF), color=col, linewidth=2)\n    ax.axvline(CUTOFF, color=colors[\"distress\"], linestyle=\"--\", linewidth=2,\n               label=\"Eligibility ceiling\")\n    ax.set_xlabel(\"Non-contingent liabilities at filing (millions)\")\n    ax.set_ylabel(ylab)\n    ax.set_title(title)\n    ax.legend(loc=\"best\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Gián đoạn hồi quy mờ tại một ngưỡng đủ điều kiện. Biểu đồ bên trái thể hiện giai đoạn một: mức tham gia thủ tục đơn giản hóa nhảy gián đoạn tại mức trần nhưng không đi từ không lên một, đó là điều làm cho thiết kế là mờ chứ không phải sắc nét. Biểu đồ bên phải thể hiện dạng rút gọn: xác suất xác nhận kế hoạch giảm mạnh đối với các doanh nghiệp ngay trên mức trần. Các điểm là trung bình theo nhóm; các đường là hồi quy tuyến tính cục bộ được ước lượng riêng ở mỗi phía.](36_valuation_files/figure-html/fig-rdd-discontinuity-output-1.png){#fig-rdd-discontinuity width=2075 height=727}\n:::\n:::\n\n\nCuối cùng là phần tương ứng của sai biệt trong sai biệt. Nhóm giai đoạn trước nộp đơn trước khi thủ tục tồn tại, và biến chỉ thị điều trị của nó phải được xây dựng từ *tổng* nợ phải trả, vì sự phân chia nợ không phụ thuộc điều kiện không quan sát được trước khi quy tắc tạo ra lý do để ghi nhận nó. Sai số đo lường đó làm suy giảm ước lượng ý định điều trị, và việc điều chỉnh tỷ lệ theo giai đoạn một khôi phục tham số cấu trúc.\n\n::: {#rdd-did .cell execution_count=37}\n``` {.python .cell-code code-summary=\"Difference-in-differences intent-to-treat, and rescaling to a LATE\"}\ndid_rng = np.random.default_rng(20200219)\n\n\ndef make_cohort(size, post):\n    \"\"\"One filing cohort; the simplified track exists only when post is True.\"\"\"\n    nc_liab = CUTOFF + did_rng.normal(0.0, 2.5, size)\n    total_liab = nc_liab + did_rng.gamma(1.5, 0.6, size)   # contingent claims\n    cplx = did_rng.normal(0.0, 1.0, size)\n    can_use = (nc_liab <= CUTOFF) & bool(post)\n    p_use = np.where(can_use, np.clip(0.60 + 0.12 * cplx, 0.05, 0.95), 0.0)\n    used = (did_rng.random(size) < p_use).astype(float)\n    p_c = np.clip(0.17 + 0.010 * (nc_liab - CUTOFF) - 0.05 * cplx + TAU * used,\n                  0.01, 0.99)\n    return pd.DataFrame({\n        \"total_liab\": total_liab,\n        \"used\": used,\n        \"confirmed\": (did_rng.random(size) < p_c).astype(float),\n        \"post\": float(post),\n    })\n\n\npanel = pd.concat([make_cohort(4000, False), make_cohort(4000, True)],\n                  ignore_index=True)\npanel = panel[(panel[\"total_liab\"] >= 4.0) & (panel[\"total_liab\"] <= 11.0)].copy()\npanel[\"treated\"] = (panel[\"total_liab\"] <= CUTOFF).astype(float)\n\nD = np.column_stack([\n    np.ones(len(panel)),\n    panel[\"treated\"].to_numpy(),\n    panel[\"post\"].to_numpy(),\n    (panel[\"treated\"] * panel[\"post\"]).to_numpy(),\n])\nunit_w = np.ones(len(panel))\nb_itt, se_itt = robust_wls(D, panel[\"confirmed\"].to_numpy(), unit_w)\nb_first, se_first = robust_wls(D, panel[\"used\"].to_numpy(), unit_w)\n\nprint(\"=\" * 66)\nprint(f\"  Difference-in-differences, n = {len(panel):,}\"\n      f\"   (true effect = {TAU:.2f})\")\nprint(\"=\" * 66)\nprint(f\"  Treated x Post on confirmation (ITT)   {b_itt[3]:>8.3f}\"\n      f\"   (se {se_itt[3]:.3f})\")\nprint(f\"  Treated x Post on take-up (1st stage)  {b_first[3]:>8.3f}\"\n      f\"   (se {se_first[3]:.3f})\")\nprint(f\"  Rescaled: ITT / first stage            {b_itt[3] / b_first[3]:>8.3f}\")\nprint(\"=\" * 66)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n==================================================================\n  Difference-in-differences, n = 6,398   (true effect = 0.32)\n==================================================================\n  Treated x Post on confirmation (ITT)      0.111   (se 0.021)\n  Treated x Post on take-up (1st stage)     0.457   (se 0.016)\n  Rescaled: ITT / first stage               0.243\n==================================================================\n```\n:::\n:::\n\n\nITT rơi xa dưới tác động thực vì hầu hết các doanh nghiệp được điều trị trên danh nghĩa không bao giờ sử dụng thủ tục và một số bị phân loại nhầm theo tổng nợ phải trả thay vì nợ không phụ thuộc điều kiện. Chia cho giai đoạn một khôi phục tham số, đó là cùng phép đối chiếu mà @hotchkiss2026can báo cáo là $12.5 / 0.42 = 29.8$ điểm phần trăm so với ước lượng RDD là $32.0$.\n\nKhuôn mẫu là điều có thể chuyển giao. Với một quy tắc ngưỡng của Việt Nam, một bảng dữ liệu cấp vụ việc hoặc cấp doanh nghiệp ghi nhận biến chạy theo cách quy tắc đo lường, và một lập luận đáng tin cậy rằng các doanh nghiệp không thể tự định vị quanh ngưỡng, các đoạn mã tương tự cho ra giai đoạn một, một LATE, một đường đi băng thông và hai kiểm tra tính hợp lệ quyết định liệu toàn bộ điều này có ý nghĩa hay không.\n\n# Các cân nhắc thực tiễn và hạn chế {#sec-valuation-limitations}\n\n## Các hạn chế đã biết của Q của Tobin ở Việt Nam\n\nMột số vấn đề ảnh hưởng đến độ tin cậy của các ước lượng Q của Tobin đối với doanh nghiệp Việt Nam:\n\n1.  **Giá trị sổ sách làm đại diện cho chi phí thay thế**: Thước đo Q giản lược giả định rằng giá trị sổ sách của tài sản xấp xỉ chi phí thay thế. Với việc VAS dựa nhiều vào giá gốc, giả định này có thể gây vấn đề hơn so với các nước áp dụng IFRS, đặc biệt đối với các doanh nghiệp có quyền sử dụng đất đáng kể hoặc tài sản hữu hình tuổi thọ dài.\n\n2.  **Hiệu ứng vi cấu trúc thị trường**: Biên độ giá hằng ngày của Việt Nam có thể ngăn giá thị trường đạt tới cân bằng, có khả năng làm méo mó thành phần giá trị thị trường. Giới hạn sở hữu nước ngoài có thể tạo ra phần bù giá nhân tạo đối với một số cổ phiếu.\n\n3.  **Sự hiếm gặp của cổ phiếu ưu đãi**: Dù điều này đơn giản hóa phép tính (hầu hết doanh nghiệp Việt Nam không có cổ phiếu ưu đãi), nó có nghĩa là phép tính BE bị chi phối bởi vốn cổ phần phổ thông, có thể không nắm bắt hết mọi quyền đòi của chủ sở hữu.\n\n4.  **Hiệu ứng niêm yết chéo**: Một số doanh nghiệp Việt Nam niêm yết trên nhiều nơi (HOSE, HNX, UPCoM, hoặc thậm chí các sàn nước ngoài). Cần thận trọng để sử dụng dữ liệu giá và số cổ phiếu nhất quán.\n\n## Các hạn chế đã biết của điểm Z của Altman ở Việt Nam\n\n1.  **Mẫu hiệu chỉnh**: Điểm Z gốc được ước lượng trên các doanh nghiệp sản xuất của Hoa Kỳ giữa thế kỷ 20. Điểm Z'' cho thị trường mới nổi phù hợp hơn nhưng vẫn được ước lượng trên một mẫu không phải của Việt Nam.\n\n2.  **Khác biệt kế toán**: Các chuẩn mực kế toán VAS tạo ra các tỷ số tài chính có tính chất phân phối khác với dữ liệu US GAAP hoặc IFRS, có khả năng ảnh hưởng đến độ chính xác phân loại của hàm phân biệt.\n\n3.  **Ngân hàng và doanh nghiệp tài chính**: Điểm Z không được thiết kế cho các định chế tài chính, vốn có cấu trúc bảng cân đối kế toán khác biệt căn bản. Ngân hàng, công ty bảo hiểm và công ty chứng khoán nên được loại trừ hoặc phân tích riêng.\n\n4.  **Bảo lãnh ngầm**: Các SOE và doanh nghiệp liên kết với các tập đoàn kinh tế lớn có thể có sự hỗ trợ ngầm làm giảm rủi ro vỡ nợ thực tế xuống dưới dự báo của điểm Z.\n\n## Khuyến nghị cho các nhà nghiên cứu\n\nDựa trên phân tích của chúng tôi, chúng tôi đưa ra các khuyến nghị sau cho các nhà nghiên cứu làm việc với dữ liệu Việt Nam:\n\n1.  **Sử dụng biến thể điểm Z'' (thị trường mới nổi)** làm thước đo kiệt quệ chính cho các doanh nghiệp phi tài chính của Việt Nam.\n2.  **Báo cáo nhiều biến thể Q** (đơn giản và Chung-Pruitt) để chứng minh độ vững.\n3.  **Winsorization tại 1%/99%** để giảm thiểu tác động của lỗi dữ liệu và các giá trị ngoại lai cực đoan.\n4.  **Tính các thước đo điều chỉnh theo ngành** khi thực hiện so sánh chéo.\n5.  **Sử dụng tuổi thành lập** thay vì tuổi niêm yết khi có sẵn, nhưng báo cáo cả hai để phân biệt mức độ trưởng thành của tổ chức với kinh nghiệm trên thị trường vốn.\n6.  **Loại trừ các doanh nghiệp tài chính** khỏi phân tích điểm Z.\n7.  **Tính đến sở hữu nhà nước** như một biến điều tiết trong các nghiên cứu về định giá và kiệt quệ.\n8.  **Đừng đọc điểm Z như một dự báo thu hồi.** Nó chấm điểm xác suất kiệt quệ, không phải điều mà hệ thống pháp luật làm với một doanh nghiệp kiệt quệ; xem @sec-valuation-resolution.\n\n# Tóm tắt {#sec-valuation-summary}\n\nChương này trình bày cách tiếp cận đối với ba thước đo cơ bản của tài chính doanh nghiệp (tức Q của Tobin, điểm Z của Altman và tuổi công ty). Chúng tôi đã trình bày nền tảng lý thuyết của từng thước đo và cung cấp nhiều hình minh họa về các mô thức cắt ngang và chuỗi thời gian.\n\nCác phát hiện chính từ phân tích các doanh nghiệp niêm yết Việt Nam gồm:\n\n1.  **Q của Tobin** biến thiên đáng kể giữa các ngành và các sàn giao dịch, với các ngành công nghệ và hướng đến người tiêu dùng thường có mức định giá cao hơn. Các doanh nghiệp niêm yết trên HOSE có xu hướng có giá trị Q cao hơn các doanh nghiệp trên HNX hoặc UPCoM, phản ánh cả sự khác biệt về chất lượng doanh nghiệp lẫn hiệu ứng thanh khoản.\n\n2.  **Điểm Z của Altman** cho thấy một tỷ lệ đáng kể các doanh nghiệp Việt Nam hoạt động trong hoặc gần vùng kiệt quệ, dù biến thể phù hợp rất quan trọng; điểm Z'' cho thị trường mới nổi cho phép phân loại tinh tế hơn mô hình gốc. Sức khỏe tài chính có biến thiên chuỗi thời gian đáng kể, với sự suy giảm rõ rệt trong các giai đoạn kinh tế suy thoái.\n\n3.  **Tuổi công ty** ở Việt Nam đòi hỏi xử lý cẩn thận do việc cổ phần hóa các SOE, tạo ra khoảng cách lớn giữa tuổi thành lập và tuổi niêm yết. Sự phân biệt này có ý nghĩa quan trọng về bản chất để hiểu mối quan hệ giữa mức độ trưởng thành, định giá và sự ổn định tài chính.\n\n4.  **Giải quyết kiệt quệ** là một câu hỏi tách biệt với dự báo kiệt quệ, và điểm Z chỉ nói về vế sau. @hotchkiss2026can cho thấy chỉ riêng một thay đổi trong thủ tục mất khả năng thanh toán đã làm xác suất một doanh nghiệp nhỏ của Hoa Kỳ tái cơ cấu thay vì thanh lý tăng hơn gấp đôi, mà không gây hại đến tỷ lệ thu hồi của chủ nợ. Vì các trường hợp rời khỏi thị trường ở Việt Nam chủ yếu là hủy niêm yết bắt buộc chứ không phải tái cơ cấu dưới sự giám sát của tòa án, một điểm Z'' của Việt Nam trong vùng kiệt quệ ứng với một phân phối kết cục khác biệt đáng kể so với cùng điểm số đó trong mẫu mà các hệ số được ước lượng. @sec-valuation-resolution phát triển luận điểm này và triển khai các thiết kế gián đoạn hồi quy mờ và sai biệt trong sai biệt mà các ngưỡng đủ điều kiện cho phép.\n\n",
    "supporting": [
      "36_valuation_files\\figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}