{
  "hash": "ee2d878cab2f35e77fd37886e5174ead",
  "result": {
    "engine": "jupyter",
    "markdown": "# Đo lường sự phân kỳ quan điểm của nhà đầu tư\n\nMột câu hỏi nền tảng của kinh tế học tài chính là sự khác biệt về niềm tin của nhà đầu tư ảnh hưởng thế nào đến giá tài sản và hoạt động giao dịch. Trong các thị trường mà nhà đầu tư có kỳ vọng không đồng nhất về dòng tiền tương lai của doanh nghiệp, việc tổng hợp những quan điểm phân kỳ này thành một mức giá thị trường duy nhất là một bài toán không đơn giản, với những hàm ý sâu sắc đối với định giá tài sản, khả năng dự báo lợi nhuận và tính hiệu quả của thị trường. Khái niệm **sự phân kỳ quan điểm của nhà đầu tư** (sau đây viết tắt là DIVOP) đã trở thành một khái niệm trung tâm trong cả các nghiên cứu kế toán lẫn tài chính, đóng vai trò như một lăng kính để các nhà nghiên cứu xem xét môi trường thông tin của doanh nghiệp, động lực của việc giải tỏa bất định, và bản chất của phản ứng thị trường trước tin tức.\n\nNền tảng lý thuyết của các nghiên cứu về DIVOP bắt nguồn từ @miller1977risk, người đề xuất rằng khi các nhà đầu tư bất đồng về giá trị của một chứng khoán và các hạn chế bán khống ngăn cản các nhà đầu tư bi quan thể hiện đầy đủ quan điểm của mình, thì giá thị trường sẽ phản ánh mức định giá của những nhà đầu tư lạc quan nhất. Điều này dẫn đến tình trạng định giá quá cao có hệ thống, tăng theo mức độ phân kỳ quan điểm. Tình trạng định giá quá cao kéo dài cho đến khi các sự kiện thông tin, chẳng hạn như công bố lợi nhuận, làm giảm bất đồng và giá hội tụ về giá trị cơ bản [@berkman2009sell]. @varian1985divergence đưa ra một góc nhìn khác, trong đó sự phân kỳ quan điểm là một yếu tố rủi ro bổ sung, dẫn đến lợi nhuận kỳ vọng *cao hơn* chứ không phải thấp hơn, tạo ra một sự giằng co lý thuyết đã thúc đẩy nhiều nghiên cứu thực nghiệm.\n\nCác nghiên cứu thực nghiệm về DIVOP đã mở rộng đáng kể kể từ những đóng góp nền tảng này. Các nhà nghiên cứu đã ghi nhận rằng sự phân kỳ quan điểm giúp giải thích một loạt hiện tượng bất thường trong định giá tài sản, bao gồm hiện tượng trôi dạt sau công bố lợi nhuận [@garfinkel2006volume; @anderson2007opinion], chênh lệch lợi nhuận mặt cắt ngang giữa cổ phiếu giá trị và cổ phiếu tăng trưởng [@doukas2004divergent], lợi nhuận ngắn hạn và dài hạn sau IPO [@houge2001divergence], lợi nhuận cổ phiếu trước và sau thương vụ mua lại [@alexandridis2007divergence], phần bù thâu tóm [@chatterjee2012takeovers], và mặt cắt ngang rộng của lợi nhuận cổ phiếu [@diether2002differences; @doukas2006divergence]. Sức giải thích của DIVOP đã được chứng minh bằng một tập hợp phong phú các biến đại diện thực nghiệm, từ mức phân tán dự báo của nhà phân tích và khối lượng giao dịch bất thường đến chênh lệch giá mua–bán và biến động đặc thù.\n\nMặc dù các nghiên cứu về DIVOP đã chín muồi ở các thị trường phát triển, đặc biệt là Hoa Kỳ, việc áp dụng vào các thị trường mới nổi vẫn còn rất mỏng. Khoảng trống này đặc biệt đáng chú ý vì các điều kiện lý thuyết khiến sự phân kỳ quan điểm quan trọng nhất (cụ thể là các hạn chế bán khống có hiệu lực ràng buộc, bất cân xứng thông tin, và mức độ tinh vi không đồng đều của nhà đầu tư) có thể nói là *phổ biến hơn* ở các thị trường mới nổi so với các thị trường phát triển. Thị trường chứng khoán Việt Nam là một phòng thí nghiệm hấp dẫn để nghiên cứu sự bất đồng của nhà đầu tư. Thị trường này có một số đặc điểm làm gia tăng tính phù hợp của khung phân tích DIVOP:\n\n1.  **Hạn chế bán khống có hiệu lực ràng buộc.** Bán khống không được phép ở Việt Nam cho đến tháng 1 năm 2025, và ngay cả sau khi được đưa vào, cơ chế này vẫn chỉ giới hạn ở một nhóm chứng khoán hạn chế với những ràng buộc quản lý đáng kể về việc thực hiện. Điều này phản ánh sát bối cảnh lý thuyết của @miller1977risk, nơi các nhà đầu tư bi quan không thể thể hiện đầy đủ quan điểm của mình thông qua các vị thế bán khống.\n\n2.  **Sự áp đảo của nhà đầu tư cá nhân.** Nhà đầu tư cá nhân chiếm khoảng 80-85% khối lượng giao dịch hằng ngày trên HOSE và HNX, so với khoảng 25% ở Hoa Kỳ. Nhà đầu tư cá nhân dễ chịu tác động hơn của các thiên lệch hành vi, giao dịch theo tâm lý và các hạn chế trong xử lý thông tin, vốn tự nhiên làm nảy sinh niềm tin không đồng nhất [@phan2023role].\n\n3.  **Bất cân xứng thông tin và thách thức về minh bạch.** Mặc dù các chuẩn mực công bố thông tin đã được cải thiện, khuôn khổ quản lý báo cáo doanh nghiệp của Việt Nam vẫn kém chặt chẽ hơn so với các thị trường phát triển. Việc công bố thông tin có chọn lọc, nộp báo cáo tài chính chậm trễ, và việc thực thi hạn chế các quy định về giao dịch nội gián tạo ra một môi trường trong đó các nhà đầu tư hoạt động với những tập thông tin khác biệt đáng kể [@vo2017further].\n\n4.  **Giới hạn sở hữu nước ngoài.** Mức trần sở hữu nước ngoài (hiện là 49% đối với hầu hết các ngành, có một số ngoại lệ) tạo ra một thị trường bị phân khúc, trong đó nhà đầu tư trong nước và nước ngoài có thể có những quan điểm khác nhau một cách có hệ thống về giá trị doanh nghiệp, làm gia tăng sự phân kỳ quan điểm.\n\n5.  **Độ phủ của nhà phân tích còn mỏng.** Trong khi một doanh nghiệp S&P 500 điển hình được 15-25 nhà phân tích bên bán theo dõi, độ phủ đối với cổ phiếu Việt Nam tập trung ở một số ít công ty môi giới trong nước và một vài đơn vị nghiên cứu quốc tế. Điều này làm hạn chế tính thông tin của các thước đo DIVOP truyền thống dựa trên nhà phân tích và đòi hỏi phải dựa nhiều hơn vào các biến đại diện dựa trên thị trường.\n\nChương này trình bày một phương pháp xây dựng nhiều biến đại diện cho sự phân kỳ quan điểm của nhà đầu tư, được điều chỉnh theo các đặc điểm thể chế của thị trường Việt Nam. Chúng ta dựa trên các khung phương pháp luận do @garfinkel2009measuring và @diether2002differences thiết lập, đồng thời đưa vào những điều chỉnh phản ánh vi cấu trúc của các sàn giao dịch Việt Nam, chu kỳ thanh toán $T+2$, việc không có bán khống (cho đến gần đây), và khả năng tiếp cận dữ liệu qua các nền tảng tài chính trong nước. Cụ thể, chúng ta xây dựng và phân tích các biến đại diện DIVOP sau:\n\n-   **Khối lượng không được giải thích (DTO):** Vòng quay đã điều chỉnh theo thị trường và loại bỏ xu hướng bằng trung vị trượt, nắm bắt hoạt động giao dịch bất thường do bất đồng quan điểm sau khi kiểm soát các hiệu ứng thanh khoản và hiệu ứng toàn thị trường.\n-   **Khối lượng không được giải thích đã chuẩn hóa (SUV):** Một thước đo dựa trên hồi quy, kiểm soát một cách tường minh các thành phần thông tin và thanh khoản của khối lượng bằng cách mô hình hóa vòng quay như một hàm của lợi nhuận có dấu.\n-   **Biến động lợi nhuận cổ phiếu (VOLATILITY):** Độ lệch chuẩn của lợi nhuận hằng ngày trong một cửa sổ ước lượng trượt, đóng vai trò biến đại diện cho mức phân tán trong định giá của nhà đầu tư.\n-   **Chênh lệch giá mua–bán (BASPREAD):** Chênh lệch giá chào theo tỷ lệ, phản ánh thành phần lựa chọn bất lợi gắn với thông tin không đồng nhất giữa các thành viên thị trường.\n-   **Phân tán dự báo của nhà phân tích (DISP):** Độ lệch chuẩn mặt cắt ngang của các dự báo lợi nhuận của từng nhà phân tích, đo lường trực tiếp sự bất đồng giữa các thành viên thị trường có thông tin.\n-   **Biến động đặc thù (IVOL):** Biến động phần dư từ hồi quy mô hình nhân tố, tách riêng thành phần đặc thù của doanh nghiệp trong biến thiên lợi nhuận, phản ánh những cách diễn giải khác nhau của nhà đầu tư về thông tin cấp doanh nghiệp.\n-   **Phi thanh khoản Amihud (ILLIQ):** Tỷ số tác động giá do @amihud2002illiquidity đề xuất, nắm bắt khía cạnh bất cân xứng thông tin của sự bất đồng thông qua phản ứng giá đối với dòng lệnh.\n\nVới mỗi biến đại diện, chúng ta mô tả động cơ lý thuyết, yêu cầu về dữ liệu, phương pháp xây dựng được điều chỉnh cho dữ liệu Việt Nam, các tính chất thực nghiệm quan sát được trong mặt cắt ngang của thị trường Việt Nam, và những lưu ý thực tiễn mà các nhà nghiên cứu cần ghi nhớ khi sử dụng các thước đo này. Chúng ta đặc biệt chú ý đến các vấn đề riêng của thị trường mới nổi, bao gồm giao dịch thưa thớt, điều chỉnh hành động doanh nghiệp, các hiệu ứng vi cấu trúc đặc thù của từng sàn, và sự tương tác giữa các ràng buộc sở hữu nước ngoài với các thước đo bất đồng của nhà đầu tư.\n\n------------------------------------------------------------------------\n\n# Khung lý thuyết {#sec-theoretical-framework}\n\n## Giả thuyết định giá quá cao của Miller (1977)\n\nMô hình kinh điển về sự phân kỳ quan điểm và định giá tài sản bắt đầu từ @miller1977risk. Nhận định trung tâm của Miller rất đơn giản: trong một thị trường mà nhà đầu tư có niềm tin không đồng nhất về các khoản chi trả tương lai của một tài sản rủi ro và các hạn chế bán khống ngăn một số nhà đầu tư hành động theo quan điểm bi quan, giá cân bằng sẽ do nhóm nhà đầu tư lạc quan nhất về giá trị tài sản quyết định. Mức độ định giá quá cao tăng theo cả mức độ phân kỳ quan điểm lẫn độ nghiêm ngặt của các hạn chế bán khống. Về mặt hình thức, nếu nhà đầu tư $i$ gán cho một chứng khoán mức định giá $V_i$, giá thị trường $P$ thỏa mãn:\n\n$$\nP = E[V_i \\mid V_i \\geq V^*]\n$$\n\ntrong đó $V^*$ là mức định giá của nhà đầu tư biên, vượt quá mức định giá trung bình không điều kiện $E[V_i]$ bất cứ khi nào các hạn chế bán khống có hiệu lực ràng buộc đối với một số nhà đầu tư. Mức độ định giá quá cao là:\n\n$$\n\\text{Overpricing} = P - E[V_i] = E[V_i \\mid V_i \\geq V^*] - E[V_i]\n$$\n\nđại lượng này dương và tăng theo độ phân tán của phân phối $V_i$ (tức là sự phân kỳ quan điểm) và theo $V^*$ (tức là mức nghiêm ngặt của các hạn chế bán khống).\n\nMô hình của Miller đưa ra một số dự đoán có thể kiểm định:\n\n-   **Dự đoán theo mặt cắt ngang:** Các cổ phiếu có **mức phân kỳ quan điểm cao hơn sẽ có lợi nhuận *thấp hơn* ở các giai đoạn sau** khi giá dần điều chỉnh về giá trị cơ bản.\n-   **Dự đoán theo chuỗi thời gian:** Các sự kiện thông tin làm giảm bất đồng (ví dụ: công bố lợi nhuận) sẽ gắn với lợi nhuận bất thường âm đối với các cổ phiếu có DIVOP cao, vì \"phần bù lạc quan\" tan biến.\n-   **Dự đoán về tương tác:** Hiệu ứng định giá quá cao sẽ mạnh nhất ở các cổ phiếu đồng thời có mức phân kỳ quan điểm cao *và* chịu hạn chế bán khống có hiệu lực ràng buộc.\n\n## Các góc nhìn lý thuyết thay thế\n\n@varian1985divergence đề xuất một khung thay thế trong đó sự phân kỳ quan điểm đóng vai trò một yếu tố rủi ro. Nếu nhà đầu tư né tránh rủi ro và sự bất đồng phản ánh sự bất định thực sự về các khoản chi trả tương lai, thì **mức phân tán niềm tin cao hơn sẽ gắn với lợi nhuận kỳ vọng *cao hơn*** như một khoản bù đắp cho việc gánh thêm rủi ro. Điều này tạo ra một sự đối lập thực nghiệm rõ nét: giả thuyết Miller dự đoán mối quan hệ DIVOP-lợi nhuận mang dấu âm, trong khi mô hình Varian dự đoán mối quan hệ mang dấu dương.\n\nSự phân biệt giữa các lý thuyết này phụ thuộc then chốt vào vi cấu trúc thị trường và bối cảnh thể chế (\\@tbl-divop-theories).\n\n| Khung lý thuyết | Hạn chế bán khống | Quan hệ DIVOP-lợi nhuận | Cơ chế chính |\n|:-----------------|:-----------------|:-----------------|:-----------------|\n| @miller1977risk | Có hiệu lực ràng buộc | Âm | Thiên lệch lạc quan trong giá |\n| @varian1985divergence | Không ràng buộc | Dương | Phần bù rủi ro cho sự bất định |\n| @hong2003differences | Ràng buộc, thông tin lan tỏa dần | Âm, thay đổi theo thời gian | Quan điểm bi quan lan tỏa chậm |\n| @scheinkman2003overconfidence | Ràng buộc, tự tin thái quá | Âm | Phần bù bong bóng đầu cơ |\n\n: Tóm tắt các dự đoán lý thuyết về quan hệ DIVOP-lợi nhuận dưới các giả định khác nhau {#tbl-divop-theories}\n\n@hong2003differences mở rộng khung của Miller bằng cách đưa vào sự lan tỏa thông tin dần dần. Trong mô hình của họ, thông tin tiêu cực được phản ánh vào giá chậm hơn thông tin tích cực vì các hạn chế bán khống làm tăng chi phí hành động theo quan điểm bi quan. Điều này tạo ra các mô thức giống động lượng, trong đó các cổ phiếu có DIVOP cao có lợi nhuận ngắn hạn dương (khi những người lạc quan đẩy giá lên) rồi đến lợi nhuận dài hạn âm (khi thông tin tiêu cực cuối cùng cũng đến được thị trường).\n\n@scheinkman2003overconfidence đưa thêm một chiều mới khi lưu ý rằng khi nhà đầu tư tự tin thái quá về tín hiệu riêng *và* các hạn chế bán khống có hiệu lực ràng buộc, giá cổ phiếu chứa một thành phần \"bong bóng đầu cơ\" phản ánh giá trị quyền chọn của việc bán lại tài sản cho một nhà đầu tư tương lai có thể còn lạc quan hơn. Mô hình này dự đoán rằng cả khối lượng giao dịch cao lẫn biến động giá cao đều gắn với tình trạng định giá quá cao, tạo cơ sở lý thuyết cho việc sử dụng các biến đại diện DIVOP dựa trên khối lượng và dựa trên biến động.\n\n## Mức độ liên quan đối với thị trường Việt Nam\n\nThị trường chứng khoán Việt Nam cung cấp một bối cảnh đặc biệt sạch để kiểm định giả thuyết Miller. Thị trường chứng khoán Việt Nam vận hành mà không có bất kỳ cơ chế bán khống nào từ khi thành lập năm 2000 cho đến tháng 1 năm 2025, tức là suốt một phần tư thế kỷ, trong đó điều kiện cần đầu tiên của mô hình Miller (hạn chế bán khống có hiệu lực ràng buộc) được thỏa mãn bởi quy định chứ không phải do các ma sát thị trường. Ngay cả sau khi đưa vào bán khống có bảo đảm năm 2025, cơ chế này vẫn chỉ giới hạn ở các chứng khoán đáp ứng ngưỡng cụ thể về thanh khoản và vốn hóa thị trường, và môi trường quản lý đặt ra các yêu cầu vay mượn làm tăng đáng kể chi phí bán khống so với các thị trường phát triển.\n\nSự áp đảo của nhà đầu tư cá nhân làm khuếch đại điều kiện cần thứ hai (tức là niềm tin không đồng nhất). Các nghiên cứu về thị trường Việt Nam đã ghi nhận hành vi bầy đàn đáng kể [@vo2017further; @vo2015foreign], giao dịch theo tâm lý [@phan2023role; @nguyen2018search], và bất cân xứng thông tin giữa nhà đầu tư trong nước và nước ngoài [@vo2017foreign]. Những đặc điểm hành vi này tự nhiên tạo ra mức phân tán trong định giá của nhà đầu tư rộng hơn so với các thị trường do nhà đầu tư tổ chức chi phối, vốn có khả năng tiếp cận các khung phân tích và nguồn thông tin tương tự nhau.\n\n@tbl-divop-vietnam-us so sánh các đặc điểm thể chế chủ chốt liên quan đến khung DIVOP giữa Việt Nam và Hoa Kỳ.\n\n| Đặc điểm | Việt Nam (HOSE/HNX) | Hoa Kỳ (NYSE/NASDAQ) |\n|:-----------------------|:-----------------------|:-----------------------|\n| Bán khống | Áp dụng từ tháng 1/2025 (hạn chế) | Được phép (Reg SHO từ 2005) |\n| Tỷ trọng nhà đầu tư cá nhân trong khối lượng | \\~80-85% | \\~25% |\n| Chu kỳ thanh toán | T+2 (dự kiến T+1 vào 2026) | T+1 (từ tháng 5/2024) |\n| Biên độ giá hằng ngày | $\\pm$ 7% (HOSE), $\\pm$ 10% (HNX) | Không có |\n| Mức trần sở hữu nước ngoài | 49% (hầu hết các ngành) | Không có |\n| Độ phủ nhà phân tích trung bình (VN30) | 5-10 nhà phân tích | 15-25 nhà phân tích |\n| Báo cáo hằng quý bắt buộc | Có (từ 2012) | Có |\n| Thị trường quyền chọn/phái sinh | Hợp đồng tương lai VN30 (từ 2017) | Quyền chọn/hợp đồng tương lai phong phú |\n\n: So sánh thể chế giữa Việt Nam và Hoa Kỳ liên quan đến sự phân kỳ quan điểm {#tbl-divop-vietnam-us}\n\nBiên độ giá hằng ngày ($\\pm$ 7% trên HOSE và $\\pm$ 10% trên HNX) tạo ra một cơ chế bổ sung làm khuếch đại sự phân kỳ quan điểm. Khi một cổ phiếu chạm biên độ giá, các nhà đầu tư muốn giao dịch theo hướng của biên độ không thể thực hiện được, dẫn đến lệnh chưa khớp tích tụ và việc khám phá giá bị trì hoãn. Đặc điểm thể chế này có thể tạo ra các đỉnh nhọn ngắn hạn trong DIVOP đo được, phản ánh ma sát do biên độ gây ra chứ không phải sự bất đồng thực sự. Chúng ta xử lý vấn đề này trong phương pháp thực nghiệm bằng cách đánh dấu các ngày chạm biên độ và thực hiện các kiểm tra độ vững loại trừ những quan sát này.\n\n# Nguồn dữ liệu và xây dựng mẫu {#sec-data}\n\n## Nguồn dữ liệu\n\nViệc xây dựng các biến đại diện DIVOP cho thị trường Việt Nam đòi hỏi dữ liệu giao dịch cổ phiếu hằng ngày và, đối với các thước đo phân tán của nhà phân tích, dữ liệu dự báo của từng nhà phân tích. Chúng ta lấy toàn bộ dữ liệu từ [DataCore.vn](https://datacore.vn/en), nguồn cung cấp độ phủ của mọi chứng khoán niêm yết trên HOSE, HNX và sàn UPCoM (Unlisted Public Company Market). @tbl-divop-data-sources tóm tắt các bộ dữ liệu và biến chính được dùng trong nghiên cứu này.\n\n| Bộ dữ liệu | Biến chính | Tần suất |\n|:-----------------------|:-----------------------|:-----------------------|\n| Giao dịch cổ phiếu hằng ngày | Giá đóng cửa, giá cao nhất, giá thấp nhất, giá mở cửa, khối lượng, số cổ phiếu đang lưu hành, giá điều chỉnh, giá mua, giá bán | Hằng ngày |\n| Hành động doanh nghiệp | Cổ tức, chia tách cổ phiếu, cổ phiếu thưởng, phát hành quyền mua | Theo sự kiện |\n| Thông tin doanh nghiệp | Mã sàn, phân loại ngành (ICB), ngày niêm yết, ngày hủy niêm yết | Tĩnh/Định kỳ |\n| Dự báo của nhà phân tích | Dự báo EPS của từng nhà phân tích, ngày công bố, ngày kết thúc kỳ tài chính, mã nhà phân tích, tên công ty môi giới | Theo từng dự báo |\n| Chỉ số thị trường | Lợi nhuận hằng ngày của VN-Index, VN30, HNX-Index | Hằng ngày |\n| Sở hữu nước ngoài | Khối lượng mua/bán của nhà đầu tư nước ngoài, tỷ lệ sở hữu nước ngoài, room ngoại còn lại | Hằng ngày |\n\n: Nguồn dữ liệu và các biến chính để xây dựng biến đại diện DIVOP {#tbl-divop-data-sources}\n\n## Xây dựng mẫu\n\nChúng ta xây dựng mẫu bằng các bộ lọc sau, áp dụng tuần tự:\n\n::: {#sample-construction .cell execution_count=1}\n``` {.python .cell-code code-summary=\"Sample construction and initial data loading\"}\nimport pandas as pd\nimport numpy as np\nfrom datetime import datetime, timedelta\nfrom sklearn.linear_model import LinearRegression\nfrom scipy import stats as scipy_stats\nimport matplotlib.pyplot as plt\nimport matplotlib.dates as mdates\nimport seaborn as sns\nimport warnings\nwarnings.filterwarnings('ignore')\n\n# =============================================================================\n# Configuration Parameters\n# =============================================================================\n# Users can modify these parameters to adjust the methodology\nCONFIG = {\n    # Sample period\n    'beg_date': '2007-01-01',\n    'end_date': '2024-12-31',\n    \n    # Estimation windows (in trading days)\n    'est_window': 60,          # Rolling window for SUV and volatility\n    'detrend_window': 180,     # Window for DTO detrending median\n    'lag': 7,                  # Lag for DTO detrending\n    'gap': 5,                  # Gap between estimation period and event date\n    \n    # Filters\n    'min_price': 1000,         # Minimum price in VND\n    'min_volume_days': 0.8,    # Min fraction of non-zero volume days in window\n    'min_analysts': 3,         # Minimum number of analysts for DISP\n    'max_spread_pct': 0.50,    # Maximum bid-ask spread as fraction of midpoint\n    'forecast_carry_days': 105,# Days to carry forward stale analyst forecasts\n    \n    # Exchange identifiers\n    'exchanges': ['HOSE', 'HNX'],\n    \n    # Price limit thresholds (for flagging)\n    'price_limit_hose': 0.07,\n    'price_limit_hnx': 0.10,\n}\n\nprint(\"Configuration parameters loaded successfully.\")\nprint(f\"Sample period: {CONFIG['beg_date']} to {CONFIG['end_date']}\")\nprint(f\"Estimation window: {CONFIG['est_window']} trading days\")\nprint(f\"Detrending window: {CONFIG['detrend_window']} trading days\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nConfiguration parameters loaded successfully.\nSample period: 2007-01-01 to 2024-12-31\nEstimation window: 60 trading days\nDetrending window: 180 trading days\n```\n:::\n:::\n\n\nTập mẫu bao gồm mọi cổ phiếu phổ thông niêm yết trên HOSE và HNX trong giai đoạn từ tháng 1 năm 2007 đến tháng 12 năm 2024. Chúng ta bắt đầu từ năm 2007 thay vì từ khi thị trường hình thành (2000 đối với HOSE, 2005 đối với HNX) vì hai lý do. Thứ nhất, những năm đầu của thị trường Việt Nam có số doanh nghiệp niêm yết cực nhỏ (dưới 30 doanh nghiệp trên HOSE cho đến năm 2005), khiến phân tích mặt cắt ngang không đáng tin cậy. Thứ hai, chất lượng và tính nhất quán của dữ liệu cải thiện đáng kể sau đợt mở rộng thị trường 2006-2007, trong đó số doanh nghiệp niêm yết trên HOSE tăng từ khoảng 40 lên hơn 100.\n\nChúng ta áp dụng các bộ lọc sau để xây dựng mẫu phân tích:\n\n1.  **Bộ lọc loại chứng khoán.** Chúng ta chỉ giữ lại cổ phiếu phổ thông, loại trừ cổ phiếu ưu đãi, quỹ hoán đổi danh mục (ETF), chứng quyền có bảo đảm và chứng chỉ tiền gửi. Điều này tương tự bộ lọc chuẩn trong các nghiên cứu ở Hoa Kỳ, vốn giới hạn ở mã cổ phiếu CRSP 10 và 11.\n\n2.  **Bộ lọc sàn giao dịch.** Chúng ta đưa vào các cổ phiếu niêm yết trên HOSE và HNX nhưng loại trừ các chứng khoán UPCoM trong phân tích cơ sở. UPCoM là địa điểm giao dịch dựa trên đăng ký, với yêu cầu niêm yết ít chặt chẽ hơn và thanh khoản thấp hơn đáng kể, có thể đưa nhiễu vào các thước đo dựa trên khối lượng và chênh lệch giá. Chúng ta đưa UPCoM vào các kiểm tra độ vững.\n\n3.  **Bộ lọc giá.** Chúng ta loại trừ các quan sát cổ phiếu-ngày có giá đóng cửa dưới 1,000 VND. Ngưỡng này phục vụ cùng mục đích với việc loại trừ \"cổ phiếu penny\" phổ biến trong các nghiên cứu ở Hoa Kỳ (thường là ngưỡng \\$1 hoặc \\$5) và giúp giảm ảnh hưởng của lợi nhuận phần trăm và chênh lệch giá cực đoan ở các mức giá rất thấp.\n\n4.  **Hoạt động giao dịch tối thiểu.** Với các thước đo dựa trên khối lượng, chúng ta yêu cầu cổ phiếu có khối lượng giao dịch khác không trong ít nhất 80% số ngày giao dịch của mỗi cửa sổ ước lượng. Bộ lọc này loại bỏ những chứng khoán giao dịch thưa thớt nhất, vốn khiến các thước đo dựa trên vòng quay không đáng tin cậy.\n\n::: {#load-and-filter .cell execution_count=2}\n``` {.python .cell-code code-summary=\"Load and filter daily stock data\"}\ndef load_daily_data(config):\n    \"\"\"\n    Load daily stock trading data from DataCore.vn.\n    \n    In practice, this function connects to the DataCore API or reads\n    from a local database/CSV. Here we document the expected schema.\n    \n    Expected columns:\n    - ticker: str, stock ticker symbol (e.g., 'VCB', 'HPG', 'VNM')\n    - date: datetime, trading date\n    - open, high, low, close: float, daily OHLC prices (VND)\n    - volume: int, trading volume (shares)\n    - shares_outstanding: int, total shares outstanding\n    - adjusted_close: float, price adjusted for corporate actions\n    - adj_factor: float, cumulative adjustment factor\n    - bid, ask: float, best bid/ask at close\n    - exchange: str, exchange code ('HOSE', 'HNX', 'UPCOM')\n    - industry_icb: str, ICB industry classification code\n    - foreign_buy_vol, foreign_sell_vol: int, foreign investor volumes\n    - foreign_ownership_pct: float, foreign ownership percentage\n    \"\"\"\n    # =========================================================================\n    # Replace with actual DataCore API call:\n    # from datacore import Client\n    # client = Client(api_key='YOUR_KEY')\n    # df = client.daily_stock(\n    #     start=config['beg_date'], end=config['end_date'],\n    #     exchanges=config['exchanges']\n    # )\n    # =========================================================================\n    print(\"Connect to DataCore.vn and load daily stock data.\")\n    print(\"Expected schema: ticker, date, open, high, low, close, volume,\")\n    print(\"  shares_outstanding, adjusted_close, adj_factor, bid, ask,\")\n    print(\"  exchange, industry_icb, foreign_buy_vol, foreign_sell_vol,\")\n    print(\"  foreign_ownership_pct\")\n    return None  # Replace with actual data\n\n\ndef apply_sample_filters(df, config):\n    \"\"\"Apply sequential sample construction filters.\"\"\"\n    print(\"\\n=== Sample Construction ===\")\n    n0 = len(df)\n    \n    # Date filter\n    df = df[(df['date'] >= config['beg_date']) &\n            (df['date'] <= config['end_date'])].copy()\n    print(f\"[1] Date filter: {len(df):,} obs (from {n0:,})\")\n    \n    # Exchange filter\n    df = df[df['exchange'].isin(config['exchanges'])].copy()\n    print(f\"[2] Exchange filter ({config['exchanges']}): {len(df):,} obs\")\n    \n    # Price filter\n    df = df[df['close'] >= config['min_price']].copy()\n    print(f\"[3] Price >= {config['min_price']:,} VND: {len(df):,} obs\")\n    \n    # Compute daily return from adjusted prices\n    df = df.sort_values(['ticker', 'date'])\n    df['ret'] = df.groupby('ticker')['adjusted_close'].pct_change()\n    \n    # Flag price limit hits\n    df['limit_hit'] = (\n        ((df['exchange'] == 'HOSE') &\n         (df['ret'].abs() >= config['price_limit_hose'] - 0.001)) |\n        ((df['exchange'] == 'HNX') &\n         (df['ret'].abs() >= config['price_limit_hnx'] - 0.001))\n    )\n    \n    n_tickers = df['ticker'].nunique()\n    print(f\"\\nFinal sample: {len(df):,} stock-day obs, \"\n          f\"{n_tickers} unique tickers\")\n    print(f\"Limit-hit days: {df['limit_hit'].sum():,} \"\n          f\"({100*df['limit_hit'].mean():.2f}%)\")\n    return df\n```\n:::\n\n\n## Điều chỉnh theo hành động doanh nghiệp {#sec-corp-actions}\n\nĐiều chỉnh đúng đắn theo các hành động doanh nghiệp là yếu tố then chốt đối với các thước đo DIVOP dựa trên khối lượng, vì các sự kiện như chia tách cổ phiếu, phát hành cổ phiếu thưởng và phát hành quyền mua làm thay đổi số cổ phiếu đang lưu hành và có thể tạo ra các đỉnh nhọn giả tạo trong vòng quay đo được. Chúng ta cần dùng các hệ số điều chỉnh tích lũy tính đến cổ tức bằng cổ phiếu (cổ phiếu thưởng), chia tách cổ phiếu, phát hành quyền mua và cổ tức tiền mặt (chỉ điều chỉnh giá). Chúng ta dùng các hệ số này để xây dựng khối lượng điều chỉnh và số cổ phiếu đang lưu hành điều chỉnh:\n\n$$\n\\text{AdjVolume}_{i,t} = \\text{Volume}_{i,t} \\times \\text{CumAdjFactor}_{i,t}\n$$\n\n$$\n\\text{AdjSharesOut}_{i,t} = \\text{SharesOut}_{i,t} \\times \\text{CumAdjFactor}_{i,t}\n$$\n\nĐiều này bảo đảm tỷ lệ vòng quay nhất quán giữa các sự kiện hành động doanh nghiệp.\n\n::: {#corp-action .cell execution_count=3}\n``` {.python .cell-code code-summary=\"Corporate action adjustment\"}\ndef adjust_for_corporate_actions(df):\n    \"\"\"Apply cumulative adjustment factors to volume and shares outstanding.\"\"\"\n    df = df.copy()\n    df['adj_volume'] = df['volume'] * df['adj_factor']\n    df['adj_shares_out'] = df['shares_outstanding'] * df['adj_factor']\n    \n    # Daily turnover ratio\n    df['turnover'] = np.where(\n        df['adj_shares_out'] > 0,\n        df['adj_volume'] / df['adj_shares_out'],\n        np.nan\n    )\n    \n    # Flag extreme turnover (> 50% of float)\n    extreme = df['turnover'] > 0.50\n    if extreme.any():\n        print(f\"Warning: {extreme.sum()} obs with turnover > 50%, set to NaN\")\n        df.loc[extreme, 'turnover'] = np.nan\n    \n    return df\n```\n:::\n\n\n## Xây dựng lịch giao dịch {#sec-calendar}\n\nPhương pháp hồi quy trượt cho SUV và biến động đòi hỏi một lịch giao dịch bảo đảm mỗi cửa sổ ước lượng chứa chính xác số ngày giao dịch đã định. Chúng ta xây dựng lịch này trực tiếp từ các ngày giao dịch quan sát được.\n\n::: {#trading-calendar .cell execution_count=4}\n``` {.python .cell-code code-summary=\"Build trading calendar for rolling estimation windows\"}\ndef build_trading_calendar(df, config):\n    \"\"\"\n    Map each trading date to its estimation window [est_start, est_end].\n    \n    For date t, the estimation window runs from\n    t - gap - est_window to t - gap - 1 (in trading-day terms).\n    \"\"\"\n    trading_dates = sorted(df['date'].unique())\n    trading_dates = pd.Series(trading_dates)\n    \n    est_window = config['est_window']\n    gap = config['gap']\n    offset = est_window + gap\n    \n    records = []\n    for i in range(offset, len(trading_dates)):\n        records.append({\n            'date': trading_dates.iloc[i],\n            'est_start': trading_dates.iloc[i - gap - est_window],\n            'est_end': trading_dates.iloc[i - gap - 1]\n        })\n    \n    calendar = pd.DataFrame(records)\n    print(f\"Trading calendar: {len(calendar)} dates, \"\n          f\"{calendar['date'].min()} to {calendar['date'].max()}\")\n    return calendar\n```\n:::\n\n\n# Các biến đại diện DIVOP dựa trên khối lượng {#sec-volume-based}\n\n## Động cơ lý thuyết\n\nKhối lượng giao dịch từ lâu đã được công nhận là biến đại diện tự nhiên cho sự phân kỳ quan điểm của nhà đầu tư. Trong khung kỳ vọng hợp lý của @milgrom1982information, giao dịch chỉ xảy ra khi các nhà đầu tư bất đồng về giá trị của một chứng khoán (tức là một \"định lý không giao dịch\" hàm ý, theo phản đảo, rằng khối lượng giao dịch quan sát được phải phản ánh một dạng niềm tin không đồng nhất nào đó). @harris1993differences và @kandel1995differential hình thức hóa trực giác này, cho thấy khối lượng giao dịch có quan hệ cùng chiều với mức phân tán của niềm tin ban đầu của nhà đầu tư và với mức độ thông tin công khai được diễn giải khác nhau.\n\nKhó khăn khi dùng khối lượng giao dịch thô làm biến đại diện DIVOP là khối lượng còn chịu tác động của các yếu tố không liên quan đến bất đồng, bao gồm tái cân bằng danh mục, yêu cầu về thanh khoản, bán để ghi nhận lỗ thuế và các hiệu ứng tái cơ cấu chỉ số. @garfinkel2009measuring đề xuất hai cách để tách thành phần bất đồng khỏi khối lượng thô. Cách thứ nhất, **Khối lượng không được giải thích (DTO)**, loại bỏ các hiệu ứng khối lượng toàn thị trường và xu hướng dài hạn. Cách thứ hai, **Khối lượng không được giải thích đã chuẩn hóa (SUV)**, kiểm soát thêm hàm lượng thông tin của lợi nhuận thông qua một hồi quy mặt cắt ngang, tách riêng thành phần \"bất đồng thuần túy\" của hoạt động giao dịch.\n\n## Khối lượng không được giải thích (DTO) {#sec-dto}\n\n### Phương pháp xây dựng\n\nViệc xây dựng thước đo Khối lượng không được giải thích gồm bốn bước.\n\n**Bước 1: Tính vòng quay hằng ngày cấp doanh nghiệp.** Với mỗi cổ phiếu $i$ vào ngày $t$:\n\n$$\n\\text{Turn}_{i,t} = \\frac{\\text{AdjVolume}_{i,t}}{\\text{AdjSharesOut}_{i,t}}\n$$\n\n**Bước 2: Tính vòng quay toàn thị trường.** Chúng ta tính vòng quay tổng hợp của mọi cổ phiếu phổ thông dưới dạng trung bình theo trọng số vốn hóa:\n\n$$\n\\text{MktTurn}_{t} = \\frac{\\sum_{i} \\text{AdjVolume}_{i,t}}{\\sum_{i} \\text{AdjSharesOut}_{i,t}}\n$$\n\nKhác với phương pháp ở Hoa Kỳ vốn tính vòng quay thị trường chỉ trên các cổ phiếu NYSE/AMEX và áp dụng một điều chỉnh tỷ lệ cho các chứng khoán NASDAQ [theo @anderson2005market], chúng ta tính vòng quay thị trường trên mọi cổ phiếu phổ thông của HOSE và HNX mà không có bất kỳ việc điều chỉnh tỷ lệ khối lượng riêng cho từng sàn nào. Cả hai sàn của Việt Nam đều vận hành như thị trường dẫn dắt bởi lệnh (HOSE dùng khớp lệnh liên tục; HNX dùng kết hợp khớp lệnh liên tục và đấu giá định kỳ) mà không có vấn đề tính trùng của thị trường nhà tạo lập (dealer market), vấn đề vốn đòi hỏi điều chỉnh khối lượng NASDAQ trong các nghiên cứu ở Hoa Kỳ.\n\n**Bước 3: Tính vòng quay đã điều chỉnh theo thị trường.**\n\n$$\n\\text{MATO}_{i,t} = \\text{Turn}_{i,t} - \\text{MktTurn}_{t}\n$$\n\n**Bước 4: Loại bỏ xu hướng bằng trung vị trượt.** Để loại bỏ các xu hướng dài hạn trong hoạt động giao dịch đặc thù của doanh nghiệp:\n\n$$\n\\text{DTO}_{i,t} = \\text{MATO}_{i,t} - \\text{Median}_{180}(\\text{MATO}_{i,t-7})\n$$\n\ntrong đó $\\text{Median}_{180}(\\text{MATO}_{i,t-7})$ là trung vị của vòng quay đã điều chỉnh theo thị trường trong cửa sổ 180 ngày giao dịch kết thúc 7 ngày trước ngày $t$. Độ trễ 7 ngày ngăn vòng quay của ngày hiện tại ảnh hưởng đến mức cơ sở dùng để loại bỏ xu hướng của chính nó.\n\n::: {#dto-construction .cell execution_count=5}\n``` {.python .cell-code code-summary=\"Construct the Unexplained Volume (DTO) measure\"}\ndef compute_market_turnover(df):\n    \"\"\"Compute daily market-wide turnover across all stocks.\"\"\"\n    mkt_turn = df.groupby('date').apply(\n        lambda x: x['adj_volume'].sum() / x['adj_shares_out'].sum()\n        if x['adj_shares_out'].sum() > 0 else np.nan\n    ).reset_index()\n    mkt_turn.columns = ['date', 'market_turnover']\n    return mkt_turn\n\n\ndef compute_dto(df, config):\n    \"\"\"\n    Construct Unexplained Volume (DTO).\n    \n    Steps:\n    1. Subtract market turnover -> MATO\n    2. Rolling 180-day median of MATO (lagged 7 days) -> trend\n    3. DTO = MATO - trend\n    \"\"\"\n    detrend_window = config['detrend_window']\n    lag = config['lag']\n    \n    # Market turnover\n    mkt_turn = compute_market_turnover(df)\n    df = df.merge(mkt_turn, on='date', how='left')\n    \n    # Market-adjusted turnover\n    df['mato'] = df['turnover'] - df['market_turnover']\n    \n    # Rolling median with lag, computed per stock\n    df = df.sort_values(['ticker', 'date'])\n    \n    def _rolling_median_lagged(group):\n        mato = group['mato']\n        med = mato.rolling(\n            window=detrend_window,\n            min_periods=int(detrend_window * 0.5)\n        ).median()\n        return med.shift(lag)\n    \n    df['mato_trend'] = (\n        df.groupby('ticker', group_keys=False)\n          .apply(lambda g: _rolling_median_lagged(g))\n    )\n    \n    # DTO\n    df['dto'] = df['mato'] - df['mato_trend']\n    \n    print(\"DTO construction complete.\")\n    print(f\"  Non-missing: {df['dto'].notna().sum():,}\")\n    print(f\"  Mean: {df['dto'].mean():.6f}, Std: {df['dto'].std():.6f}\")\n    return df\n```\n:::\n\n\n### Những lưu ý riêng của Việt Nam đối với DTO\n\nMột số đặc điểm của thị trường Việt Nam cần được chú ý khi xây dựng DTO:\n\n1.  **Không cần điều chỉnh khối lượng kiểu NASDAQ.** Cả HOSE và HNX đều là thị trường đấu giá dẫn dắt bởi lệnh. Điều chỉnh tính trùng áp dụng cho các chứng khoán NASDAQ trong các nghiên cứu ở Hoa Kỳ là không cần thiết.\n\n2.  **Cổ phiếu giao dịch thưa thớt.** Một tỷ lệ đáng kể cổ phiếu niêm yết của Việt Nam, đặc biệt trên HNX, có thể có khối lượng bằng không trong nhiều ngày giao dịch. Với các cổ phiếu giao dịch không liên tục, trung vị trượt có thể bị chệch về không, khiến DTO kém thông tin hơn. Chúng ta yêu cầu ít nhất 80% số ngày có khối lượng khác không trong mỗi cửa sổ ước lượng.\n\n3.  **Tác động của biên độ giá lên khối lượng.** Khi một cổ phiếu chạm biên độ giá hằng ngày, các lệnh chưa khớp tích tụ và khối lượng ghi nhận có thể thấp hơn khối lượng khớp thực. Ngày hôm sau thường xuất hiện hiệu ứng \"bắt kịp\". Các nhà nghiên cứu nên cân nhắc đánh dấu các ngày chạm biên độ.\n\n4.  **Phân rã giao dịch của nhà đầu tư nước ngoài.** DataCore cung cấp khối lượng theo loại nhà đầu tư (nước ngoài so với trong nước). Các nhà nghiên cứu có thể muốn xây dựng các thước đo DTO riêng cho khối lượng của nhà đầu tư nước ngoài và trong nước, hoặc dùng tỷ lệ khối lượng nước ngoài trên trong nước như một chiều bổ sung của sự bất đồng.\n\n## Khối lượng không được giải thích đã chuẩn hóa (SUV) {#sec-suv}\n\n### Phương pháp xây dựng\n\nThước đo Khối lượng không được giải thích đã chuẩn hóa, do @garfinkel2009measuring đề xuất, tách riêng thành phần bất đồng của khối lượng bằng cách kiểm soát một cách tường minh hàm lượng thông tin của lợi nhuận. Ý tưởng là khối lượng giao dịch có cả thành phần **thanh khoản** lẫn thành phần **thông tin** tương quan với độ lớn và dấu của lợi nhuận. Bằng cách hồi quy vòng quay theo lợi nhuận có dấu và lấy phần dư chuẩn hóa, SUV nắm bắt khối lượng do bất đồng gây ra sau khi kiểm soát cả xu hướng thanh khoản lẫn giao dịch dựa trên thông tin.\n\nVới mỗi cổ phiếu $i$, tại mỗi ngày giao dịch $t$, chúng ta ước lượng bằng dữ liệu từ cửa sổ ước lượng $[\\tau_1, \\tau_2]$:\n\n$$\n\\text{Turn}_{i,s} = \\alpha_i + \\beta_i^{+} \\cdot \\text{RetPos}_{i,s} + \\beta_i^{-} \\cdot \\text{RetNeg}_{i,s} + \\epsilon_{i,s}, \\quad s \\in [\\tau_1, \\tau_2]\n$$ {#eq-suv-regression}\n\ntrong đó $\\text{RetPos}_{i,s} = |r_{i,s}| \\cdot \\mathbf{1}(r_{i,s} > 0)$ và $\\text{RetNeg}_{i,s} = |r_{i,s}| \\cdot \\mathbf{1}(r_{i,s} < 0)$.\n\nKhối lượng không được giải thích đã chuẩn hóa vào ngày $t$ là:\n\n$$\n\\text{SUV}_{i,t} = \\frac{\\text{Turn}_{i,t} - \\hat{\\text{Turn}}_{i,t}}{\\hat{\\sigma}_{\\epsilon,i}}\n$$ {#eq-suv}\n\ntrong đó $\\hat{\\text{Turn}}_{i,t}$ là vòng quay dự báo và $\\hat{\\sigma}_{\\epsilon,i}$ là RMSE từ @eq-suv-regression.\n\nĐặc tả bất đối xứng với các hệ số riêng cho lợi nhuận dương và âm phản ánh việc quan hệ khối lượng-lợi nhuận khác nhau theo dấu của lợi nhuận. Ở Hoa Kỳ, áp lực mua có xu hướng tạo ra khối lượng lớn hơn áp lực bán do các ma sát bán khống. Ở Việt Nam, nơi bán khống không khả dụng cho đến năm 2025, sự bất đối xứng này được kỳ vọng còn rõ rệt hơn vì mọi hoạt động bán đều bị giới hạn ở các cổ đông hiện hữu.\n\n::: {#suv-construction .cell execution_count=6}\n``` {.python .cell-code code-summary=\"Construct Standardized Unexplained Volume (SUV)\"}\ndef compute_suv(df, calendar, config):\n    \"\"\"\n    Compute Standardized Unexplained Volume via rolling regressions.\n    \n    For each stock-date, regress Turn on RetPos and RetNeg over the\n    estimation window, then compute SUV = (actual - predicted) / RMSE.\n    \"\"\"\n    est_window = config['est_window']\n    min_obs = int(est_window * config['min_volume_days'])\n    \n    # Prepare signed return components\n    df = df.copy()\n    df['ret_pos'] = np.where(df['ret'] > 0, np.abs(df['ret']), 0.0)\n    df['ret_neg'] = np.where(\n        (df['ret'] < 0) & df['ret'].notna(), np.abs(df['ret']), 0.0\n    )\n    \n    results = []\n    grouped = {t: g for t, g in df.groupby('ticker')}\n    \n    for _, cal_row in calendar.iterrows():\n        dt = cal_row['date']\n        est_s, est_e = cal_row['est_start'], cal_row['est_end']\n        \n        for ticker, tdata in grouped.items():\n            # Estimation window\n            est = tdata[\n                (tdata['date'] >= est_s) & (tdata['date'] <= est_e)\n            ].dropna(subset=['turnover', 'ret_pos', 'ret_neg'])\n            \n            if len(est) < min_obs:\n                continue\n            \n            # Event date\n            evt = tdata[tdata['date'] == dt]\n            if evt.empty or evt['turnover'].isna().all():\n                continue\n            \n            # OLS: Turn = alpha + beta_pos * RetPos + beta_neg * RetNeg\n            X = est[['ret_pos', 'ret_neg']].values\n            y = est['turnover'].values\n            \n            reg = LinearRegression().fit(X, y)\n            y_hat = reg.predict(X)\n            rmse = np.sqrt(np.mean((y - y_hat) ** 2))\n            \n            if rmse <= 0:\n                continue\n            \n            # Predict and standardize for event date\n            X_evt = evt[['ret_pos', 'ret_neg']].values\n            pred = reg.predict(X_evt)[0]\n            actual = evt['turnover'].values[0]\n            suv = (actual - pred) / rmse\n            \n            results.append({\n                'ticker': ticker, 'date': dt,\n                'suv': suv,\n                'predicted_turnover': pred,\n                'rmse_turn': rmse,\n                'n_est': len(est),\n                'alpha_turn': reg.intercept_,\n                'beta_pos': reg.coef_[0],\n                'beta_neg': reg.coef_[1],\n            })\n    \n    suv_df = pd.DataFrame(results)\n    print(f\"SUV: {len(suv_df):,} stock-date obs\")\n    print(f\"  Mean: {suv_df['suv'].mean():.4f}, \"\n          f\"Median: {suv_df['suv'].median():.4f}\")\n    return suv_df\n```\n:::\n\n\n### Diễn giải các hệ số hồi quy SUV\n\nCác hệ số ước lượng từ @eq-suv-regression cung cấp thông tin về vi cấu trúc thị trường. @garfinkel2009measuring báo cáo $\\hat{\\beta}^{+} > \\hat{\\beta}^{-}$ đối với hầu hết cổ phiếu Hoa Kỳ. Ở Việt Nam, chúng ta kỳ vọng sự bất đối xứng này còn mạnh hơn vì:\n\n-   **Không có bán khống (trước 2025):** Mọi lệnh bán đều do cổ đông hiện hữu thực hiện, làm hạn chế phản ứng của khối lượng đối với lợi nhuận âm.\n-   **Thanh toán T+2:** Nhà đầu tư không thể tái đầu tư ngay tiền bán, làm giảm thêm khối lượng bên bán.\n-   **Biên độ giá:** Biên độ hằng ngày $\\pm$ 7% (HOSE) và $\\pm$ 10% (HNX) cắt cụt phân phối lợi nhuận, nén khoảng biến thiên của cả hai biến hồi quy.\n\nCác nhà nghiên cứu nên báo cáo thống kê mô tả của $(\\hat{\\alpha}, \\hat{\\beta}^{+}, \\hat{\\beta}^{-}, R^2)$ theo mặt cắt ngang và theo thời gian.\n\n::: {#suv-diagnostics .cell execution_count=7}\n``` {.python .cell-code code-summary=\"Diagnostic statistics for SUV turnover regressions\"}\ndef suv_diagnostics(suv_df):\n    \"\"\"Report cross-sectional summary of SUV regression parameters.\"\"\"\n    print(\"\\n=== SUV Regression Diagnostics ===\")\n    \n    params = ['alpha_turn', 'beta_pos', 'beta_neg']\n    print(suv_df[params].describe(\n        percentiles=[.05, .25, .50, .75, .95]\n    ).T.to_string(float_format='{:.6f}'.format))\n    \n    # Asymmetry test\n    diff = suv_df['beta_pos'] - suv_df['beta_neg']\n    print(f\"\\nbeta_pos - beta_neg: mean = {diff.mean():.6f}, \"\n          f\"frac > 0 = {(diff > 0).mean():.3f}\")\n```\n:::\n\n\n# Các biến đại diện DIVOP dựa trên biến động {#sec-volatility}\n\n## Biến động lợi nhuận tổng {#sec-total-vol}\n\n### Động cơ lý thuyết\n\nBiến động lợi nhuận cổ phiếu đóng vai trò biến đại diện cho sự phân kỳ quan điểm qua nhiều kênh. @shalen1993volume xây dựng một mô hình trong đó cả khối lượng lẫn biến động đều tăng theo mức phân tán niềm tin của nhà đầu tư. @scheinkman2003overconfidence dự đoán rằng biến động cao hơn phản ánh thành phần giao dịch đầu cơ do các nhà đầu tư tự tin thái quá bất đồng về giá trị thúc đẩy. Về mặt thực nghiệm, @boehme2006short và @chatterjee2012takeovers dùng biến động đặc thù làm biến đại diện DIVOP và thấy nó tương quan dương với các thước đo bất đồng khác và gắn với lợi nhuận về sau thấp hơn khi các hạn chế bán khống có hiệu lực ràng buộc.\n\n### Xây dựng\n\nBiến động lợi nhuận tổng là độ lệch chuẩn của lợi nhuận hằng ngày trong cửa sổ ước lượng trượt:\n\n$$\n\\text{VOLATILITY}_{i,t} = \\sqrt{\\frac{1}{N_i - 1} \\sum_{s \\in [\\tau_1, \\tau_2]} (r_{i,s} - \\bar{r}_i)^2}\n$$ {#eq-volatility}\n\ntrong đó $N_i$ là số quan sát lợi nhuận không bị thiếu của cổ phiếu $i$ trong cửa sổ $[\\tau_1, \\tau_2]$.\n\n## Biến động đặc thù (IVOL) {#sec-ivol}\n\nBiến động đặc thù tách riêng biến thiên lợi nhuận đặc thù của doanh nghiệp bằng cách loại bỏ thành phần hệ thống được giải thích bởi biến động thị trường. Chúng ta tính IVOL từ phần dư của mô hình thị trường:\n\n$$\nr_{i,s} = \\alpha_i + \\beta_i \\cdot r_{m,s} + \\epsilon_{i,s}, \\quad s \\in [\\tau_1, \\tau_2]\n$$ {#eq-market-model}\n\n$$\n\\text{IVOL}_{i,t} = \\text{Std}(\\hat{\\epsilon}_{i,s})\n$$ {#eq-ivol}\n\nCác nhà nghiên cứu có thể mở rộng sang mô hình ba nhân tố hoặc năm nhân tố của @fama1993common bằng các danh mục nhân tố Việt Nam được xây dựng ở những phần khác trong cuốn sách này. Một mô hình nhân tố phong phú hơn cho các ước lượng IVOL tách biệt tốt hơn sự bất đồng thực sự mang tính đặc thù, với cái giá là phải xây dựng các danh mục nhân tố.\n\n::: {#volatility-construction .cell execution_count=8}\n``` {.python .cell-code code-summary=\"Construct total and idiosyncratic volatility\"}\ndef compute_volatility(df, calendar, config):\n    \"\"\"\n    Compute total return volatility and idiosyncratic volatility\n    via rolling estimation windows.\n    \n    Total vol = std(returns) in window.\n    IVOL = std(residuals) from market model regression.\n    \"\"\"\n    est_window = config['est_window']\n    min_obs = int(est_window * config['min_volume_days'])\n    \n    # Value-weighted market return\n    def _vw_ret(g):\n        valid = g.dropna(subset=['ret'])\n        if valid.empty:\n            return np.nan\n        w = valid['adj_shares_out'] * valid['close']\n        return np.average(valid['ret'], weights=w)\n    \n    mkt_ret = df.groupby('date').apply(_vw_ret).reset_index()\n    mkt_ret.columns = ['date', 'mkt_ret']\n    df = df.merge(mkt_ret, on='date', how='left')\n    \n    results = []\n    grouped = {t: g for t, g in df.groupby('ticker')}\n    \n    for _, cal_row in calendar.iterrows():\n        dt = cal_row['date']\n        est_s, est_e = cal_row['est_start'], cal_row['est_end']\n        \n        for ticker, tdata in grouped.items():\n            est = tdata[\n                (tdata['date'] >= est_s) & (tdata['date'] <= est_e)\n            ].dropna(subset=['ret', 'mkt_ret'])\n            \n            if len(est) < min_obs:\n                continue\n            \n            # Total volatility\n            total_vol = est['ret'].std()\n            \n            # Market model -> IVOL\n            X = est[['mkt_ret']].values\n            y = est['ret'].values\n            reg = LinearRegression().fit(X, y)\n            resid = y - reg.predict(X)\n            ivol = np.std(resid, ddof=1)\n            \n            results.append({\n                'ticker': ticker, 'date': dt,\n                'total_volatility': total_vol,\n                'idio_volatility': ivol,\n                'market_beta': reg.coef_[0],\n                'market_alpha': reg.intercept_,\n                'r_squared_mm': reg.score(X, y),\n                'n_vol': len(est),\n            })\n    \n    vol_df = pd.DataFrame(results)\n    print(f\"Volatility: {len(vol_df):,} stock-date obs\")\n    print(f\"  Total vol (ann. mean): \"\n          f\"{vol_df['total_volatility'].mean() * np.sqrt(252):.4f}\")\n    print(f\"  IVOL (ann. mean): \"\n          f\"{vol_df['idio_volatility'].mean() * np.sqrt(252):.4f}\")\n    return vol_df\n```\n:::\n\n\n### Những lưu ý riêng của Việt Nam đối với biến động\n\n1.  **Biên độ giá làm nén biến động đo được.** Biên độ hằng ngày $\\pm$ 7% (HOSE) và $\\pm$ 10% (HNX) cắt cụt phân phối lợi nhuận một cách cơ học, dẫn đến đánh giá thấp biến động thực. Vào các ngày chạm biên độ, lợi nhuận cân bằng thực có thể vượt lợi nhuận quan sát được. Các nhà nghiên cứu cần lưu ý rằng các thước đo DIVOP dựa trên biến động có thể bị chệch xuống đối với các cổ phiếu thường xuyên chạm biên độ.\n\n2.  **Sự tập trung của VN-Index.** VN-Index có mức độ tập trung cao, 10 cổ phiếu hàng đầu thường chiếm 50-60% trọng số chỉ số. Với các cổ phiếu vốn hóa nhỏ và vừa, lợi nhuận thị trường trọng số bằng nhau hoặc một chỉ số tổng hợp HOSE+HNX có thể cung cấp nhân tố thị trường tốt hơn trong @eq-market-model.\n\n3.  **Giao dịch thưa thớt và lợi nhuận không đồng bộ.** Với các cổ phiếu giao dịch thưa thớt, các ngày có lợi nhuận bằng không liên tiếp có thể làm giảm biến động đo được. Điều chỉnh của @dimson1979risk (đưa lợi nhuận thị trường trễ và dẫn trước vào mô hình thị trường) có thể giúp hiệu chỉnh thiên lệch giao dịch không đồng bộ trong ước lượng beta, dù tác động của nó lên IVOL thường nhỏ.\n\n# Các biến đại diện DIVOP dựa trên chênh lệch giá và thanh khoản {#sec-spread}\n\n## Chênh lệch giá mua–bán (BASPREAD) {#sec-baspread}\n\n### Động cơ lý thuyết\n\nChênh lệch giá mua–bán phản ánh chi phí lựa chọn bất lợi mà các bên cung cấp lệnh giới hạn phải gánh. Khi nhà đầu tư có niềm tin không đồng nhất, mỗi giao dịch có nhiều khả năng truyền tải thông tin riêng hơn, làm tăng thành phần lựa chọn bất lợi của chênh lệch giá. @handa2003quote chỉ ra rằng trong các thị trường dẫn dắt bởi lệnh, chênh lệch giá nới rộng khi sự phân kỳ quan điểm tăng vì các bên cung cấp lệnh giới hạn đối mặt rủi ro lớn hơn là bị các nhà giao dịch có thông tin khai thác. @chung2014simple chứng minh rằng chênh lệch giá mua–bán đóng cửa từ dữ liệu hằng ngày cung cấp xấp xỉ đáng tin cậy cho chênh lệch hiệu dụng trong ngày.\n\n### Xây dựng\n\nChúng ta tính chênh lệch giá mua–bán theo tỷ lệ bằng dữ liệu báo giá cuối ngày:\n\n$$\n\\text{BASPREAD}_{i,t} = \\frac{\\text{Ask}_{i,t} - \\text{Bid}_{i,t}}{\\text{Midpoint}_{i,t}}\n$$ {#eq-baspread}\n\ntrong đó $\\text{Midpoint}_{i,t} = (\\text{Ask}_{i,t} + \\text{Bid}_{i,t}) / 2$. Khi không có giá mua và giá bán cuối ngày, chúng ta dùng biên độ cao–thấp trong ngày làm phương án dự phòng. Theo @chung2014simple, chúng ta xóa các quan sát mà cả Bid và Ask đều bằng không, và những quan sát mà chênh lệch giá vượt quá 50% điểm giữa.\n\n## Phi thanh khoản Amihud (ILLIQ) {#sec-amihud}\n\nTỷ số @amihud2002illiquidity đo lường tác động giá của dòng lệnh:\n\n$$\n\\text{ILLIQ}_{i,t} = \\frac{|r_{i,t}|}{\\text{DolVol}_{i,t}}\n$$ {#eq-amihud}\n\ntrong đó $\\text{DolVol}_{i,t} = \\text{Volume}_{i,t} \\times \\text{Price}_{i,t}$ (tính bằng tỷ VND để thu nhỏ thang đo). ILLIQ cao hơn phản ánh bất cân xứng thông tin lớn hơn. Chúng ta lấy trung bình các tỷ số hằng ngày theo từng tháng và dùng phép biến đổi logarit vì phân phối lệch phải nặng.\n\n::: {#spread-illiq .cell execution_count=9}\n``` {.python .cell-code code-summary=\"Construct bid-ask spread and Amihud illiquidity\"}\ndef compute_spread_and_illiq(df, config):\n    \"\"\"Compute bid-ask spread (BASPREAD) and Amihud illiquidity.\"\"\"\n    df = df.copy()\n    \n    # --- Bid-Ask Spread ---\n    df['midpoint_ba'] = (df['ask'] + df['bid']) / 2\n    df['baspread_ba'] = np.where(\n        (df['ask'] > 0) & (df['bid'] > 0) & (df['midpoint_ba'] > 0),\n        (df['ask'] - df['bid']) / df['midpoint_ba'], np.nan\n    )\n    \n    # Fallback: high/low range\n    df['midpoint_hl'] = (df['high'] + df['low']) / 2\n    df['baspread_hl'] = np.where(\n        (df['high'] > 0) & (df['low'] > 0) & (df['midpoint_hl'] > 0),\n        (df['high'] - df['low']) / df['midpoint_hl'], np.nan\n    )\n    \n    df['baspread'] = df['baspread_ba'].fillna(df['baspread_hl'])\n    df['midpoint'] = df['midpoint_ba'].fillna(df['midpoint_hl'])\n    \n    # Chung & Zhang (2009) filters\n    bad = (df['baspread'].isna()) | \\\n          (df['baspread'] > config['max_spread_pct']) | \\\n          (df['baspread'] < 0)\n    df.loc[bad, 'baspread'] = np.nan\n    \n    # --- Amihud Illiquidity ---\n    df['dollar_vol'] = df['volume'] * df['close'] / 1e9\n    df['amihud_daily'] = np.where(\n        df['dollar_vol'] > 0,\n        np.abs(df['ret']) / df['dollar_vol'], np.nan\n    )\n    \n    print(f\"BASPREAD: {df['baspread'].notna().sum():,} valid obs, \"\n          f\"mean = {df['baspread'].mean():.6f}\")\n    print(f\"AMIHUD: {df['amihud_daily'].notna().sum():,} valid obs, \"\n          f\"mean = {df['amihud_daily'].mean():.6f}\")\n    return df\n\n\ndef compute_amihud_monthly(df):\n    \"\"\"Monthly Amihud = mean daily |ret|/dollar_vol (min 15 days).\"\"\"\n    df = df.copy()\n    df['ym'] = df['date'].dt.to_period('M')\n    agg = df.groupby(['ticker', 'ym']).agg(\n        illiq_mean=('amihud_daily', 'mean'),\n        n_days=('amihud_daily', 'count'),\n    ).reset_index()\n    agg = agg[agg['n_days'] >= 15].copy()\n    agg['log_illiq'] = np.log(agg['illiq_mean'] + 1e-10)\n    return agg\n```\n:::\n\n\n### Những lưu ý riêng của Việt Nam đối với chênh lệch giá và thanh khoản\n\n1.  **Biểu bước giá.** Việt Nam dùng bước giá thay đổi: 10 VND (giá \\< 10,000), 50 VND (10,000--49,950) và 100 VND (≥ 50,000) trên HOSE. Các mức này đặt ra một sàn dưới cho chênh lệch giá chào của các cổ phiếu giá thấp. Các nhà nghiên cứu cần thận trọng khi diễn giải sự biến thiên của chênh lệch giá giữa các thập phân vị giá như phản ánh sự phân kỳ quan điểm thay vì cơ chế bước giá.\n\n2.  **Cấu trúc thị trường dẫn dắt bởi lệnh.** Cả HOSE và HNX đều là các thị trường thuần dẫn dắt bởi lệnh, nơi các lệnh giới hạn công khai cung cấp thanh khoản. Điều này khiến phép xấp xỉ chênh lệch giá dựa trên CRSP của @chung2014simple là phù hợp.\n\n3.  **Yêu cầu về lô giao dịch.** HOSE yêu cầu lô chuẩn 100 cổ phiếu cho giao dịch liên tục. Với các cổ phiếu giá cao, lô chuẩn đại diện cho một cam kết vốn lớn, có thể làm phồng chênh lệch giá chào so với chi phí giao dịch hiệu dụng.\n\n4.  **Hiệu ứng đấu giá định kỳ.** Các phiên mở cửa và đóng cửa trên HOSE dùng đấu giá định kỳ, có thể tạo ra các báo giá mua–bán khác biệt đáng kể so với chênh lệch giá trong giao dịch liên tục.\n\n## Phi thanh khoản thực hiện: ILLIQ ít nhiễu hơn {#sec-divop-realized-illiq}\n\nBiến đại diện ILLIQ trong @eq-amihud tóm gọn cả một ngày biến động giá bằng một giá trị lợi nhuận tuyệt đối duy nhất. @lacava2026realized thay tử số đó bằng một ước lượng tần suất cao của chính biến thiên giá trong ngày, cho ra **Amihud thực hiện**\n\n$$\n\\text{RILLIQ}_{i,t} = \\sqrt{\\frac{2}{\\pi}}\\,\\frac{\\sqrt{\\text{RV}_{i,t}}}{\\text{DolVol}_{i,t}},\n\\qquad\n\\text{RV}_{i,t} = \\sum_{j=1}^{M} r_{i,t,j}^2\n$$ {#eq-divop-realized-illiq}\n\nvới $r_{i,t,j}$ là lợi nhuận trong ngày trên $M$ khoảng lấy mẫu và $\\sqrt{2/\\pi}$ được chọn để @eq-divop-realized-illiq nằm trên cùng thang đo với @eq-amihud. Với 45 khoảng năm phút của HOSE, sai số đo lường tương đối của tử số giảm từ khoảng 76% xuống khoảng 11%. Phần suy dẫn và các giả định của hàm ước lượng này nằm trong @sec-liquidity-realized; phần triển khai trên HOSE nằm trong @sec-micro-realized-illiq.\n\nLợi ích hiển nhiên là lợi ích chung của mọi biến đại diện DIVOP được dùng ở vế phải: một biến hồi quy sạch hơn gây thiên lệch suy giảm (attenuation) ít hơn, nên các hệ số dốc Fama-MacBeth trong @sec-applications được ước lượng gần giá trị thực hơn. Lập luận đó mang tính tổng quát và đã được nêu trong @sec-liquidity-realized.\n\nLý do chương này cần một phần xử lý riêng là một vấn đề khác và cụ thể hơn, và nó ảnh hưởng đến những kết quả mà chương này thực sự báo cáo.\n\n### Nhiễu lấy mẫu chung làm nhiễm bẩn ma trận tương quan\n\nHãy xem các biến đại diện trong chương này được xây dựng từ đâu. ILLIQ lấy $|r_{i,t}|$ từ chuỗi lợi nhuận hằng ngày. TOTVOL lấy độ lệch chuẩn của *chính chuỗi đó*. IVOL lấy độ lệch chuẩn của phần dư của nó. Khi thiếu báo giá cuối ngày, BASPREAD dùng biên độ cao–thấp trong ngày làm phương án dự phòng, lấy từ cùng các bản ghi giá hằng ngày.\n\nĐây không phải là các phép đo độc lập. Một tháng mà lợi nhuận hằng ngày của doanh nghiệp tình cờ nhận những giá trị lớn sẽ cho ILLIQ đo được cao *và* TOTVOL đo được cao *và* IVOL đo được cao, không phải vì sự phân kỳ quan điểm thực của doanh nghiệp cao, mà vì cùng một mẫu hữu hạn các lợi nhuận hằng ngày là đầu vào của cả ba. Sai số lấy mẫu là chung giữa các biến đại diện, nên nó không triệt tiêu khi chúng được đặt tương quan với nhau hoặc được kết hợp.\n\nĐiều này tác động trực tiếp đến hai việc mà chương làm. @sec-correlation báo cáo các tương quan Spearman giữa các biến đại diện DIVOP và diễn giải mô thức đó như bằng chứng về việc các biến đại diện nắm bắt những chiều nào của sự phân kỳ. @sec-empirical xây dựng một chỉ số tổng hợp bằng cách trích thành phần chính thứ nhất. Cả hai đều được tính trên cấu trúc tương quan của các biến đại diện đo được, và do đó đều hấp thụ bất kỳ tương quan nào mà các lợi nhuận hằng ngày dùng chung tạo ra.\n\nMô phỏng dưới đây tách riêng hiệu ứng này. Biến động thực và khối lượng giao dịch thực được rút **độc lập** giữa các doanh nghiệp, nên mọi tương quan vượt mức đều có thể quy cho cách xây dựng chứ không phải yếu tố kinh tế. Biến đối chứng then chốt là cột `TOTVOL (disjoint)`, tính biến động từ lợi nhuận của một tháng *khác* của cùng doanh nghiệp: nó đo cùng biến động tiềm ẩn nhưng không chia sẻ nhiễu lấy mẫu với ILLIQ, nên khoảng cách giữa nó và tương quan cùng cửa sổ thông thường chính là thành phần cơ học.\n\n::: {#divop-realized-illiq-noise .cell execution_count=10}\n`````` {.python .cell-code code-summary=\"Shared sampling noise between ILLIQ and the volatility proxies\"}\nrng_ri = np.random.default_rng(2026)\nN_SIM, D_MONTH, M_HF = 8000, 21, 45\nK_HF = np.sqrt(2 / np.pi)\n\n\ndef simulate_month(vol_dispersion):\n    \"\"\"\n    One cross-section of firm-months. True volatility and true dollar volume\n    are INDEPENDENT by construction, so any measured association between\n    illiquidity and volatility beyond sqrt(sigma)/DolVol is an artefact.\n\n    `vol_dispersion` is the cross-sectional sd of log dollar volume: wide for\n    the full market, narrow within a size decile.\n    \"\"\"\n    sigma = np.exp(rng_ri.normal(np.log(0.022), 0.35, N_SIM))\n    dvol = np.exp(rng_ri.normal(np.log(5.0), vol_dispersion, N_SIM))\n    beta = rng_ri.normal(1.0, 0.3, N_SIM)\n    mkt = rng_ri.normal(0, 0.012, (1, D_MONTH))\n\n    R = beta[:, None] * mkt + rng_ri.normal(0, 1, (N_SIM, D_MONTH)) * sigma[:, None]\n    RV = (sigma[:, None] ** 2) * rng_ri.chisquare(M_HF, (N_SIM, D_MONTH)) / M_HF\n\n    # Same firm, same true sigma, DIFFERENT month: no shared sampling noise.\n    R_alt = beta[:, None] * mkt + rng_ri.normal(0, 1, (N_SIM, D_MONTH)) * sigma[:, None]\n\n    return dict(\n        sigma=sigma,\n        illiq_true=K_HF * sigma / dvol,\n        illiq_classic=np.abs(R).mean(1) / dvol,\n        illiq_realized=K_HF * np.sqrt(RV).mean(1) / dvol,\n        totvol=R.std(1, ddof=1),\n        totvol_disjoint=R_alt.std(1, ddof=1),\n        ivol=(R - beta[:, None] * mkt).std(1, ddof=1),\n    )\n\n\ndef rho(a, b):\n    return scipy_stats.spearmanr(a, b).statistic\n\n\nrows_ri = []\nfor label, disp in [(\"full cross-section\", 0.90), (\"within size decile\", 0.30),\n                    (\"volume near-constant\", 0.10)]:\n    s = simulate_month(disp)\n    rows_ri.append({\n        \"volume dispersion\": label,\n        \"TRUE illiq vs TRUE vol\": round(rho(s[\"illiq_true\"], s[\"sigma\"]), 3),\n        \"classic vs TOTVOL\": round(rho(s[\"illiq_classic\"], s[\"totvol\"]), 3),\n        \"classic vs TOTVOL (disjoint)\": round(rho(s[\"illiq_classic\"], s[\"totvol_disjoint\"]), 3),\n        \"realized vs TOTVOL\": round(rho(s[\"illiq_realized\"], s[\"totvol\"]), 3),\n        \"fidelity: classic\": round(rho(s[\"illiq_classic\"], s[\"illiq_true\"]), 3),\n        \"fidelity: realized\": round(rho(s[\"illiq_realized\"], s[\"illiq_true\"]), 3),\n    })\n\nprint(\"Spearman correlations; true volatility and true volume are INDEPENDENT\")\nprint(pd.DataFrame(rows_ri).set_index(\"volume dispersion\").T.to_string())\n\n\ndef normal_scores(x):\n    \"\"\"Rank-based normal scores, matching the chapter's rank-correlation approach.\"\"\"\n    return scipy_stats.norm.ppf(scipy_stats.rankdata(x) / (len(x) + 1))\n\n\ns = simulate_month(0.30)\nprint(\"\\nPCA composite of (ILLIQ, TOTVOL, IVOL), within size decile:\")\nfor name, ill in [(\"classic ILLIQ\", s[\"illiq_classic\"]),\n                  (\"realized ILLIQ\", s[\"illiq_realized\"]),\n                  (\"TRUE illiquidity\", s[\"illiq_true\"])]:\n    X = np.column_stack([normal_scores(c) for c in (ill, s[\"totvol\"], s[\"ivol\"])])\n    C = np.corrcoef(X, rowvar=False)\n    ev = np.linalg.eigvalsh(C)[::-1]\n    print(f\"  {name:<17} PC1 share={ev[0] / ev.sum():.3f}   \"\n          f\"corr(ILLIQ,TOTVOL)={C[0, 1]:.3f}   corr(ILLIQ,IVOL)={C[0, 2]:.3f}\")\n``````\n\n::: {.cell-output .cell-output-stdout}\n```\nSpearman correlations; true volatility and true volume are INDEPENDENT\nvolume dispersion             full cross-section  within size decile  volume near-constant\nTRUE illiq vs TRUE vol                     0.353               0.739                 0.958\nclassic vs TOTVOL                          0.315               0.690                 0.932\nclassic vs TOTVOL (disjoint)               0.239               0.514                 0.726\nrealized vs TOTVOL                         0.295               0.609                 0.824\nfidelity: classic                          0.977               0.895                 0.862\nfidelity: realized                         1.000               0.999                 0.998\n\nPCA composite of (ILLIQ, TOTVOL, IVOL), within size decile:\n  classic ILLIQ     PC1 share=0.841   corr(ILLIQ,TOTVOL)=0.713   corr(ILLIQ,IVOL)=0.655\n  realized ILLIQ    PC1 share=0.829   corr(ILLIQ,TOTVOL)=0.628   corr(ILLIQ,IVOL)=0.685\n  TRUE illiquidity  PC1 share=0.829   corr(ILLIQ,TOTVOL)=0.629   corr(ILLIQ,IVOL)=0.686\n```\n:::\n:::\n\n\nBốn phát hiện, mỗi phát hiện có tác động trực tiếp đến cách đọc các kết quả trong @sec-correlation và @sec-empirical.\n\n**Mức thổi phồng cơ học là lớn, và lớn nhất đúng ở nơi chương này làm việc.** Trong một thập phân vị quy mô, tương quan đo được giữa ILLIQ cổ điển và TOTVOL là 0.690 khi cả hai được tính từ lợi nhuận của cùng một tháng, nhưng chỉ là 0.514 khi TOTVOL đến từ một cửa sổ tách rời. Khoảng một phần tư mối liên hệ biểu kiến là do nhiễu lấy mẫu chung tạo ra. Trong trường hợp khối lượng gần như không đổi, khoảng cách còn nới rộng hơn, từ 0.726 lên 0.932. Vì nghiên cứu DIVOP thường xuyên kiểm soát theo quy mô, và quy mô là yếu tố chi phối chính của độ phân tán của giá trị giao dịch, nên chế độ liên quan là chế độ phân tán hẹp, không phải toàn bộ mặt cắt ngang.\n\n**Thước đo thực hiện loại bỏ gần như toàn bộ.** Độ trung thực của nó đối với phi thanh khoản thực là 0.999 so với 0.895 của thước đo cổ điển trong một thập phân vị quy mô, và tương quan của nó với TOTVOL (0.609) phản ánh quan hệ thực bị suy giảm chỉ bởi sai số lấy mẫu của chính TOTVOL, không phải bởi bất kỳ thành phần chung nào.\n\n**Biến đại diện cổ điển mất lợi thế đúng ở nơi tử số phải gánh vác công việc.** Độ trung thực đối với phi thanh khoản thực giảm từ 0.977 trong toàn bộ mặt cắt ngang xuống 0.862 khi khối lượng gần như không đổi, trong khi thước đo thực hiện duy trì trên 0.998 xuyên suốt. Cách diễn giải là cách đã được dự báo trong @sec-liquidity-amihud-original: trên toàn thị trường, tỷ số cổ điển xếp hạng các cổ phiếu tốt vì *mẫu số* biến thiên rất lớn và được đo không có sai số. Hãy loại bỏ biến thiên đó bằng cách kiểm soát theo quy mô, và phần còn lại là tử số nhiễu.\n\n**Chỉ số tổng hợp PCA thừa hưởng sự nhiễm bẩn, dù ở mức khiêm tốn.** Dùng biến đại diện cổ điển, tương quan ILLIQ-TOTVOL đi vào PCA là 0.713 so với giá trị thực 0.629, và tỷ lệ phương sai của thành phần thứ nhất là 0.841 so với giá trị thực 0.829. Thay bằng thước đo thực hiện thì tái tạo gần như chính xác ma trận tương quan thực và tỷ lệ PC1 thực (0.628 và 0.829). Do đó chỉ số tổng hợp bị phóng đại nhẹ khi dùng làm bản tóm tắt biến thiên chung: nó một phần đang tóm tắt sai số đo lường chung thay vì một nhân tố phân kỳ quan điểm chung. Sự méo mó ở đây nhỏ vì chỉ một trong ba đầu vào được thay thế; một chỉ số tổng hợp được xây hoàn toàn từ các thống kê hằng ngày cùng cửa sổ sẽ tệ hơn.\n\n### Điều này có ý nghĩa gì đối với các kết quả của chương\n\nCác cách đọc thực tiễn là hẹp và đáng được nêu chính xác, vì các hiệu ứng trên là có thật nhưng không quá lớn.\n\n1.  **Các tương quan được báo cáo giữa các biến đại diện dựa trên lợi nhuận là cận trên.** Ở bất cứ nơi nào @sec-correlation cho thấy ILLIQ tương quan với TOTVOL, IVOL hoặc BASPREAD kiểu cao–thấp, một phần của tương quan đó là do cách xây dựng chứ không phải kinh tế. Các tương quan với biến đại diện được xây từ dữ liệu *khác* (DTO và SUV từ vòng quay, DISP từ dự báo của nhà phân tích) không bị ảnh hưởng bởi kênh này và có thể được hiểu theo đúng giá trị báo cáo.\n2.  **Một kiểm tra độ vững rẻ tiền không cần dữ liệu trong ngày nào.** Tính lại ma trận tương quan với các biến đại diện biến động được ước lượng trên một cửa sổ liền kề, không chồng lấn sẽ phá vỡ trực tiếp kênh nhiễu chung. Bất kỳ tương quan nào còn tồn tại không phải là sản phẩm phụ của sai số lấy mẫu chung. Đây là cột `disjoint` của mô phỏng, được triển khai trên dữ liệu thực, và chỉ tốn thêm một lệnh `shift`.\n3.  **Đừng diễn giải quá mức tỷ lệ phương sai của PC1.** Nó bị chệch lên do nhiễu chung, nên nhận định rằng một nhân tố duy nhất giải thích phần lớn biến thiên chung của các biến đại diện DIVOP có phần yếu hơn so với những gì các trị riêng thô gợi ý.\n4.  **Kiểm soát theo quy mô làm vấn đề trở nên hệ trọng hơn.** Bất kỳ đặc tả nào hoạt động trong các nhóm quy mô đều loại bỏ biến thiên khối lượng vốn mang phần lớn tín hiệu mặt cắt ngang của ILLIQ cổ điển, để lại một biến đại diện có độ trung thực đối với phi thanh khoản thực giảm xuống còn khoảng 0.86. Đây là nơi việc thay bằng @eq-divop-realized-illiq mang lại nhiều nhất.\n\n### Xây dựng\n\nBiến đại diện thực hiện là một thay thế trực tiếp cho `amihud_daily` trong `compute_spread_and_illiq()`. Nó đòi hỏi các đầu vào trong ngày có tính đến phiên giao dịch được mô tả trong @sec-micro-realized-illiq.\n\n::: {#realized-illiq-divop .cell execution_count=11}\n`````` {.python .cell-code code-summary=\"Construct realized ILLIQ as a DIVOP proxy\"}\ndef compute_realized_illiq(realized_daily, config, min_active=20):\n    \"\"\"\n    Monthly realized Amihud from a symbol-day intraday panel with columns\n    [ticker, date, rv, bv, n_active, dvol_continuous].\n\n    `min_active` screens out days whose five-minute grid is mostly stale\n    prices; below roughly 20 active intervals of 45 the estimator's precision\n    advantage largely disappears (see the microstructure chapter).\n    \"\"\"\n    k = np.sqrt(2 / np.pi)\n    df = realized_daily.copy()\n\n    n_before = len(df)\n    df = df[(df[\"n_active\"] >= min_active) & (df[\"dvol_continuous\"] > 0)]\n    print(f\"Thin-trading screen: kept {len(df):,} of {n_before:,} symbol-days \"\n          f\"({100 * len(df) / max(n_before, 1):.1f}%)\")\n\n    dvol_bn = df[\"dvol_continuous\"] / 1e9\n    df[\"rilliq_daily\"] = k * np.sqrt(df[\"rv\"]) / dvol_bn\n    df[\"rilliq_bv_daily\"] = k * np.sqrt(df[\"bv\"].clip(lower=0)) / dvol_bn\n\n    df[\"ym\"] = df[\"date\"].dt.to_period(\"M\")\n    agg = (df.groupby([\"ticker\", \"ym\"])\n             .agg(rilliq_mean=(\"rilliq_daily\", \"mean\"),\n                  rilliq_bv_mean=(\"rilliq_bv_daily\", \"mean\"),\n                  n_days=(\"rilliq_daily\", \"size\"))\n             .reset_index())\n    agg = agg[agg[\"n_days\"] >= config.get(\"min_days_per_month\", 15)].copy()\n    agg[\"log_rilliq\"] = np.log(agg[\"rilliq_mean\"] + 1e-10)\n    return agg\n\n\ndef totvol_disjoint(monthly_vol):\n    \"\"\"\n    Robustness control requiring no intraday data: pair each month's ILLIQ\n    with the PREVIOUS month's volatility, so the two share no daily returns.\n    \"\"\"\n    out = monthly_vol.sort_values([\"ticker\", \"ym\"]).copy()\n    out[\"totvol_lag\"] = out.groupby(\"ticker\")[\"totvol\"].shift(1)\n    return out\n``````\n:::\n\n\n### Những lưu ý riêng của Việt Nam\n\n1.  **Độ phủ là ràng buộc then chốt.** Dữ liệu trong ngày thực tế chỉ có cho phần thanh khoản cao của HOSE, khoảng VN30 và các doanh nghiệp vốn hóa vừa có quy mô lớn hơn. Vì bước sàng lọc loại các doanh nghiệp một cách không ngẫu nhiên đúng theo chiều đang nghiên cứu, một phân tích DIVOP giới hạn ở mẫu còn lại sẽ bị điều kiện hóa theo thanh khoản. Hãy báo cáo tỷ lệ được giữ lại.\n2.  **Dùng biến thể bipower.** Biên độ giá hằng ngày của Việt Nam khiến các biến động rời rạc lớn trở nên thường lệ, và một cú nhảy thông tin làm phồng phương sai thực hiện trong khi để biến thiên bipower gần như không chệch (@sec-liquidity-realized). Với một chương về sự phân kỳ quan điểm, điều này quan trọng hơn thường lệ, vì những ngày có nhiều bất đồng nhất cũng là những ngày dễ chạm biên độ nhất.\n3.  **Kiểm tra cửa sổ tách rời nên được chạy trong mọi trường hợp.** Nó không đòi hỏi dữ liệu nào mà chương này chưa có, nó xử lý trực tiếp sự nhiễm bẩn đã nêu ở trên, và nó áp dụng cho toàn bộ mẫu chứ không chỉ tập con thanh khoản cao.\n4.  **Mẫu số không đổi.** @eq-divop-realized-illiq chỉ cải thiện tử số; các phức tạp về giao dịch thỏa thuận và báo cáo ảnh hưởng đến DolVol, được thảo luận trong chương vi cấu trúc thị trường, áp dụng như nhau cho cả hai phiên bản.\n\n# Phân tán dự báo của nhà phân tích {#sec-analyst}\n\n## Động cơ lý thuyết\n\nPhân tán dự báo của nhà phân tích, tức độ lệch chuẩn mặt cắt ngang của các dự báo lợi nhuận của từng nhà phân tích, là thước đo trực tiếp nhất của sự phân kỳ quan điểm. Khác với các biến đại diện dựa trên thị trường nắm bắt sự bất đồng một cách gián tiếp, phân tán dự báo đo trực tiếp sự bất đồng giữa các thành viên thị trường có thông tin. @abarbanell1995analysts thiết lập cơ sở lý thuyết, và @diether2002differences chứng minh rằng các cổ phiếu có phân tán dự báo của nhà phân tích cao hơn có lợi nhuận về sau thấp hơn, phù hợp với giả thuyết định giá quá cao của Miller.\n\n## Thách thức dữ liệu ở Việt Nam\n\nViệc xây dựng phân tán dự báo của nhà phân tích ở Việt Nam đặt ra những thách thức đáng kể so với Hoa Kỳ:\n\n-   **Độ rộng của độ phủ.** Trong khi I/B/E/S phủ hơn 4,000 doanh nghiệp Hoa Kỳ, chỉ có 100--150 doanh nghiệp Việt Nam thường được ít nhất 3 nhà phân tích theo dõi, tập trung ở các cổ phiếu thành phần VN30.\n-   **Nguồn dữ liệu.** Dự báo của nhà phân tích có sẵn từ DataCore.vn, FiinPro, Bloomberg và Refinitiv. Việc chọn nguồn ảnh hưởng đến độ phủ và tính kịp thời.\n-   **Dự báo lỗi thời.** Với độ phủ hạn chế, các dự báo có thể không được sửa đổi trong nhiều tháng. Theo phương pháp I/B/E/S, chúng ta duy trì hiệu lực của mỗi dự báo tối đa 105 ngày.\n\n## Phương pháp xây dựng\n\nQuá trình xây dựng diễn ra như sau:\n\n1.  **Làm sạch các dự báo riêng lẻ.** Loại bỏ các quan sát mà ngày công bố đi trước ngày rà soát. Chỉ giữ lại các dự báo EPS hằng năm. Với mỗi cặp nhà phân tích-mã cổ phiếu-kỳ tài chính, chỉ giữ lại dự báo mới nhất trong mỗi tháng dương lịch.\n2.  **Xử lý các ước lượng bị ngừng và bị loại.** Loại bỏ các dự báo mà nhà phân tích đã rời công ty môi giới hoặc ước lượng đã bị loại khỏi đồng thuận.\n3.  **Duy trì hiệu lực dự báo có kiểm soát độ lỗi thời.** Mỗi dự báo có hiệu lực cho đến thời điểm sớm hơn trong số: (a) dự báo kế tiếp của cùng nhà phân tích, (b) 105 ngày sau ngày công bố, hoặc (c) ngày công bố lợi nhuận thực tế.\n4.  **Mở rộng sang tần suất hằng tháng.** Với mỗi cặp mã cổ phiếu-tháng, xác định mọi dự báo còn hiệu lực và tính độ phân tán.\n5.  **Tính các thước đo đã chuẩn hóa tỷ lệ:**\n\n$$\n\\text{DISP1}_{i,m} = \\frac{\\text{Std}(\\hat{\\text{EPS}}_{i,m}^{(a)})}{|\\text{Mean}(\\hat{\\text{EPS}}_{i,m}^{(a)})|}\n\\qquad\n\\text{DISP2}_{i,m} = \\frac{\\text{Std}(\\hat{\\text{EPS}}_{i,m}^{(a)})}{\\bar{P}_{i,m}}\n$$\n\n::: {#analyst-dispersion .cell execution_count=12}\n``` {.python .cell-code code-summary=\"Construct analyst forecast dispersion (DISP1, DISP2)\"}\ndef construct_analyst_dispersion(forecasts_df, price_df, config):\n    \"\"\"\n    Construct analyst forecast dispersion measures.\n    \n    Parameters\n    ----------\n    forecasts_df : pd.DataFrame\n        Individual analyst forecasts with: ticker, analyst_id, broker,\n        fpedats, anndats, revdats, value (EPS), anndats_act.\n    price_df : pd.DataFrame\n        Monthly price: ticker, month, mean_price.\n    config : dict\n        With min_analysts, forecast_carry_days.\n    \"\"\"\n    carry_days = config['forecast_carry_days']\n    min_analysts = config['min_analysts']\n    \n    df = forecasts_df.copy()\n    df = df[df['anndats'] <= df['revdats']].copy()\n    df = df.dropna(subset=['fpedats', 'anndats', 'value'])\n    \n    # Latest forecast per analyst-month\n    df['ym'] = df['anndats'].dt.to_period('M')\n    df = df.sort_values(\n        ['ticker', 'fpedats', 'analyst_id', 'ym', 'anndats', 'revdats']\n    )\n    df = df.groupby(['ticker', 'fpedats', 'analyst_id', 'ym']).tail(1)\n    \n    # Carry-forward end date\n    df = df.sort_values(\n        ['ticker', 'analyst_id', 'fpedats', 'anndats'],\n        ascending=[True, True, True, False]\n    )\n    df['next_ann'] = df.groupby(\n        ['ticker', 'analyst_id', 'fpedats']\n    )['anndats'].shift(-1)\n    \n    def _carry_end(row):\n        candidates = [row['anndats'] + pd.Timedelta(days=carry_days)]\n        if pd.notna(row.get('next_ann')):\n            candidates.append(row['next_ann'])\n        if pd.notna(row.get('anndats_act')):\n            candidates.append(row['anndats_act'])\n        return min(candidates)\n    \n    df['carry_end'] = df.apply(_carry_end, axis=1)\n    \n    # Monthly expansion\n    months = pd.period_range(config['beg_date'], config['end_date'], freq='M')\n    records = []\n    for month in months:\n        me = month.to_timestamp(how='end')\n        valid = df[(df['anndats'] <= me) & (df['carry_end'] > me)].copy()\n        valid = valid[valid['fpedats'] > me]\n        valid = valid.sort_values(['ticker', 'analyst_id', 'anndats'])\n        valid = valid.groupby(['ticker', 'analyst_id']).tail(1)\n        \n        disp = valid.groupby('ticker').agg(\n            n_analysts=('analyst_id', 'nunique'),\n            mean_fcst=('value', 'mean'),\n            std_fcst=('value', 'std'),\n        ).reset_index()\n        disp['month'] = month\n        records.append(disp)\n    \n    if not records:\n        return pd.DataFrame()\n    disp_df = pd.concat(records, ignore_index=True)\n    \n    # Scaled measures\n    disp_df['disp1'] = np.where(\n        disp_df['mean_fcst'].abs() > 0,\n        disp_df['std_fcst'] / disp_df['mean_fcst'].abs(), np.nan\n    )\n    disp_df = disp_df.merge(price_df, on=['ticker', 'month'], how='left')\n    disp_df['disp2'] = np.where(\n        disp_df['mean_price'] > 0,\n        disp_df['std_fcst'] / disp_df['mean_price'], np.nan\n    )\n    disp_df['disp_raw'] = disp_df['std_fcst']\n    \n    out = disp_df[disp_df['n_analysts'] >= min_analysts].copy()\n    print(f\"DISP: {len(out):,} ticker-months (>= {min_analysts} analysts)\")\n    print(f\"  Mean analysts: {out['n_analysts'].mean():.1f}\")\n    return out\n```\n:::\n\n\n## Các lưu ý về chuẩn hóa tỷ lệ\n\nTheo @cheong2011eps, chúng ta lưu ý rằng mỗi cách chọn chuẩn hóa tỷ lệ đều có điểm yếu. DISP1 (chuẩn hóa theo giá trị tuyệt đối của dự báo trung bình) có thể cho giá trị cực đoan khi dự báo trung bình tiến về không, điều phổ biến với các doanh nghiệp Việt Nam gần điểm hòa vốn. DISP2 (chuẩn hóa theo giá) đưa vào một tương quan âm cơ học giữa giá và độ phân tán đã chuẩn hóa. Chúng tôi khuyến nghị báo cáo cả ba phiên bản (DISP1, DISP2 và DISP_RAW không chuẩn hóa với $\\ln(\\text{Price})$ làm biến kiểm soát bổ sung), và winsorize DISP1 ở phân vị thứ 1 và thứ 99.\n\n::: callout-warning\n## Lưu ý về phân tán của nhà phân tích ở các thị trường có độ phủ mỏng\n\nVới độ phủ điển hình 5--10 nhà phân tích mỗi doanh nghiệp ở Việt Nam (so với 15--25 ở Hoa Kỳ), phân tán dự báo được ước lượng với nhiễu lớn hơn đáng kể. Một thước đo phân tán từ 3 nhà phân tích có phân phối mẫu rất khác so với thước đo từ 20 nhà phân tích. Hãy luôn đưa số nhà phân tích vào làm biến kiểm soát và kiểm tra độ vững với các ngưỡng tối thiểu số nhà phân tích khác nhau (3, 5, 7).\n:::\n\n# Tương quan mặt cắt ngang giữa các biến đại diện DIVOP {#sec-correlation}\n\nMột câu hỏi thực nghiệm quan trọng là mức độ mà các biến đại diện DIVOP khác nhau nắm bắt cùng một cấu trúc tiềm ẩn. Nếu sự phân kỳ quan điểm là một biến tiềm ẩn được xác định rõ, chúng ta kỳ vọng có các tương quan dương giữa mọi biến đại diện, dù các tương quan không nhất thiết phải cao vì mỗi biến nắm bắt một khía cạnh khác nhau của sự bất đồng.\n\n::: {#correlation-analysis .cell execution_count=13}\n``` {.python .cell-code code-summary=\"Spearman rank correlations among DIVOP proxies\"}\ndef compute_divop_correlations(merged_df, proxies=None):\n    \"\"\"\n    Compute and visualize Spearman correlations among DIVOP proxies.\n    We use rank correlations because many proxies are right-skewed.\n    \"\"\"\n    if proxies is None:\n        proxies = [\n            'dto', 'suv', 'total_volatility', 'idio_volatility',\n            'baspread', 'amihud_daily', 'disp1', 'disp2'\n        ]\n    available = [p for p in proxies if p in merged_df.columns]\n    data = merged_df[available].dropna()\n    \n    n = len(available)\n    rho_mat = np.eye(n)\n    p_mat = np.zeros((n, n))\n    for i in range(n):\n        for j in range(i + 1, n):\n            rho, p = scipy_stats.spearmanr(\n                data[available[i]], data[available[j]]\n            )\n            rho_mat[i, j] = rho_mat[j, i] = rho\n            p_mat[i, j] = p_mat[j, i] = p\n    \n    labels = {'dto': 'DTO', 'suv': 'SUV',\n              'total_volatility': 'VOL', 'idio_volatility': 'IVOL',\n              'baspread': 'SPREAD', 'amihud_daily': 'ILLIQ',\n              'disp1': 'DISP1', 'disp2': 'DISP2'}\n    pretty = [labels.get(c, c) for c in available]\n    corr_df = pd.DataFrame(rho_mat, index=pretty, columns=pretty)\n    \n    # Heatmap\n    fig, ax = plt.subplots(figsize=(9, 7))\n    mask = np.triu(np.ones_like(corr_df, dtype=bool), k=1)\n    sns.heatmap(\n        corr_df, mask=mask, annot=True, fmt='.3f',\n        cmap='RdBu_r', center=0, vmin=-0.4, vmax=0.7,\n        square=True, linewidths=0.5,\n        cbar_kws={'shrink': 0.8, 'label': 'Spearman ρ'}, ax=ax\n    )\n    ax.set_title('Spearman Correlations Among DIVOP Proxies\\n'\n                  'Vietnamese Equity Market', fontsize=13, fontweight='bold')\n    plt.tight_layout()\n    plt.savefig('divop_correlations.png', dpi=300, bbox_inches='tight')\n    plt.show()\n    \n    return corr_df\n```\n:::\n\n\n### Các mô thức tương quan kỳ vọng\n\nDựa trên bằng chứng và lý thuyết ở Hoa Kỳ, chúng ta kỳ vọng:\n\n| Cặp | Kỳ vọng | Cơ sở |\n|:-----------------------|:-----------------------|:-----------------------|\n| DTO × SUV | Dương cao | Cả hai nắm bắt khối lượng bất thường; SUV tinh chỉnh DTO |\n| VOL × IVOL | Dương cao | IVOL là tập con của biến động tổng |\n| SPREAD × ILLIQ | Dương trung bình-cao | Cả hai nắm bắt bất cân xứng thông tin |\n| Khối lượng × Biến động | Dương trung bình | @shalen1993volume liên kết cả hai với mức phân tán niềm tin |\n| Nhà phân tích × Dựa trên thị trường | Dương yếu-trung bình | Các nhóm nhà đầu tư khác nhau |\n\n: Cấu trúc tương quan kỳ vọng giữa các biến đại diện DIVOP {#tbl-expected-corr}\n\n# Thống kê mô tả và các tính chất mặt cắt ngang {#sec-empirical}\n\n## Thống kê tóm tắt\n\n::: {#descriptive-stats .cell execution_count=14}\n``` {.python .cell-code code-summary=\"Descriptive statistics for all DIVOP proxies\"}\ndef descriptive_statistics(merged_df):\n    \"\"\"Comprehensive descriptive statistics for DIVOP proxies.\"\"\"\n    proxies = {\n        'dto': 'Unexplained Volume (DTO)',\n        'suv': 'Std Unexplained Volume (SUV)',\n        'total_volatility': 'Total Return Volatility',\n        'idio_volatility': 'Idiosyncratic Volatility',\n        'baspread': 'Bid-Ask Spread',\n        'amihud_daily': 'Amihud Illiquidity',\n        'disp1': 'Analyst Disp (mean-scaled)',\n        'disp2': 'Analyst Disp (price-scaled)',\n    }\n    avail = {k: v for k, v in proxies.items() if k in merged_df.columns}\n    rows = []\n    for col, label in avail.items():\n        s = merged_df[col].dropna()\n        rows.append({\n            'Proxy': label, 'N': f'{len(s):,}',\n            'Mean': f'{s.mean():.6f}', 'Std': f'{s.std():.6f}',\n            'P5': f'{s.quantile(.05):.6f}',\n            'Median': f'{s.median():.6f}',\n            'P95': f'{s.quantile(.95):.6f}',\n            'Skew': f'{s.skew():.2f}',\n            'Kurt': f'{s.kurtosis():.2f}',\n        })\n    stats = pd.DataFrame(rows).set_index('Proxy')\n    print(\"\\n\" + \"=\" * 90)\n    print(\"Descriptive Statistics of DIVOP Proxies\")\n    print(\"Vietnamese Equity Market, HOSE and HNX\")\n    print(\"=\" * 90)\n    print(stats.to_string())\n    return stats\n```\n:::\n\n\n## DIVOP theo đặc điểm doanh nghiệp\n\n::: {#by-characteristics .cell execution_count=15}\n``` {.python .cell-code code-summary=\"DIVOP by size, exchange, and foreign ownership\"}\ndef divop_by_size(merged_df):\n    \"\"\"Mean DIVOP proxies by market-cap quintile.\"\"\"\n    df = merged_df.copy()\n    df['mkt_cap'] = df['close'] * df['shares_outstanding']\n    df['size_q'] = df.groupby('date')['mkt_cap'].transform(\n        lambda x: pd.qcut(x, 5,\n            labels=['Q1 Small','Q2','Q3','Q4','Q5 Large'],\n            duplicates='drop')\n    )\n    proxies = ['dto','suv','total_volatility','idio_volatility',\n               'baspread','amihud_daily']\n    avail = [p for p in proxies if p in df.columns]\n    tab = df.groupby('size_q')[avail].mean()\n    print(\"\\n=== Mean DIVOP by Size Quintile ===\")\n    print(tab.to_string(float_format='{:.6f}'.format))\n    return tab\n\ndef divop_by_exchange(merged_df):\n    \"\"\"Compare mean DIVOP across HOSE and HNX.\"\"\"\n    proxies = ['dto','suv','total_volatility','idio_volatility',\n               'baspread','amihud_daily']\n    avail = [p for p in proxies if p in merged_df.columns]\n    tab = merged_df.groupby('exchange')[avail].mean()\n    print(\"\\n=== Mean DIVOP by Exchange ===\")\n    print(tab.to_string(float_format='{:.6f}'.format))\n    return tab\n```\n:::\n\n\n## Diễn biến theo chuỗi thời gian\n\n::: {#time-series-plot .cell execution_count=16}\n``` {.python .cell-code code-summary=\"Time-series evolution of DIVOP proxies\"}\ndef plot_divop_timeseries(merged_df):\n    \"\"\"Plot monthly cross-sectional median DIVOP with crisis shading.\"\"\"\n    df = merged_df.copy()\n    df['ym'] = df['date'].dt.to_period('M')\n    proxies = ['dto','suv','total_volatility','baspread']\n    avail = [p for p in proxies if p in df.columns]\n    monthly = df.groupby('ym')[avail].median()\n    monthly.index = monthly.index.to_timestamp()\n    \n    fig, axes = plt.subplots(len(avail), 1,\n        figsize=(13, 3.5*len(avail)), sharex=True)\n    if len(avail) == 1: axes = [axes]\n    \n    labels = {'dto':'DTO','suv':'SUV',\n              'total_volatility':'Volatility','baspread':'Spread'}\n    colors = ['#1976D2','#388E3C','#F57C00','#D32F2F']\n    \n    for i, (proxy, ax) in enumerate(zip(avail, axes)):\n        ax.plot(monthly.index, monthly[proxy],\n                color=colors[i], linewidth=1.3)\n        ax.set_ylabel(labels.get(proxy, proxy), fontsize=10)\n        ax.grid(True, alpha=0.25)\n        for s, e, c in [('2008-01','2009-06','red'),\n                         ('2020-01','2020-12','orange'),\n                         ('2022-09','2023-06','purple')]:\n            ax.axvspan(pd.Timestamp(s), pd.Timestamp(e),\n                        alpha=0.1, color=c)\n    \n    axes[0].set_title(\n        'Time-Series of DIVOP Proxies\\n'\n        'Monthly Cross-Sectional Median, HOSE & HNX',\n        fontsize=13, fontweight='bold')\n    from matplotlib.patches import Patch\n    axes[-1].legend(handles=[\n        Patch(facecolor='red', alpha=.2, label='GFC 2008-09'),\n        Patch(facecolor='orange', alpha=.2, label='COVID-19'),\n        Patch(facecolor='purple', alpha=.2, label='Bond Crisis 2022-23'),\n    ], loc='upper right', fontsize=8)\n    plt.tight_layout()\n    plt.savefig('divop_timeseries.png', dpi=300, bbox_inches='tight')\n    plt.show()\n```\n:::\n\n\n# Tổng hợp lại {#sec-pipeline}\n\n::: {#merge-all .cell execution_count=17}\n``` {.python .cell-code code-summary=\"Master pipeline: build full DIVOP dataset\"}\ndef build_divop_dataset(config):\n    \"\"\"\n    Master pipeline: load data, construct all DIVOP proxies,\n    merge into a single stock-date panel.\n    \"\"\"\n    df = load_daily_data(config)\n    df = apply_sample_filters(df, config)\n    df = adjust_for_corporate_actions(df)\n    calendar = build_trading_calendar(df, config)\n    \n    df = compute_dto(df, config)\n    suv_df = compute_suv(df, calendar, config)\n    vol_df = compute_volatility(df, calendar, config)\n    df = compute_spread_and_illiq(df, config)\n    \n    # Merge\n    base = df[['ticker','date','ret','close','volume',\n                'shares_outstanding','exchange','industry_icb',\n                'foreign_ownership_pct','turnover',\n                'mato','dto','baspread','amihud_daily','limit_hit']].copy()\n    \n    if not suv_df.empty:\n        base = base.merge(\n            suv_df[['ticker','date','suv','predicted_turnover']],\n            on=['ticker','date'], how='left')\n    if not vol_df.empty:\n        base = base.merge(\n            vol_df[['ticker','date','total_volatility',\n                     'idio_volatility','market_beta']],\n            on=['ticker','date'], how='left')\n    \n    print(f\"\\n=== Final DIVOP Dataset ===\")\n    print(f\"Shape: {base.shape}\")\n    print(f\"Tickers: {base['ticker'].nunique()}\")\n    return base\n```\n:::\n\n\n# Các ứng dụng thực nghiệm {#sec-applications}\n\n## Ứng dụng 1: DIVOP và mặt cắt ngang của lợi nhuận\n\nPhép kiểm định cơ bản của giả thuyết Miller là liệu các cổ phiếu có sự phân kỳ quan điểm cao hơn có lợi nhuận về sau thấp hơn hay không. Chúng ta triển khai các hồi quy mặt cắt ngang Fama-MacBeth:\n\n$$\nr_{i,t+1:t+h} = \\gamma_{0,t} + \\gamma_{1,t} \\cdot \\text{DIVOP}_{i,t} + \\gamma_{2,t}' \\mathbf{X}_{i,t} + \\varepsilon_{i,t}\n$$\n\ntrong đó $\\mathbf{X}_{i,t}$ gồm các biến kiểm soát là beta thị trường, logarit vốn hóa thị trường và logarit tỷ số giá trị sổ sách trên giá trị thị trường. Giả thuyết Miller dự đoán $\\bar{\\gamma}_1 < 0$.\n\n::: {#fama-macbeth .cell execution_count=18}\n``` {.python .cell-code code-summary=\"Fama-MacBeth regressions of returns on DIVOP\"}\ndef fama_macbeth_divop(merged_df, divop_proxy='suv',\n                        controls=None, horizon=21):\n    \"\"\"\n    Fama-MacBeth cross-sectional regressions.\n    Miller predicts gamma_1 < 0; Varian predicts gamma_1 > 0.\n    \"\"\"\n    if controls is None:\n        controls = ['market_beta', 'log_mktcap']\n    \n    df = merged_df.copy()\n    df = df.sort_values(['ticker', 'date'])\n    df['fwd_ret'] = df.groupby('ticker')['ret'].transform(\n        lambda x: x.shift(-1).rolling(horizon).sum().shift(-(horizon-1))\n    )\n    df['log_mktcap'] = np.log(\n        df['close'] * df['shares_outstanding'] + 1\n    )\n    \n    reg_vars = ['fwd_ret', divop_proxy] + \\\n               [c for c in controls if c in df.columns]\n    df_reg = df[['ticker','date'] + reg_vars].dropna()\n    \n    from numpy.linalg import lstsq\n    results = []\n    for date, cross in df_reg.groupby('date'):\n        if len(cross) < 30: continue\n        y = cross['fwd_ret'].values\n        X_cols = [divop_proxy] + [c for c in controls if c in cross.columns]\n        X = np.column_stack([np.ones(len(cross)), cross[X_cols].values])\n        try:\n            coefs, _, _, _ = lstsq(X, y, rcond=None)\n            results.append({\n                'date': date, 'intercept': coefs[0],\n                f'gamma_{divop_proxy}': coefs[1], 'n': len(cross),\n            })\n        except Exception: continue\n    \n    fm = pd.DataFrame(results)\n    gc = f'gamma_{divop_proxy}'\n    mu = fm[gc].mean()\n    se = fm[gc].std() / np.sqrt(len(fm))\n    t = mu / se\n    \n    print(f\"\\n=== Fama-MacBeth: {divop_proxy} -> \"\n          f\"{horizon}-day fwd returns ===\")\n    print(f\"  Mean gamma: {mu:.6f}, t-stat: {t:.3f}\")\n    if t < -1.96:   print(\"  -> Supports Miller (1977)\")\n    elif t > 1.96:   print(\"  -> Supports Varian (1985)\")\n    else:            print(\"  -> Inconclusive at 5%\")\n    return fm\n```\n:::\n\n\n## Ứng dụng 2: DIVOP và công bố lợi nhuận\n\nTheo @berkman2009sell, chúng ta kiểm định liệu các cổ phiếu có DIVOP cao có lợi nhuận bất thường âm quanh các đợt công bố lợi nhuận hay không, vì việc giải tỏa bất định làm giảm phần bù lạc quan.\n\n::: {#ea-event .cell execution_count=19}\n``` {.python .cell-code code-summary=\"Event study: DIVOP and earnings announcement returns\"}\ndef divop_earnings_event(merged_df, ea_dates_df,\n                          divop_proxy='suv', window=(-1, 3)):\n    \"\"\"\n    Sort stocks into DIVOP quintiles pre-EA, compute CAR in window.\n    Miller predicts: Q5 (high DIVOP) has lower CAR than Q1 (low DIVOP).\n    \"\"\"\n    df = merged_df.copy()\n    ea = ea_dates_df.copy()\n    \n    # Pre-EA DIVOP value (5 days before)\n    ea['pre_date'] = ea['ea_date'] - pd.Timedelta(days=5)\n    ea = ea.merge(\n        df[['ticker','date',divop_proxy]].rename(\n            columns={'date':'pre_date'}),\n        on=['ticker','pre_date'], how='inner'\n    )\n    ea['divop_q'] = pd.qcut(\n        ea[divop_proxy], 5,\n        labels=['Q1 Low','Q2','Q3','Q4','Q5 High'],\n        duplicates='drop'\n    )\n    \n    print(f\"\\n=== EA Event Study by {divop_proxy} quintile ===\")\n    print(f\"  Window: ({window[0]}, {window[1]}) days\")\n    print(f\"  Miller predicts: Q5 has lower CAR than Q1\")\n    return ea\n```\n:::\n\n\n## Ứng dụng 3: Chỉ số DIVOP tổng hợp bằng PCA\n\nKhi cần một thước đo tóm tắt duy nhất về sự bất đồng, PCA trên bộ các biến đại diện đã chuẩn hóa sẽ trích ra \"nhân tố bất đồng\" chung.\n\n::: {#pca-composite .cell execution_count=20}\n``` {.python .cell-code code-summary=\"Composite DIVOP index via PCA\"}\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.decomposition import PCA\n\ndef composite_divop_pca(merged_df, proxies=None):\n    \"\"\"Extract first principal component from standardized DIVOP proxies.\"\"\"\n    if proxies is None:\n        proxies = ['dto','suv','total_volatility','idio_volatility',\n                   'baspread','amihud_daily']\n    avail = [p for p in proxies if p in merged_df.columns]\n    data = merged_df[['ticker','date'] + avail].dropna()\n    \n    scaler = StandardScaler()\n    X = scaler.fit_transform(data[avail])\n    \n    pca = PCA(n_components=3)\n    factors = pca.fit_transform(X)\n    data['divop_composite'] = factors[:, 0]\n    \n    # Ensure positive correlation with inputs\n    for col in avail:\n        if data['divop_composite'].corr(data[col]) < 0:\n            data['divop_composite'] *= -1\n            break\n    \n    loadings = pd.DataFrame(\n        pca.components_.T, index=avail,\n        columns=['PC1','PC2','PC3']\n    )\n    \n    print(f\"\\n=== PCA Composite DIVOP ===\")\n    print(f\"Variance explained: \"\n          f\"{pca.explained_variance_ratio_[:3].round(3)}\")\n    print(f\"\\nLoadings:\\n{loadings.to_string(float_format='{:.4f}'.format)}\")\n    return data[['ticker','date','divop_composite']], loadings\n```\n:::\n\n\n# Kết luận và khuyến nghị thực tiễn\n\nChương này đã trình bày một phương pháp toàn diện để xây dựng bảy biến đại diện riêng biệt cho sự phân kỳ quan điểm của nhà đầu tư, được điều chỉnh cho thị trường chứng khoán Việt Nam. Chúng tôi kết thúc bằng các khuyến nghị thực tiễn:\n\n**1. Ưu tiên nhiều biến đại diện.** Không có thước đo DIVOP đơn lẻ nào không có hạn chế. Chúng tôi khuyến nghị xây dựng và báo cáo kết quả cho ít nhất ba biến đại diện trải trên các kênh kinh tế khác nhau (khối lượng, biến động, chênh lệch giá hoặc dựa trên nhà phân tích).\n\n**2. Tính đến vi cấu trúc riêng của Việt Nam.** Biên độ giá hằng ngày, thanh toán T+2, các ràng buộc sở hữu nước ngoài và cấu trúc thị trường dẫn dắt bởi lệnh đều ảnh hưởng đến các tính chất của DIVOP. Hãy đánh dấu các ngày chạm biên độ, đưa vào hiệu ứng cố định theo sàn, và kiểm soát sở hữu nước ngoài.\n\n**3. Việt Nam như một phòng thí nghiệm tự nhiên cho Miller (1977).** Việc không có bán khống đến hết năm 2024 và sự áp đảo của nhà đầu tư cá nhân tạo ra những điều kiện khớp sát với bối cảnh lý thuyết của Miller. Việc đưa vào bán khống năm 2025 tạo ra một thử nghiệm tự nhiên để xem xét việc nới lỏng các hạn chế bán khống ảnh hưởng thế nào đến quan hệ DIVOP-lợi nhuận.\n\n**4. Kiểm soát độ phủ nhà phân tích khi dùng các thước đo DISP.** Với độ phủ điển hình 5--10 nhà phân tích mỗi doanh nghiệp, phân tán dự báo được ước lượng với nhiễu lớn hơn so với các thị trường phát triển. Hãy luôn đưa số nhà phân tích vào làm biến kiểm soát và thực hiện các kiểm tra độ vững với các ngưỡng tối thiểu số nhà phân tích khác nhau.\n\n**5. Cân nhắc xây dựng chỉ số tổng hợp.** Khi các nhà nghiên cứu cần một thước đo tóm tắt duy nhất về sự bất đồng, chỉ số tổng hợp dựa trên PCA được mô tả trong @sec-applications cung cấp một cách tiếp cận có nguyên tắc để tổng hợp thông tin qua các biến đại diện riêng lẻ. Thành phần chính thứ nhất thường giải thích 30-50% biến thiên chung trong bộ các thước đo DIVOP.\n\n**6. Winsorize mạnh tay.** Một số biến đại diện DIVOP (đặc biệt là DISP1, ILLIQ Amihud và SUV) có các giá trị ngoại lai cực đoan trong dữ liệu Việt Nam. Winsorization ở phân vị thứ 1 và thứ 99 (hoặc thậm chí thứ 2 và thứ 98 đối với DISP1) là thiết yếu để thu được kết quả hồi quy đáng tin cậy.\n\n**7. Thận trọng với suy luận nhân quả.** Các biến đại diện DIVOP là nội sinh, chúng phản ứng với cùng những đặc điểm doanh nghiệp (quy mô, đòn bẩy, tăng trưởng) vốn cũng ảnh hưởng đến lợi nhuận. Các nhà nghiên cứu nên dùng các biến kiểm soát phù hợp, cân nhắc biến công cụ khi khả thi, và nêu rõ các hạn chế của chiến lược nhận diện của mình.\n\nKhung DIVOP đặc biệt phù hợp với thị trường Việt Nam ở giai đoạn phát triển hiện nay. Khi thị trường trưởng thành hướng tới khả năng được nâng hạng lên nhóm Thị trường mới nổi của FTSE, khi bán khống trở nên phổ biến hơn, và khi sự tham gia của nhà đầu tư tổ chức tăng lên, động lực của sự phân kỳ quan điểm và các hàm ý định giá của nó nhiều khả năng sẽ thay đổi đáng kể. Phương pháp được trình bày trong chương này trang bị cho các nhà nghiên cứu những công cụ để ghi nhận và phân tích các thay đổi đó khi chúng diễn ra.\n\n",
    "supporting": [
      "39_divop_files\\figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}