{
  "hash": "20c6d89e497db0628d8dbecca422cf9d",
  "result": {
    "engine": "jupyter",
    "markdown": "# Chất lượng và thời điểm công bố thông tin\n\nCông bố thông tin doanh nghiệp là cơ chế chính để các công ty giao tiếp với thị trường vốn. Chất lượng, khối lượng và thời điểm công bố thông tin định hình môi trường thông tin, trong đó nhà đầu tư hình thành kỳ vọng, định giá chứng khoán và phân bổ vốn. Một nền văn liệu lý thuyết và thực nghiệm đồ sộ, được tổng quan bởi @healy2001information và @beyer2010financial, cho thấy các quyết định công bố thông tin có tác động bậc nhất lên chi phí vốn, thanh khoản và hiệu quả đầu tư.\n\nChương này đưa hai thập kỷ nghiên cứu về công bố thông tin vào thị trường Việt Nam, nơi một số đặc điểm thể chế tạo nên bối cảnh đặc thù. Thứ nhất, khung pháp lý của Việt Nam, dựa trên Thông tư 155/2015/TT-BTC (được sửa đổi bởi Thông tư 96/2020/TT-BTC) và được Ủy ban Chứng khoán Nhà nước (SSC) giám sát thực thi, quy định các nghĩa vụ công bố định kỳ và theo sự kiện với thời hạn cụ thể khác với chuẩn mực của Hoa Kỳ và châu Âu. Thứ hai, sự thống trị của nhà đầu tư cá nhân và mức độ phủ sóng tương đối mỏng của các nhà phân tích khiến thông tin do doanh nghiệp công bố thường là nguồn thông tin *chủ yếu* về riêng từng doanh nghiệp, làm tăng tầm quan trọng kinh tế của chúng. Thứ ba, quá trình chuyển đổi đang diễn ra từ Chuẩn mực Kế toán Việt Nam (VAS) sang hội tụ với IFRS đưa vào những thay đổi theo thời gian đối với yêu cầu công bố thông tin, tạo ra biến thiên tự nhiên cho phân tích thực nghiệm.\n\n## Nền tảng lý thuyết {#sec-dis-qual-theory}\n\n### Lý thuyết công bố thông tin tự nguyện\n\nMô hình nền tảng về công bố thông tin tự nguyện thuộc về @verrecchia1983discretionary, người chỉ ra rằng khi nhà đầu tư biết nhà quản lý nắm giữ thông tin riêng, một trạng thái cân bằng *bóc tách* (unraveling) xuất hiện: sự im lặng bị diễn giải là tin xấu, nên nhà quản lý sẽ công bố trừ khi chi phí độc quyền thông tin (proprietary cost) của việc công bố vượt quá lợi ích. Điểm mấu chốt là việc không công bố cũng mang thông tin, vì nhà đầu tư suy luận một cách hợp lý rằng thông tin bị giữ lại là bất lợi.\n\n@diamond1985optimal mở rộng phân tích sang bối cảnh nhiều thời kỳ, trong đó chính sách công bố thông tin của doanh nghiệp ảnh hưởng đến độ chính xác của thông tin công khai và do đó ảnh hưởng đến động cơ thu thập thông tin riêng. Sự đánh đổi trung tâm là giữa việc giảm bất cân xứng thông tin (làm giảm chi phí vốn) và việc giảm các khoản đặc lợi mà nhà giao dịch có thông tin kiếm được (có thể làm nản lòng hoạt động giám sát). @diamond1991disclosure chính thức hóa mối liên hệ giữa công bố thông tin và thanh khoản: bằng cách giảm lựa chọn đối nghịch, công bố thông tin tự nguyện thu hẹp chênh lệch giá mua–bán và làm tăng mức sẵn lòng giao dịch của nhà đầu tư không có thông tin.\n\nDự báo thực nghiệm là các doanh nghiệp có chất lượng công bố thông tin cao hơn sẽ được hưởng:\n\n1.  Chi phí vốn cổ phần thấp hơn [@botosan1997disclosure; @botosan2002re]\n2.  Chi phí nợ thấp hơn [@sengupta1998corporate]\n3.  Thanh khoản cao hơn và chênh lệch giá mua–bán thấp hơn [@diamond1991disclosure; @lang2012transparency]\n4.  Các quyết định đầu tư hiệu quả hơn [@biddle2009does]\n\n### Thời điểm công bố thông tin mang tính chiến lược\n\nKhông phải mọi thông tin công bố đều tự nguyện về thời điểm, nhưng nhà quản lý vẫn giữ quyền tùy nghi về việc *khi nào* công bố trong các khung thời gian cho phép. @patell1982good ghi nhận rằng các doanh nghiệp có xu hướng công bố tin tốt trong giờ giao dịch và tin xấu sau khi thị trường đóng cửa. @dellavigna2009investor chỉ ra rằng lợi nhuận được công bố vào thứ Sáu (tức là khi sự chú ý của nhà đầu tư thấp hơn) tạo ra phản ứng tức thời nhỏ hơn và hiện tượng trôi dạt sau thông báo lớn hơn, phù hợp với giả thuyết chú ý hạn chế. @hirshleifer2009driven khái quát hóa phát hiện này: các sự kiện không liên quan làm phân tán nhà đầu tư (chẳng hạn một số lượng lớn thông báo diễn ra đồng thời) làm giảm phản ứng giá tức thời đối với tin tức lợi nhuận.\n\nỞ Việt Nam, một số đặc điểm khiến việc chọn thời điểm chiến lược đặc biệt đáng chú ý. Lịch công bố thông tin tập trung, khi nhiều doanh nghiệp nộp hồ sơ sát hạn quy định, tạo ra biến thiên tự nhiên về mức độ ùn tắc thông báo. Cơ sở nhà đầu tư do cá nhân chi phối có thể dễ chịu tác động của hiệu ứng chú ý hơn nhà đầu tư tổ chức. Cấu trúc quy định, vốn áp dụng chế tài đối với việc nộp muộn nhưng cho phép tùy nghi trong khung thời gian cho phép, tạo ra bối cảnh trong đó *việc lựa chọn* ngày nộp hồ sơ tự nó mang thông tin.\n\n### Chất lượng công bố thông tin tại các thị trường mới nổi\n\n@ball2003incentives lập luận rằng chất lượng kế toán được định hình bởi *động cơ* lập báo cáo nhiều hơn là bởi *chuẩn mực* kế toán. Trong các môi trường thể chế có thực thi yếu, sở hữu tập trung và báo cáo tài chính gắn chặt với báo cáo thuế, doanh nghiệp có thể tạo ra thông tin công bố chất lượng thấp hơn ngay cả khi chuẩn mực danh nghĩa là nghiêm ngặt. @leuz2003earnings xác nhận mô hình này trên phạm vi quốc tế: quản trị lợi nhuận (một thước đo thay thế đảo ngược của chất lượng công bố thông tin) cao nhất ở các quốc gia có bảo vệ nhà đầu tư yếu, sở hữu tập trung và thị trường vốn kém phát triển.\n\nViệt Nam thể hiện một số đặc điểm này. @bushman2004financial phân loại các yếu tố quyết định tính minh bạch thành các yếu tố quản trị (nguồn gốc hệ thống pháp luật, hiệu quả tư pháp, bảo vệ cổ đông thiểu số) và các yếu tố chính trị (sở hữu nhà nước, sự can thiệp của chính phủ). Truyền thống luật thành văn của Việt Nam, sở hữu nhà nước đáng kể trong các doanh nghiệp niêm yết và năng lực thực thi đang phát triển cho thấy chất lượng công bố thông tin về trung bình có thể thấp hơn so với các thị trường phát triển, nhưng có biến thiên đáng kể giữa các doanh nghiệp do cấu trúc quản trị và sở hữu ở cấp doanh nghiệp.\n\n## Khung pháp lý {#sec-dis-qual-regulation}\n\n### Các yêu cầu công bố thông tin bắt buộc\n\nQuy định về công bố thông tin của Việt Nam vận hành thông qua một hệ thống thứ bậc các văn bản pháp lý:\n\n-   **Luật Chứng khoán (2019):** Thiết lập nghĩa vụ chung của các doanh nghiệp niêm yết là công bố thông tin trung thực, chính xác, đầy đủ và kịp thời (Điều 118).\n-   **Thông tư 155/2015/TT-BTC** (được sửa đổi bởi **Thông tư 96/2020/TT-BTC**): Quy định nội dung, định dạng và thời hạn đối với các lần công bố định kỳ và theo sự kiện.\n-   **Các quyết định và hướng dẫn của SSC:** Cung cấp chi tiết triển khai và các yêu cầu theo từng ngành.\n\nCác thời hạn báo cáo định kỳ chính được nêu trong @tbl-dis-qual-deadlines\n\n| Loại báo cáo | Thời hạn | Yêu cầu kiểm toán |\n|------------------------|------------------------|------------------------|\n| Báo cáo tài chính năm | 90 ngày sau khi kết thúc năm tài chính | Được kiểm toán |\n| Báo cáo tài chính bán niên | 45 ngày sau khi kết thúc kỳ | Được soát xét |\n| Báo cáo tài chính quý | 20 ngày sau khi kết thúc quý | Chưa kiểm toán |\n| Báo cáo thường niên | 110 ngày sau khi kết thúc năm tài chính | Không áp dụng (tường thuật) |\n\n: Thời hạn công bố thông tin định kỳ theo quy định chứng khoán của Việt Nam. {#tbl-dis-qual-deadlines}\n\nThông tin công bố theo sự kiện (bất thường) phải được nộp trong vòng 24 giờ đối với các sự kiện trọng yếu, bao gồm thay đổi sở hữu vượt quá 1% của các cổ đông lớn, nghị quyết của hội đồng quản trị về cổ tức hoặc tăng vốn, và bất kỳ sự kiện nào có thể ảnh hưởng đáng kể đến giá cổ phiếu.\n\n### Chế tài đối với hành vi không tuân thủ\n\nSSC có thể áp dụng phạt hành chính đối với việc công bố thông tin muộn hoặc không đầy đủ, thường từ 50–100 triệu VND đối với vi phạm nhẹ và lên đến 500 triệu VND đối với các thiếu sót trọng yếu. Mặc dù các khoản tiền này khá nhỏ so với quy mô của các công ty vốn hóa lớn, chi phí danh tiếng và rủi ro bị đình chỉ giao dịch tạo thêm sức răn đe.\n\n## Xây dựng dữ liệu {#sec-dis-qual-data}\n\n### Nạp các thư viện cần thiết\n\n::: {#setup .cell execution_count=1}\n``` {.python .cell-code code-summary=\"Import libraries and configure environment\"}\nimport pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nimport statsmodels.api as sm\nimport statsmodels.formula.api as smf\nfrom datetime import datetime, timedelta\nfrom scipy import stats\nfrom sklearn.preprocessing import StandardScaler\nfrom linearmodels.panel import PanelOLS\nimport warnings\nwarnings.filterwarnings('ignore')\n\n# Plotting defaults\nplt.rcParams.update({\n    'figure.figsize': (10, 6),\n    'figure.dpi': 150,\n    'font.size': 11,\n    'axes.spines.top': False,\n    'axes.spines.right': False\n})\n```\n:::\n\n\n### Truy xuất dữ liệu công bố thông tin\n\nChúng ta giả định rằng mình có dữ liệu có cấu trúc về ngày nộp hồ sơ, dấu thời gian thông báo và nội dung văn bản của các thông tin công bố của doanh nghiệp đối với tất cả các công ty.\n\n::: {#data-load .cell execution_count=2}\n``` {.python .cell-code code-summary=\"Load disclosure and financial data\"}\nfrom datacore import DataCoreClient\n\nclient = DataCoreClient()\n\n# Filing metadata: announcement dates, filing dates, report types\nfilings = client.get_filings(\n    exchanges=['HOSE', 'HNX'],\n    report_types=['annual', 'semi_annual', 'quarterly'],\n    start_date='2012-01-01',\n    end_date='2024-12-31',\n    fields=[\n        'ticker', 'report_type', 'fiscal_year', 'fiscal_quarter',\n        'fiscal_year_end', 'filing_date', 'announcement_date',\n        'auditor', 'audit_opinion', 'file_url'\n    ]\n)\n\n# Financial statement data\nfinancials = client.get_fundamentals(\n    exchanges=['HOSE', 'HNX'],\n    start_date='2012-01-01',\n    end_date='2024-12-31',\n    fields=[\n        'ticker', 'fiscal_year', 'fiscal_quarter',\n        'total_assets', 'total_equity', 'revenue', 'net_income',\n        'operating_cash_flow', 'total_accruals',\n        'market_cap', 'book_to_market'\n    ]\n)\n\n# Daily trading data for event studies\ntrading = client.get_daily_prices(\n    exchanges=['HOSE', 'HNX'],\n    start_date='2012-01-01',\n    end_date='2024-12-31',\n    fields=[\n        'ticker', 'date', 'close', 'volume', 'turnover',\n        'bid_ask_spread', 'market_return'\n    ]\n)\n\n# Ownership and governance\ngovernance = client.get_governance(\n    exchanges=['HOSE', 'HNX'],\n    fields=[\n        'ticker', 'fiscal_year', 'state_ownership_pct',\n        'foreign_ownership_pct', 'board_size',\n        'board_independence_pct', 'big4_auditor',\n        'dual_listing'\n    ]\n)\n\nprint(f\"Filings: {filings.shape[0]:,} records\")\nprint(f\"Financials: {financials.shape[0]:,} records\")\nprint(f\"Trading: {trading.shape[0]:,} records\")\nprint(f\"Governance: {governance.shape[0]:,} records\")\n```\n:::\n\n\n### Tính độ kịp thời của việc nộp hồ sơ {#sec-dis-qual-timeliness}\n\nChúng ta định nghĩa **độ trễ báo cáo** là số ngày theo lịch giữa ngày kết thúc kỳ tài chính và ngày báo cáo tài chính của doanh nghiệp được công bố công khai. Đối với báo cáo năm, mức tối đa theo quy định là 90 ngày; các doanh nghiệp nộp sớm hơn thời hạn sẽ tiết lộ thông tin sớm hơn, trong khi các doanh nghiệp nộp muộn đối mặt với khả năng bị phạt và phát đi tín hiệu về những khó khăn có thể có trong sổ sách của mình.\n\n::: {#compute-lag .cell execution_count=3}\n``` {.python .cell-code code-summary=\"Compute reporting lag for each filing\"}\nfilings['fiscal_year_end'] = pd.to_datetime(filings['fiscal_year_end'])\nfilings['filing_date'] = pd.to_datetime(filings['filing_date'])\nfilings['announcement_date'] = pd.to_datetime(filings['announcement_date'])\n\n# Reporting lag = filing date - fiscal period end\nfilings['reporting_lag'] = (\n    filings['filing_date'] - filings['fiscal_year_end']\n).dt.days\n\n# Regulatory deadline based on report type\ndeadline_map = {\n    'annual': 90,\n    'semi_annual': 45,\n    'quarterly': 20\n}\nfilings['deadline_days'] = filings['report_type'].map(deadline_map)\n\n# Late filing indicator\nfilings['late_filing'] = (\n    filings['reporting_lag'] > filings['deadline_days']\n).astype(int)\n\n# Days relative to deadline (negative = early, positive = late)\nfilings['days_relative_deadline'] = (\n    filings['reporting_lag'] - filings['deadline_days']\n)\n\n# Summary statistics\nannual_filings = filings[filings['report_type'] == 'annual'].copy()\nprint(\"Annual Report Filing Lag (calendar days):\")\nprint(annual_filings['reporting_lag'].describe().round(1))\nprint(f\"\\nLate filing rate: {annual_filings['late_filing'].mean():.1%}\")\n```\n:::\n\n\n### Phân phối độ trễ nộp hồ sơ\n\n::: {#fig-filing-lag-dist .cell execution_count=4}\n``` {.python .cell-code code-summary=\"Plot the distribution of annual report filing lags\"}\nfig, axes = plt.subplots(1, 2, figsize=(14, 5))\n\n# Histogram\naxes[0].hist(\n    annual_filings['reporting_lag'].dropna(),\n    bins=60, range=(20, 150),\n    color='#2C5F8A', edgecolor='white', alpha=0.85\n)\naxes[0].axvline(x=90, color='#C0392B', linestyle='--', linewidth=2,\n                label='90-day deadline')\naxes[0].set_xlabel('Reporting Lag (Calendar Days)')\naxes[0].set_ylabel('Number of Filings')\naxes[0].set_title('Distribution of Annual Report Filing Lags')\naxes[0].legend()\n\n# Time trend: median lag by year\nmedian_lag = (\n    annual_filings\n    .groupby('fiscal_year')['reporting_lag']\n    .agg(['median', lambda x: x.quantile(0.25),\n          lambda x: x.quantile(0.75)])\n)\nmedian_lag.columns = ['median', 'p25', 'p75']\n\naxes[1].fill_between(\n    median_lag.index, median_lag['p25'], median_lag['p75'],\n    alpha=0.3, color='#2C5F8A', label='IQR'\n)\naxes[1].plot(\n    median_lag.index, median_lag['median'],\n    color='#2C5F8A', linewidth=2, marker='o', label='Median'\n)\naxes[1].axhline(y=90, color='#C0392B', linestyle='--',\n                linewidth=1.5, label='Deadline')\naxes[1].set_xlabel('Fiscal Year')\naxes[1].set_ylabel('Filing Lag (Calendar Days)')\naxes[1].set_title('Median Annual Filing Lag Over Time')\naxes[1].legend()\n\nplt.tight_layout()\nplt.show()\n```\n:::\n\n\n## Đo lường chất lượng công bố thông tin {#sec-dis-qual-quality}\n\nChất lượng công bố thông tin vốn có tính đa chiều. Theo @dechow2010understanding và @beyer2010financial, chúng ta xây dựng các thước đo thay thế theo bốn chiều: (i) tính kịp thời, (ii) đặc tính văn bản, (iii) chất lượng kế toán, và (iv) độ rộng của công bố thông tin tự nguyện.\n\n### Tính kịp thời như một chiều của chất lượng\n\nCông bố kịp thời làm giảm thời gian tồn tại bất cân xứng thông tin giữa người trong cuộc và nhà đầu tư bên ngoài. @chambers1984timeliness và @givoly1982timeliness xác lập rằng các doanh nghiệp báo cáo sớm có xu hướng công bố tin tốt, trong khi các doanh nghiệp báo cáo muộn thường đưa ra tin xấu nhiều hơn. Chúng ta kiểm tra mô hình này trong bối cảnh Việt Nam ở phần dưới đây.\n\nChúng ta thao tác hóa tính kịp thời qua hai thước đo:\n\n1.  **Độ trễ báo cáo** (liên tục): Số ngày theo lịch từ ngày kết thúc kỳ tài chính đến ngày nộp hồ sơ, được xây dựng như trong @sec-dis-qual-timeliness.\n2.  **Phân loại sớm/muộn** (phân loại): Chúng ta phân loại các quan sát doanh nghiệp–năm thành các nhóm tam phân vị dựa trên độ trễ báo cáo trong từng năm tài chính. Cách làm này kiểm soát các xu hướng dài hạn về tốc độ nộp hồ sơ (ví dụ do thay đổi quy định hoặc gián đoạn vì COVID-19).\n\n::: {#timeliness-terciles .cell execution_count=5}\n``` {.python .cell-code code-summary=\"Classify filings into timeliness terciles\"}\nannual_filings['lag_tercile'] = (\n    annual_filings\n    .groupby('fiscal_year')['reporting_lag']\n    .transform(lambda x: pd.qcut(x, 3, labels=['Early', 'Middle', 'Late']))\n)\n\n# Tabulate\ntercile_stats = (\n    annual_filings\n    .groupby('lag_tercile')['reporting_lag']\n    .agg(['count', 'mean', 'median', 'std'])\n    .round(1)\n)\ntercile_stats.columns = ['N', 'Mean Lag', 'Median Lag', 'SD']\nprint(tercile_stats)\n```\n:::\n\n\n### Các thước đo chất lượng văn bản {#sec-dis-qual-textual}\n\nCác đặc tính văn bản của thông tin công bố doanh nghiệp truyền tải thông tin về chất lượng vượt ra ngoài những gì các con số kế toán đơn thuần nắm bắt được. @li2008annual chứng minh rằng các báo cáo năm khó đọc hơn gắn với tính bền vững lợi nhuận thấp hơn, cho thấy ngôn ngữ phức tạp có thể che giấu thông tin bất lợi. @loughran2014measuring phê phán việc áp dụng các công thức đo mức độ dễ đọc thông dụng (chỉ số Fog, Flesch-Kincaid) cho văn bản tài chính, lập luận rằng các thước đo này lẫn lộn độ phức tạp với thuật ngữ chuyên môn.\n\nChúng ta xây dựng ba thước đo chất lượng văn bản được điều chỉnh cho thông tin công bố của doanh nghiệp Việt Nam:\n\n#### Độ dài và tính cụ thể của tài liệu\n\nThông tin công bố dài hơn không nhất thiết tốt hơn, vì độ dài có thể phản ánh văn bản mẫu rập khuôn hoặc sự làm mờ. Tuy nhiên, @dyer2017evolution chỉ ra rằng thành phần *có thông tin* của việc công bố (khác với ngôn ngữ pháp lý tiêu chuẩn) đã tăng theo thời gian trong các báo cáo 10-K của Hoa Kỳ. Chúng ta đo lường:\n\n-   **Tổng số từ:** Độ dài thô của các phần tường thuật trong báo cáo năm (tương đương MD&A)\n-   **Mật độ số liệu:** Tỷ lệ các token là số, tỷ lệ phần trăm hoặc giá trị tiền tệ, là thước đo thay thế cho tính cụ thể.\n\n::: {#textual-measures .cell execution_count=6}\n``` {.python .cell-code code-summary=\"Compute textual disclosure quality measures\"}\nimport re\nfrom underthesea import word_tokenize\n\ndef compute_textual_metrics(text):\n    \"\"\"Compute textual quality metrics for Vietnamese corporate text.\"\"\"\n    if not text or len(text.strip()) == 0:\n        return {\n            'word_count': 0, 'sentence_count': 0,\n            'numerical_density': 0, 'avg_sentence_length': 0,\n            'unique_word_ratio': 0, 'forward_looking_density': 0\n        }\n\n    # Vietnamese word segmentation\n    tokens = word_tokenize(text)\n    sentences = re.split(r'[.!?。]', text)\n    sentences = [s.strip() for s in sentences if len(s.strip()) > 5]\n\n    word_count = len(tokens)\n    sentence_count = max(len(sentences), 1)\n\n    # Numerical density: proportion of tokens that are numeric\n    num_pattern = re.compile(r'^[\\d,.%]+$')\n    numeric_tokens = sum(1 for t in tokens if num_pattern.match(t))\n    numerical_density = numeric_tokens / max(word_count, 1)\n\n    # Lexical diversity: unique words / total words\n    unique_words = len(set(t.lower() for t in tokens))\n    unique_word_ratio = unique_words / max(word_count, 1)\n\n    # Forward-looking statement density\n    forward_keywords = [\n        'dự kiến', 'kế hoạch', 'mục tiêu', 'triển vọng',\n        'định hướng', 'chiến lược', 'tương lai', 'sẽ',\n        'dự báo', 'phấn đấu', 'cam kết', 'hướng tới'\n    ]\n    text_lower = text.lower()\n    forward_count = sum(text_lower.count(kw) for kw in forward_keywords)\n    forward_looking_density = forward_count / max(sentence_count, 1)\n\n    return {\n        'word_count': word_count,\n        'sentence_count': sentence_count,\n        'numerical_density': numerical_density,\n        'avg_sentence_length': word_count / sentence_count,\n        'unique_word_ratio': unique_word_ratio,\n        'forward_looking_density': forward_looking_density\n    }\n\n# Retrieve annual report text from DataCore\nannual_text = client.get_annual_report_text(\n    exchanges=['HOSE', 'HNX'],\n    start_date='2012-01-01',\n    end_date='2024-12-31',\n    sections=['mda', 'business_overview', 'risk_factors']\n)\n\n# Apply textual metrics\ntextual_metrics = annual_text.apply(\n    lambda row: compute_textual_metrics(row['text']),\n    axis=1, result_type='expand'\n)\nannual_text = pd.concat([annual_text, textual_metrics], axis=1)\n\nprint(\"Textual Quality Summary Statistics:\")\nprint(annual_text[['word_count', 'numerical_density',\n                    'avg_sentence_length', 'unique_word_ratio',\n                    'forward_looking_density']].describe().round(3))\n```\n:::\n\n\n#### Mật độ các phát biểu hướng tới tương lai\n\nForward-looking statements reveal management's expectations about future performance and are considered a higher-quality form of disclosure because they expose the manager to ex-post evaluation. In Vietnamese reports, forward-looking language typically appears in the form of phrases like *dự kiến* (expected), *kế hoạch* (plan), *mục tiêu* (target), and *triển vọng* (outlook).\n\n@guay2016guiding chỉ ra rằng nhà quản lý dùng công bố thông tin tự nguyện để \"dẫn đường xuyên màn sương\" khi báo cáo tài chính phức tạp. Chúng ta thao tác hóa mật độ hướng tới tương lai là số cụm từ hướng tới tương lai trên mỗi câu, theo cách tiếp cận từ khóa trong hàm `compute_textual_metrics` ở trên.\n\n### Các thước đo chất lượng dựa trên kế toán {#sec-dis-qual-accruals-quality}\n\nChúng ta bổ sung các thước đo văn bản bằng các thước đo thay thế dựa trên kế toán, nắm bắt độ tin cậy của thông tin tài chính được báo cáo.\n\n#### Chất lượng các khoản dồn tích\n\nTheo @francis2005market, chúng ta đo chất lượng các khoản dồn tích bằng độ lệch chuẩn của phần dư từ hồi quy các khoản dồn tích vốn lưu động theo dòng tiền hoạt động trong quá khứ, hiện tại và tương lai:\n\n$$\n\\frac{WC_{i,t}}{A_{i,t-1}} = \\alpha + \\beta_1 \\frac{CFO_{i,t-1}}{A_{i,t-1}} + \\beta_2 \\frac{CFO_{i,t}}{A_{i,t-1}} + \\beta_3 \\frac{CFO_{i,t+1}}{A_{i,t-1}} + \\varepsilon_{i,t}\n$$ {#eq-accruals-quality}\n\ntrong đó $WC_{i,t}$ là các khoản dồn tích vốn lưu động, $CFO_{i,t}$ là dòng tiền hoạt động, và $A_{i,t-1}$ là tổng tài sản trễ một kỳ. Độ lệch chuẩn cấp doanh nghiệp của $\\hat{\\varepsilon}_{i,t}$ trên một cửa sổ trượt (thường là 5 năm) là thước đo chất lượng các khoản dồn tích, với giá trị càng cao cho thấy chất lượng càng thấp.\n\n::: {#accruals-quality .cell execution_count=7}\n``` {.python .cell-code code-summary=\"Estimate accruals quality (Dechow-Dichev residual volatility)\"}\ndef estimate_accruals_quality(df, min_obs=5):\n    \"\"\"\n    Estimate accruals quality as std dev of DD residuals\n    over a rolling 5-year window for each firm.\n    \"\"\"\n    results = []\n\n    for ticker, group in df.groupby('ticker'):\n        group = group.sort_values('fiscal_year')\n\n        # Construct leads/lags of CFO\n        group['cfo_lag1'] = group['operating_cash_flow'].shift(1)\n        group['cfo_lead1'] = group['operating_cash_flow'].shift(-1)\n\n        # Scale by lagged assets\n        group['lag_assets'] = group['total_assets'].shift(1)\n        for col in ['total_accruals', 'operating_cash_flow',\n                     'cfo_lag1', 'cfo_lead1']:\n            group[f'{col}_scaled'] = group[col] / group['lag_assets']\n\n        # Rolling 5-year residual std dev\n        for idx in range(len(group)):\n            window = group.iloc[max(0, idx - 4):idx + 1]\n            window = window.dropna(subset=[\n                'total_accruals_scaled', 'operating_cash_flow_scaled',\n                'cfo_lag1_scaled', 'cfo_lead1_scaled'\n            ])\n\n            if len(window) >= min_obs:\n                y = window['total_accruals_scaled']\n                X = sm.add_constant(window[[\n                    'cfo_lag1_scaled',\n                    'operating_cash_flow_scaled',\n                    'cfo_lead1_scaled'\n                ]])\n                try:\n                    model = sm.OLS(y, X).fit()\n                    results.append({\n                        'ticker': ticker,\n                        'fiscal_year': group.iloc[idx]['fiscal_year'],\n                        'accruals_quality': model.resid.std()\n                    })\n                except Exception:\n                    pass\n\n    return pd.DataFrame(results)\n\naq_df = estimate_accruals_quality(financials)\nprint(f\"Accruals quality computed for {aq_df['ticker'].nunique()} firms\")\nprint(aq_df['accruals_quality'].describe().round(4))\n```\n:::\n\n\n#### Tính bền vững và khả năng dự báo của lợi nhuận\n\nLợi nhuận bền vững hữu ích hơn cho định giá. Chúng ta ước lượng tính bền vững của lợi nhuận bằng hệ số góc $\\phi_1$ từ một mô hình tự hồi quy bậc nhất:\n\n$$\n\\frac{E_{i,t}}{A_{i,t-1}} = \\phi_0 + \\phi_1 \\frac{E_{i,t-1}}{A_{i,t-2}} + \\nu_{i,t}\n$$ {#eq-persistence}\n\n$\\hat{\\phi}_1$ càng cao cho thấy lợi nhuận càng bền vững (và có thể cho là chất lượng càng cao).\n\n::: {#earnings-persistence .cell execution_count=8}\n``` {.python .cell-code code-summary=\"Estimate firm-level earnings persistence\"}\ndef estimate_persistence(df, min_obs=5):\n    \"\"\"Estimate earnings persistence via AR(1) model.\"\"\"\n    results = []\n\n    for ticker, group in df.groupby('ticker'):\n        group = group.sort_values('fiscal_year')\n        group['earnings_scaled'] = group['net_income'] / group['total_assets'].shift(1)\n        group['earnings_lag'] = group['earnings_scaled'].shift(1)\n\n        clean = group.dropna(subset=['earnings_scaled', 'earnings_lag'])\n        if len(clean) >= min_obs:\n            y = clean['earnings_scaled']\n            X = sm.add_constant(clean[['earnings_lag']])\n            model = sm.OLS(y, X).fit()\n            results.append({\n                'ticker': ticker,\n                'persistence': model.params['earnings_lag'],\n                'persistence_se': model.bse['earnings_lag'],\n                'r_squared': model.rsquared,\n                'n_obs': model.nobs\n            })\n\n    return pd.DataFrame(results)\n\npersistence_df = estimate_persistence(financials)\nprint(persistence_df[['persistence', 'r_squared']].describe().round(3))\n```\n:::\n\n\n### Chỉ số tổng hợp về chất lượng công bố thông tin {#sec-dis-qual-composite}\n\nMỗi thước đo chất lượng riêng lẻ nắm bắt một khía cạnh khác nhau của môi trường thông tin. Để tổng hợp chúng thành một điểm số duy nhất mà tránh được việc đặt trọng số tùy tiện, chúng ta theo @lang1993cross và sử dụng một chỉ số tổng hợp dựa trên thứ hạng. Với mỗi quan sát doanh nghiệp–năm, chúng ta xếp hạng các doanh nghiệp theo từng chiều sau (thứ hạng cao hơn = chất lượng cao hơn) (@tbl-dis-qual-composite).\n\n| Chiều            | Thước đo thay thế     | Hướng             |\n|------------------|-----------------------|-------------------|\n| Tính kịp thời    | Độ trễ báo cáo        | Thấp hơn thì tốt hơn |\n| Tính cụ thể      | Mật độ số liệu        | Cao hơn thì tốt hơn |\n| Hướng tới tương lai | Mật độ FLS         | Cao hơn thì tốt hơn |\n| Chất lượng lợi nhuận | Chất lượng dồn tích (DD) | σ thấp hơn thì tốt hơn |\n| Tính bền vững    | Hệ số AR(1)           | Cao hơn thì tốt hơn |\n\n: Các thành phần của chỉ số tổng hợp về chất lượng công bố thông tin. {#tbl-dis-qual-composite}\n\nChúng ta chuyển mỗi thước đo thay thế thành thứ hạng phân vị trong từng năm tài chính (để mỗi thành phần nằm trong khoảng từ 0 đến 1), rồi lấy trung bình qua các thành phần:\n\n$$\nDQ_{i,t} = \\frac{1}{K} \\sum_{k=1}^{K} \\text{Rank}_{k,i,t}\n$$ {#eq-dq-index}\n\ntrong đó $K$ là số thành phần có sẵn và $\\text{Rank}_{k,i,t}$ là thứ hạng phân vị của doanh nghiệp $i$ trong năm $t$ theo chiều $k$.\n\n::: {#composite-index .cell execution_count=9}\n``` {.python .cell-code code-summary=\"Construct composite disclosure quality index\"}\n# Merge all quality proxies\nquality_panel = (\n    annual_filings[['ticker', 'fiscal_year', 'reporting_lag']]\n    .merge(\n        annual_text[['ticker', 'fiscal_year', 'numerical_density',\n                      'forward_looking_density']],\n        on=['ticker', 'fiscal_year'], how='left'\n    )\n    .merge(aq_df, on=['ticker', 'fiscal_year'], how='left')\n    .merge(persistence_df[['ticker', 'persistence']],\n           on='ticker', how='left')\n)\n\n# Rank each component within fiscal year (higher = better quality)\ndef year_percentile_rank(series):\n    \"\"\"Convert to percentile rank within group.\"\"\"\n    return series.rank(pct=True)\n\nrank_cols = {}\nfor col, ascending in [\n    ('reporting_lag', False),       # lower lag = better → invert\n    ('numerical_density', True),    # higher = better\n    ('forward_looking_density', True),\n    ('accruals_quality', False),    # lower volatility = better → invert\n    ('persistence', True)           # higher = better\n]:\n    col_to_rank = quality_panel[col] if ascending else -quality_panel[col]\n    rank_cols[f'rank_{col}'] = (\n        quality_panel\n        .groupby('fiscal_year')[col]\n        .transform(lambda x: x.rank(pct=True) if ascending\n                   else (-x).rank(pct=True))\n    )\n\nrank_df = pd.DataFrame(rank_cols)\nquality_panel = pd.concat([quality_panel, rank_df], axis=1)\n\n# Composite index: average of available ranks\nrank_columns = [c for c in quality_panel.columns if c.startswith('rank_')]\nquality_panel['dq_index'] = quality_panel[rank_columns].mean(axis=1)\n\nprint(\"Disclosure Quality Index Distribution:\")\nprint(quality_panel['dq_index'].describe().round(3))\n```\n:::\n\n\n::: {#fig-dq-distribution .cell execution_count=10}\n``` {.python .cell-code code-summary=\"Plot distribution of composite disclosure quality index\"}\nfig, ax = plt.subplots(figsize=(10, 5))\nax.hist(quality_panel['dq_index'].dropna(), bins=50,\n        color='#2C5F8A', edgecolor='white', alpha=0.85)\nax.axvline(quality_panel['dq_index'].median(), color='#E67E22',\n           linestyle='--', linewidth=2, label='Median')\nax.set_xlabel('Disclosure Quality Index')\nax.set_ylabel('Number of Firm-Years')\nax.set_title('Distribution of Composite Disclosure Quality')\nax.legend()\nplt.tight_layout()\nplt.show()\n```\n:::\n\n\n## Các yếu tố quyết định chất lượng công bố thông tin {#sec-dis-qual-determinants}\n\nĐiều gì thúc đẩy sự khác biệt về chất lượng công bố thông tin giữa các doanh nghiệp Việt Nam? Chúng ta ước lượng một hồi quy chéo của chỉ số DQ tổng hợp theo các đặc điểm doanh nghiệp và các biến quản trị:\n\n$$\nDQ_{i,t} = \\alpha + \\beta_1 \\ln(\\text{Size}_{i,t}) + \\beta_2 \\text{ROA}_{i,t} + \\beta_3 \\text{Lev}_{i,t} + \\beta_4 \\text{StateOwn}_{i,t} + \\beta_5 \\text{ForeignOwn}_{i,t} + \\beta_6 \\text{Big4}_{i,t} + \\beta_7 \\text{BoardIndep}_{i,t} + \\gamma_t + \\varepsilon_{i,t}\n$$ {#eq-determinants}\n\ntrong đó $\\gamma_t$ là các hiệu ứng cố định theo năm.\n\nCác dự báo lý thuyết, dựa trên @lang1993cross, @hope2003disclosure và @bushman2004financial, là:\n\n-   **Quy mô (+):** Các doanh nghiệp lớn hơn chịu sự giám sát công chúng lớn hơn và có chi phí độc quyền thông tin thấp hơn so với lợi ích của việc công bố thông tin.\n-   **ROA (+/−):** Các doanh nghiệp có lợi nhuận cao có thể công bố nhiều hơn để phát tín hiệu chất lượng, nhưng các doanh nghiệp điều chỉnh lợi nhuận giảm xuống (vì mục đích thuế) có thể giảm công bố để tránh bị soi xét.\n-   **Đòn bẩy (+):** @sengupta1998corporate lập luận rằng các doanh nghiệp có nhiều nợ hơn có động cơ mạnh hơn để duy trì chất lượng công bố thông tin nhằm giảm chi phí vay.\n-   **Sở hữu nhà nước (−):** Các doanh nghiệp nhà nước (SOE) có thể chịu kỷ luật thị trường yếu hơn và có động cơ chính trị để hạn chế tính minh bạch.\n-   **Sở hữu nước ngoài (+):** Các nhà đầu tư tổ chức nước ngoài đòi hỏi tính minh bạch cao hơn.\n-   **Công ty kiểm toán Big 4 (+):** Các công ty kiểm toán chất lượng cao hạn chế quản trị lợi nhuận và gián tiếp cải thiện chất lượng công bố thông tin.\n-   **Tính độc lập của hội đồng quản trị (+):** Các thành viên độc lập cải thiện việc giám sát và khuyến khích công bố thông tin hữu ích hơn.\n\n::: {#determinants-regression .cell execution_count=11}\n``` {.python .cell-code code-summary=\"Estimate determinants of disclosure quality\"}\n# Merge quality index with financials and governance\ndet_panel = (\n    quality_panel[['ticker', 'fiscal_year', 'dq_index']]\n    .merge(financials, on=['ticker', 'fiscal_year'], how='left')\n    .merge(governance, on=['ticker', 'fiscal_year'], how='left')\n)\n\n# Construct variables\ndet_panel['log_size'] = np.log(det_panel['total_assets'])\ndet_panel['roa'] = det_panel['net_income'] / det_panel['total_assets']\ndet_panel['leverage'] = (\n    (det_panel['total_assets'] - det_panel['total_equity'])\n    / det_panel['total_assets']\n)\n\n# Panel regression with year FE\ndet_panel = det_panel.set_index(['ticker', 'fiscal_year'])\n\nmodel_det = PanelOLS(\n    dependent=det_panel['dq_index'],\n    exog=sm.add_constant(det_panel[[\n        'log_size', 'roa', 'leverage',\n        'state_ownership_pct', 'foreign_ownership_pct',\n        'big4_auditor', 'board_independence_pct'\n    ]]),\n    entity_effects=False,\n    time_effects=True,\n    check_rank=False\n).fit(cov_type='clustered', cluster_entity=True)\n\nprint(model_det.summary)\n```\n:::\n\n\n::: {#fig-determinants-coefficients .cell execution_count=12}\n``` {.python .cell-code code-summary=\"Visualize determinant regression coefficients\"}\ncoefs = model_det.params.drop('const')\nci = model_det.conf_int().drop('const')\n\nfig, ax = plt.subplots(figsize=(8, 5))\ny_pos = range(len(coefs))\nlabels = [\n    'ln(Assets)', 'ROA', 'Leverage', 'State Own %',\n    'Foreign Own %', 'Big 4 Auditor', 'Board Indep %'\n]\n\ncolors = ['#2C5F8A' if c > 0 else '#C0392B' for c in coefs.values]\nax.barh(y_pos, coefs.values, color=colors, alpha=0.8, height=0.6)\nax.errorbar(\n    coefs.values, y_pos,\n    xerr=[coefs.values - ci.iloc[:, 0].values,\n          ci.iloc[:, 1].values - coefs.values],\n    fmt='none', color='black', capsize=3\n)\nax.axvline(x=0, color='gray', linewidth=0.8, linestyle='-')\nax.set_yticks(y_pos)\nax.set_yticklabels(labels)\nax.set_xlabel('Coefficient Estimate')\nax.set_title('Determinants of Disclosure Quality')\nplt.tight_layout()\nplt.show()\n```\n:::\n\n\n## Thời điểm công bố thông tin mang tính chiến lược {#sec-dis-qual-strategic-timing}\n\n### Hiệu ứng ngày trong tuần\n\n@dellavigna2009investor ghi nhận rằng các thông báo lợi nhuận vào thứ Sáu nhận được ít sự chú ý tức thời của thị trường hơn. Chúng ta kiểm tra xem mô hình này có đúng ở Việt Nam hay không, nơi tuần giao dịch kéo dài từ thứ Hai đến thứ Sáu nhưng cơ sở nhà đầu tư do cá nhân chi phối có thể thể hiện các mô hình chú ý khác.\n\n::: {#day-of-week .cell execution_count=13}\n``` {.python .cell-code code-summary=\"Analyze day-of-week patterns in earnings announcements\"}\nannual_filings['announcement_dow'] = (\n    annual_filings['announcement_date'].dt.dayofweek\n)\nannual_filings['day_name'] = (\n    annual_filings['announcement_date'].dt.day_name()\n)\n\n# Compute surprise: actual earnings minus naive expectation (last year's earnings)\nannual_filings = annual_filings.merge(\n    financials[['ticker', 'fiscal_year', 'net_income', 'total_assets']],\n    on=['ticker', 'fiscal_year'], how='left'\n)\nannual_filings['earnings_scaled'] = (\n    annual_filings['net_income'] / annual_filings['total_assets']\n)\nannual_filings['earnings_surprise'] = (\n    annual_filings\n    .groupby('ticker')['earnings_scaled']\n    .diff()\n)\n\n# Classify as good/bad news\nannual_filings['bad_news'] = (\n    annual_filings['earnings_surprise'] < 0\n).astype(int)\n\n# Day-of-week distribution by news type\ndow_crosstab = pd.crosstab(\n    annual_filings['day_name'],\n    annual_filings['bad_news'].map({0: 'Good News', 1: 'Bad News'}),\n    normalize='columns'\n)\n# Reorder days\nday_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']\ndow_crosstab = dow_crosstab.reindex(day_order)\n\nprint(\"Proportion of Announcements by Day and News Type:\")\nprint(dow_crosstab.round(3))\n```\n:::\n\n\n::: {#fig-dow-pattern .cell execution_count=14}\n``` {.python .cell-code code-summary=\"Plot day-of-week announcement patterns\"}\nfig, ax = plt.subplots(figsize=(10, 5))\nx = np.arange(len(day_order))\nwidth = 0.35\n\nbad_pct = dow_crosstab['Bad News'].values\ngood_pct = dow_crosstab['Good News'].values\n\nax.bar(x - width/2, good_pct, width, label='Good News',\n       color='#27AE60', alpha=0.8)\nax.bar(x + width/2, bad_pct, width, label='Bad News',\n       color='#C0392B', alpha=0.8)\nax.set_xticks(x)\nax.set_xticklabels(day_order)\nax.set_ylabel('Proportion of Announcements')\nax.set_title('Strategic Timing: Day-of-Week Announcement Patterns')\nax.legend()\nplt.tight_layout()\nplt.show()\n```\n:::\n\n\n### Sự ùn tắc thông báo\n\nKhi nhiều doanh nghiệp thông báo cùng một ngày, mỗi thông báo nhận được ít sự chú ý hơn. Chúng ta đo **mức ùn tắc thông báo** bằng số doanh nghiệp khác công bố lợi nhuận vào cùng ngày:\n\n$$\n\\text{Congestion}_{i,t} = \\sum_{j \\neq i} \\mathbf{1}\\{\\text{AnnDate}_{j} = \\text{AnnDate}_{i}\\}\n$$ {#eq-congestion}\n\n@hirshleifer2009driven dự báo rằng các doanh nghiệp chôn tin xấu sẽ chọn những ngày ùn tắc cao. Chúng ta kiểm tra điều này bằng cách hồi quy biến ùn tắc theo dấu của tin tức lợi nhuận:\n\n::: {#congestion-analysis .cell execution_count=15}\n``` {.python .cell-code code-summary=\"Test whether bad-news firms choose high-congestion announcement days\"}\n# Count announcements per date\nann_counts = (\n    annual_filings\n    .groupby('announcement_date')\n    .size()\n    .reset_index(name='n_announcements')\n)\nannual_filings = annual_filings.merge(\n    ann_counts, on='announcement_date', how='left'\n)\nannual_filings['congestion'] = annual_filings['n_announcements'] - 1\n\n# Regression: congestion ~ bad_news + controls\ncongestion_model = smf.ols(\n    'congestion ~ bad_news + log_size + roa + C(fiscal_year)',\n    data=annual_filings.assign(\n        log_size=np.log(annual_filings['total_assets']),\n        roa=annual_filings['net_income'] / annual_filings['total_assets']\n    )\n).fit(cov_type='cluster', cov_kwds={'groups': annual_filings['ticker']})\n\nprint(\"Congestion Regression:\")\nprint(congestion_model.summary().tables[1])\n```\n:::\n\n\n### Thông báo ngoài giờ và cuối tuần\n\nQuy định của Việt Nam yêu cầu công bố trong vòng 24 giờ kể từ các sự kiện trọng yếu, nhưng doanh nghiệp vẫn có quyền tùy nghi về thời điểm chính xác. Các thông báo được đưa ra sau khi phiên giao dịch kết thúc (sau 3:00 chiều trên HOSE/HNX) hoặc vào cuối tuần làm chậm cơ hội phản ứng của thị trường ít nhất một ngày giao dịch.\n\n::: {#after-hours .cell execution_count=16}\n``` {.python .cell-code code-summary=\"Identify and analyze after-hours announcement patterns\"}\n# Assume announcement timestamps are available\nannual_filings['ann_hour'] = (\n    annual_filings['announcement_date'].dt.hour\n)\nannual_filings['after_hours'] = (\n    (annual_filings['ann_hour'] >= 15) |\n    (annual_filings['announcement_dow'] >= 5)  # Saturday/Sunday\n).astype(int)\n\n# Cross-tabulate after-hours by news type\nafterhours_crosstab = pd.crosstab(\n    annual_filings['after_hours'].map({0: 'During Hours', 1: 'After Hours'}),\n    annual_filings['bad_news'].map({0: 'Good News', 1: 'Bad News'}),\n    normalize='index'\n)\nprint(\"News Distribution by Announcement Timing:\")\nprint(afterhours_crosstab.round(3))\n\n# Chi-squared test\ncontingency = pd.crosstab(\n    annual_filings['after_hours'], annual_filings['bad_news']\n)\nchi2, p_val, _, _ = stats.chi2_contingency(contingency)\nprint(f\"\\nChi-squared = {chi2:.2f}, p-value = {p_val:.4f}\")\n```\n:::\n\n\n## Hệ quả thị trường của chất lượng công bố thông tin {#sec-dis-qual-consequences}\n\n### Chất lượng công bố thông tin và chi phí vốn cổ phần\n\nDự báo trung tâm của @diamond1991disclosure và @botosan1997disclosure là công bố thông tin chất lượng cao hơn làm giảm chi phí vốn cổ phần bằng cách giảm bất cân xứng thông tin. Chúng ta kiểm tra điều này bằng cách tiếp cận chi phí vốn ngụ ý (ICC), trong đó chúng ta ước lượng tỷ lệ chiết khấu làm cho giá hiện tại bằng giá trị hiện tại của lợi nhuận kỳ vọng trong tương lai.\n\nChúng ta dùng cách tiếp cận tỷ số PEG làm ước tính ICC đơn giản:\n\n$$\nr_{PEG,i,t} = \\sqrt{\\frac{\\hat{E}_{i,t+2} - \\hat{E}_{i,t+1}}{P_{i,t}}}\n$$ {#eq-icc}\n\ntrong đó $\\hat{E}_{i,t+k}$ là dự báo lợi nhuận đồng thuận (hoặc, khi không có nhà phân tích theo dõi, là dự báo dựa trên mô hình) và $P_{i,t}$ là giá cổ phiếu hiện tại.\n\n::: {#cost-of-equity .cell execution_count=17}\n``` {.python .cell-code code-summary=\"Estimate implied cost of equity and test disclosure quality effect\"}\n# Construct earnings forecasts using a simple random walk with drift\nforecasts = financials.sort_values(['ticker', 'fiscal_year']).copy()\nforecasts['eps'] = forecasts['net_income'] / forecasts['market_cap']\nforecasts['eps_growth'] = forecasts.groupby('ticker')['eps'].pct_change()\n\n# Simple forecast: E[t+1] = E[t] * (1 + avg_growth)\nforecasts['avg_growth'] = (\n    forecasts.groupby('ticker')['eps_growth']\n    .transform(lambda x: x.rolling(3, min_periods=2).mean())\n)\nforecasts['eps_f1'] = forecasts['eps'] * (1 + forecasts['avg_growth'])\nforecasts['eps_f2'] = forecasts['eps_f1'] * (1 + forecasts['avg_growth'])\n\n# PEG-based ICC\nforecasts['icc_peg'] = np.sqrt(\n    np.maximum(forecasts['eps_f2'] - forecasts['eps_f1'], 0)\n    / np.maximum(forecasts['market_cap'] / 1e6, 1e-6)\n)\n\n# Merge with disclosure quality\nicc_panel = (\n    forecasts[['ticker', 'fiscal_year', 'icc_peg']]\n    .merge(quality_panel[['ticker', 'fiscal_year', 'dq_index']].reset_index(drop=True),\n           on=['ticker', 'fiscal_year'], how='inner')\n    .merge(governance, on=['ticker', 'fiscal_year'], how='left')\n    .merge(financials[['ticker', 'fiscal_year', 'total_assets',\n                        'book_to_market', 'market_cap']],\n           on=['ticker', 'fiscal_year'], how='left')\n)\n\nicc_panel['log_size'] = np.log(icc_panel['market_cap'])\nicc_panel = icc_panel.set_index(['ticker', 'fiscal_year'])\n\n# Panel regression: ICC ~ DQ + controls\nicc_model = PanelOLS(\n    dependent=icc_panel['icc_peg'],\n    exog=sm.add_constant(icc_panel[[\n        'dq_index', 'log_size', 'book_to_market'\n    ]]),\n    entity_effects=True,\n    time_effects=True,\n    check_rank=False\n).fit(cov_type='clustered', cluster_entity=True)\n\nprint(\"Implied Cost of Capital ~ Disclosure Quality:\")\nprint(icc_model.summary)\n```\n:::\n\n\n### Chất lượng công bố thông tin và thanh khoản\n\n@diamond1991disclosure dự báo rằng công bố thông tin tốt hơn làm giảm lựa chọn đối nghịch và cải thiện thanh khoản. Chúng ta đo thanh khoản qua chênh lệch giá mua–bán và tỷ số phi thanh khoản Amihud:\n\n$$\n\\text{Amihud}_{i,t} = \\frac{1}{D_{i,t}} \\sum_{d=1}^{D_{i,t}} \\frac{|R_{i,d}|}{\\text{Volume}_{i,d}}\n$$ {#eq-amihud}\n\ntrong đó $R_{i,d}$ là lợi nhuận hằng ngày và $\\text{Volume}_{i,d}$ là khối lượng giao dịch hằng ngày tính bằng VND.\n\n::: {#liquidity-analysis .cell execution_count=18}\n``` {.python .cell-code code-summary=\"Compute Amihud illiquidity and test disclosure quality effect\"}\n# Compute annual Amihud illiquidity\ntrading['abs_return'] = trading['close'].pct_change().abs()\ntrading['amihud_daily'] = trading['abs_return'] / (trading['volume'] * trading['close'])\n\namihud_annual = (\n    trading\n    .assign(fiscal_year=trading['date'].dt.year)\n    .groupby(['ticker', 'fiscal_year'])\n    .agg(\n        amihud=('amihud_daily', 'mean'),\n        avg_spread=('bid_ask_spread', 'mean'),\n        avg_turnover=('turnover', 'mean')\n    )\n    .reset_index()\n)\n\n# Log transform for better distributional properties\namihud_annual['log_amihud'] = np.log(amihud_annual['amihud'] + 1e-10)\namihud_annual['log_spread'] = np.log(amihud_annual['avg_spread'] + 1e-6)\n\n# Merge and run regression\nliq_panel = (\n    amihud_annual\n    .merge(quality_panel[['ticker', 'fiscal_year', 'dq_index']].reset_index(drop=True),\n           on=['ticker', 'fiscal_year'], how='inner')\n    .merge(financials[['ticker', 'fiscal_year', 'market_cap', 'total_assets']],\n           on=['ticker', 'fiscal_year'], how='left')\n)\nliq_panel['log_size'] = np.log(liq_panel['market_cap'])\nliq_panel = liq_panel.set_index(['ticker', 'fiscal_year'])\n\nliq_model = PanelOLS(\n    dependent=liq_panel['log_amihud'],\n    exog=sm.add_constant(liq_panel[['dq_index', 'log_size']]),\n    entity_effects=True,\n    time_effects=True,\n    check_rank=False\n).fit(cov_type='clustered', cluster_entity=True)\n\nprint(\"Amihud Illiquidity ~ Disclosure Quality:\")\nprint(liq_model.summary)\n```\n:::\n\n\n::: {#fig-dq-liquidity .cell execution_count=19}\n``` {.python .cell-code code-summary=\"Plot disclosure quality vs liquidity relationship\"}\nliq_panel_plot = liq_panel.reset_index()\nliq_panel_plot['dq_quintile'] = pd.qcut(\n    liq_panel_plot['dq_index'], 5, labels=['Q1\\n(Low)', 'Q2', 'Q3', 'Q4', 'Q5\\n(High)']\n)\n\nquintile_liq = (\n    liq_panel_plot\n    .groupby('dq_quintile')['log_amihud']\n    .agg(['mean', 'sem'])\n)\n\nfig, ax = plt.subplots(figsize=(8, 5))\nbars = ax.bar(\n    range(5), quintile_liq['mean'],\n    yerr=1.96 * quintile_liq['sem'],\n    color=['#C0392B', '#E67E22', '#F1C40F', '#27AE60', '#2C5F8A'],\n    alpha=0.85, capsize=4, edgecolor='white'\n)\nax.set_xticks(range(5))\nax.set_xticklabels(quintile_liq.index)\nax.set_xlabel('Disclosure Quality Quintile')\nax.set_ylabel('Log Amihud Illiquidity')\nax.set_title('Disclosure Quality and Market Liquidity')\nplt.tight_layout()\nplt.show()\n```\n:::\n\n\n#### Sai số đo lường trong biến kết quả thanh khoản {#sec-dq-realized-illiq}\n\n@eq-amihud dùng một lợi nhuận tuyệt đối hằng ngày duy nhất để tóm tắt toàn bộ biến động giá trong một ngày. Như đã trình bày chi tiết trong chương về thanh khoản (@sec-liquidity-realized), tử số đó mang sai số đo lường tương đối khoảng 76% mỗi ngày, và @lacava2026realized chỉ ra rằng có thể thay nó bằng một ước lượng tần suất cao của cùng đại lượng đó, gọi là **Amihud thực hiện** (realized Amihud),\n\n$$\n\\text{RAmihud}_{i,t} = \\frac{1}{D_{i,t}}\\sum_{d=1}^{D_{i,t}}\n\\sqrt{\\frac{2}{\\pi}}\\,\\frac{\\sqrt{\\text{RV}_{i,d}}}{\\text{Volume}_{i,d}},\n\\qquad\n\\text{RV}_{i,d} = \\sum_{j=1}^{M} r_{i,d,j}^2\n$$ {#eq-dq-realized-amihud}\n\ntrong đó $r_{i,d,j}$ là các lợi nhuận trong ngày và hằng số $\\sqrt{2/\\pi}$ giữ cho @eq-dq-realized-amihud cùng thang đo với @eq-amihud. Với $M = 45$ khoảng thời gian năm phút của HOSE, sai số tương đối của tử số giảm từ khoảng 76% xuống khoảng 11%.\n\nNgười ta dễ kết luận rằng đặc tả này do đó đánh giá thấp tác động của chất lượng công bố thông tin. **Không phải vậy, và lý do đáng được nêu chính xác, bởi vì kinh tế lượng ở đây khác về căn bản với ứng dụng phân loại danh mục trong chương về thanh khoản.** Ở đó, phi thanh khoản là biến sắp xếp ở vế phải, và sai số đo lường làm suy giảm phần bù ước lượng về phía không. Ở đây, phi thanh khoản là biến *phụ thuộc*. Viết biến kết quả đo được là giá trị thật cộng nhiễu, $\\widehat{y}_i = y_i + \\nu_i$, hồi quy $\\widehat{y}_i = \\alpha + \\beta\\,\\text{DQ}_i + (\\varepsilon_i + \\nu_i)$ có hệ số góc không đổi theo kỳ vọng với điều kiện $\\nu_i$ không tương quan với $\\text{DQ}_i$. Sai số đo lường cổ điển trong biến kết quả làm mất *độ chính xác*, chứ không làm mất tính vững [@hausman2001mismeasured]. Do đó, thước đo thực hiện mang lại sức mạnh thống kê trong chương này, chứ không phải hiệu chỉnh thiên lệch.\n\nHai câu hỏi đặt ra. Sức mạnh thống kê tăng bao nhiêu, và điều kiện \"không tương quan với $\\text{DQ}$\" có thực sự được thỏa mãn ở đây không?\n\n#### Nơi nó hầu như không quan trọng: đặc tả theo năm\n\nHồi quy ở trên lấy trung bình các tỷ số hằng ngày trong cả năm tài chính. Chính việc lấy trung bình đã khắc chế sai số đo lường: trên $D$ ngày, sai số tương đối của tử số Amihud giảm xuống $0.7555/\\sqrt{D}$, với một doanh nghiệp có thanh khoản tốt và 250 ngày giao dịch thì dưới 5%, đã đủ nhỏ để việc giảm thêm một nửa nữa thay đổi rất ít.\n\nTuy nhiên, có một kênh mà qua đó đặc tả theo năm có thể bị thiên lệch, và kênh này gắn riêng với phép biến đổi log mà chương này áp dụng. Vì $\\log$ là hàm lõm, $\\mathbb{E}[\\log \\widehat{y}] < \\log \\mathbb{E}[\\widehat{y}]$, và độ lớn của khoảng cách Jensen đó xấp xỉ $-\\tfrac{1}{2}\\,\\text{relvar}/D$. Do đó nó *thay đổi giữa các doanh nghiệp theo $D_{i,t}$*. Các doanh nghiệp giao dịch ít ngày chịu méo mó hướng xuống lớn hơn trong $\\log(\\text{Amihud})$ so với các doanh nghiệp giao dịch mỗi ngày. Vì các doanh nghiệp giao dịch thưa thớt cũng chiếm tỷ lệ lớn trong nhóm công bố kém, rốt cuộc $\\nu_i$ tương quan với $\\text{DQ}_i$, và hệ số góc không còn sạch. Độ lớn là $-0.285/D$ đối với thước đo cổ điển so với $-0.0056/D$ đối với thước đo thực hiện, chênh nhau năm mươi lần.\n\nĐoạn mã sau định lượng cả hai tác động. Nó mô phỏng một tác động chất lượng công bố thông tin đã biết là $\\beta = -0.10$ lên log phi thanh khoản, trước hết với số ngày giao dịch giống nhau giữa các doanh nghiệp rồi với số ngày giao dịch tăng theo chất lượng công bố thông tin.\n\n::: {#dq-annual-measurement-error .cell execution_count=20}\n``` {.python .cell-code code-summary=\"Does numerator noise bias the annual disclosure-liquidity slope?\"}\nimport numpy as np\nimport pandas as pd\nfrom scipy.stats import norm\n\nrng_dq = np.random.default_rng(4242)\nM_HF, BETA_DQ, N_FIRMS, REPS_A, SD_E = 45, -0.10, 400, 300, 0.50\n\n\ndef measure_factor(kind, n, D, rng):\n    \"\"\"\n    Multiplicative measurement-error factor in the Amihud numerator,\n    averaged over each firm's D trading days. Mean one by construction;\n    only the variance differs between the two measures.\n    \"\"\"\n    Dm = D.max()\n    mask = np.arange(Dm)[None, :] < D[:, None]\n    if kind == \"classic\":\n        z = np.abs(rng.normal(0, 1, (n, Dm))) / np.sqrt(2 / np.pi)   # half-normal\n    else:\n        z = np.sqrt(rng.chisquare(M_HF, (n, Dm)) / M_HF)             # sqrt(RV)\n    return np.where(mask, z, 0).sum(1) / D\n\n\ndef annual_rep(link_days, rng):\n    \"\"\"One draw of the annual cross-sectional regression.\"\"\"\n    DQ = rng.normal(0, 1, N_FIRMS)\n    log_true = 1.0 + BETA_DQ * DQ + rng.normal(0, SD_E, N_FIRMS)\n\n    # Better disclosers trade on more days: 20 to 250 per year.\n    D = (np.clip(np.round(20 + 230 * norm.cdf(DQ)), 20, 250).astype(int)\n         if link_days else np.full(N_FIRMS, 250))\n\n    X = np.column_stack([np.ones(N_FIRMS), DQ])\n    XtXinv = np.linalg.inv(X.T @ X)\n\n    out = {}\n    for kind in [\"classic\", \"realized\", \"truth\"]:\n        f = (np.ones(N_FIRMS) if kind == \"truth\"\n             else measure_factor(kind, N_FIRMS, D, rng))\n        y = log_true + np.log(f)\n        b = XtXinv @ X.T @ y\n        r = y - X @ b\n        se = np.sqrt((r @ r / (N_FIRMS - 2)) * XtXinv[1, 1])\n        out[kind] = (b[1], se, b[1] / se)\n    return out\n\n\nfor link_days in [False, True]:\n    acc = {k: [] for k in [\"classic\", \"realized\", \"truth\"]}\n    for _ in range(REPS_A):\n        for k, v in annual_rep(link_days, rng_dq).items():\n            acc[k].append(v)\n\n    rows = []\n    for k, v in acc.items():\n        a = np.array(v)\n        rows.append({\n            \"measure\": k,\n            \"mean beta\": round(a[:, 0].mean(), 4),\n            \"attenuation %\": round(100 * (1 - a[:, 0].mean() / BETA_DQ), 1),\n            \"mean |t|\": round(np.abs(a[:, 2]).mean(), 2),\n            \"power@5%\": round((np.abs(a[:, 2]) > 1.96).mean(), 3),\n        })\n    print(f\"\\nTrading days linked to disclosure quality: {link_days}\")\n    print(pd.DataFrame(rows).to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nTrading days linked to disclosure quality: False\n measure  mean beta  attenuation %  mean |t|  power@5%\n classic    -0.1002           -0.2      3.99     0.977\nrealized    -0.1002           -0.2      4.01     0.977\n   truth    -0.1002           -0.2      4.01     0.977\n\nTrading days linked to disclosure quality: True\n measure  mean beta  attenuation %  mean |t|  power@5%\n classic    -0.0972            2.8      3.81     0.973\nrealized    -0.1000           -0.0      3.97     0.987\n   truth    -0.1001           -0.1      3.97     0.987\n```\n:::\n:::\n\n\nKết quả là đáng yên tâm đối với đặc tả đã được ước lượng trong chương này. Khi số ngày giao dịch không liên quan đến chất lượng công bố thông tin, cả ba thước đo đều khôi phục $\\beta$ về cơ bản chính xác, xác nhận rằng sai số đo lường ở phía biến kết quả không làm thiên lệch hệ số góc. Khi số ngày giao dịch *có* liên hệ với chất lượng công bố thông tin, thước đo cổ điển bị suy giảm khoảng 3%, trong khi thước đo thực hiện và giá trị thật không khả thi là không thể phân biệt. Mức suy giảm 3% không phải là điều quyết định liệu mối quan hệ công bố–thanh khoản có được phát hiện hay không, và nó nằm thoải mái trong mọi khoảng tin cậy hợp lý.\n\n**Kết luận trung thực đối với hồi quy theo năm là Amihud thực hiện không đáng với dữ liệu trong ngày mà nó đòi hỏi.** Biết một cải tiến không quan trọng ở đâu cũng hữu ích như biết nó quan trọng ở đâu; việc lấy trung bình theo năm trong @eq-amihud đã làm phần lớn công việc mà lấy mẫu tần suất cao sẽ làm.\n\n#### Nơi nó quan trọng rất nhiều: các cửa sổ sự kiện ngắn\n\nBức tranh hoàn toàn đảo ngược đối với các thiết kế nghiên cứu sự kiện ở những phần khác của chương này. Kiểm tra xem thanh khoản có cải thiện sau khi nộp hồ sơ hay không đòi hỏi so sánh phi thanh khoản trên một cửa sổ vài ngày ở hai phía của sự kiện, và cửa sổ ngắn chính là nơi việc lấy trung bình không thể cứu một tử số nhiễu. Trên cửa sổ năm ngày, sai số tương đối của tử số cổ điển là $0.7555/\\sqrt{5} \\approx 34\\%$; còn của tử số thực hiện dưới 5%.\n\nVì nhiễu đi vào hiệu số trước–sau hai lần, tác động của nó lên sức mạnh thống kê là nghiêm trọng. Mô phỏng dưới đây tính sức mạnh để phát hiện một thay đổi thực sự sau khi nộp hồ sơ trong log phi thanh khoản, cho phép sự không đồng nhất thực giữa các doanh nghiệp trong phản ứng để thước đo thực hiện không đạt sức mạnh tuyệt đối (bằng 1) một cách tầm thường.\n\n::: {#dq-event-window-power .cell execution_count=21}\n``` {.python .cell-code code-summary=\"Power to detect a post-filing liquidity change, by window length\"}\nrng_ev = np.random.default_rng(77)\nREPS_B = 1500\nRELVAR = {\"classic\": np.pi / 2 - 1, \"realized\": 1 / (2 * M_HF)}\n\n\ndef win_noise(kind, n, D):\n    \"\"\"Log measurement error in a D-day window average of the numerator.\"\"\"\n    z = (np.abs(rng_ev.normal(0, 1, (n, D))) / np.sqrt(2 / np.pi) if kind == \"classic\"\n         else np.sqrt(rng_ev.chisquare(M_HF, (n, D)) / M_HF))\n    return np.log(z.mean(1))\n\n\ndef ev_power(kind, n, D, delta, sd_delta):\n    \"\"\"Rejection rate of a paired pre/post test of a true change `delta`.\"\"\"\n    rejections = 0\n    for _ in range(REPS_B):\n        d = ((delta + rng_ev.normal(0, sd_delta, n))\n             + win_noise(kind, n, D) - win_noise(kind, n, D))\n        rejections += abs(d.mean() / (d.std(ddof=1) / np.sqrt(n))) > 1.96\n    return rejections / REPS_B\n\n\nSD_RESP = 0.10          # genuine cross-firm variation in the liquidity response\nrows_ev = []\nfor D in [5, 10, 21]:\n    for delta in [-0.02, -0.03, -0.05]:\n        row = {\"window (days)\": D, \"true change\": delta}\n        for kind in [\"classic\", \"realized\"]:\n            row[f\"power {kind}\"] = round(ev_power(kind, 200, D, delta, SD_RESP), 3)\n            # Closed-form firms needed for 80% power at the 5% level.\n            var_d = SD_RESP ** 2 + 2 * RELVAR[kind] / D\n            row[f\"firms for 80% ({kind})\"] = int(np.ceil(7.849 * var_d / delta ** 2))\n        rows_ev.append(row)\n\nev = pd.DataFrame(rows_ev)\nev[\"sample-size ratio\"] = (ev[\"firms for 80% (classic)\"]\n                           / ev[\"firms for 80% (realized)\"]).round(1)\nprint(\"200 firms, 5% two-sided test, cross-firm response sd = 0.10\")\nprint(ev.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n200 firms, 5% two-sided test, cross-firm response sd = 0.10\n window (days)  true change  power classic  firms for 80% (classic)  power realized  firms for 80% (realized)  sample-size ratio\n             5        -0.02          0.088                     4677           0.661                       284               16.5\n             5        -0.03          0.121                     2079           0.949                       126               16.5\n             5        -0.05          0.283                      749           0.999                        46               16.3\n            10        -0.02          0.127                     2437           0.732                       240               10.2\n            10        -0.03          0.238                     1083           0.967                       107               10.1\n            10        -0.05          0.499                      390           1.000                        39               10.0\n            21        -0.02          0.203                     1263           0.756                       217                5.8\n            21        -0.03          0.383                      562           0.978                        97                5.8\n            21        -0.05          0.775                      203           1.000                        35                5.8\n```\n:::\n:::\n\n\nKhoảng cách đủ lớn để thay đổi điều gì là khả thi. Với 200 doanh nghiệp và cửa sổ mười ngày, sức mạnh để phát hiện cải thiện thanh khoản 3% là khoảng 0.24 với thước đo cổ điển và khoảng 0.97 với thước đo thực hiện. Diễn đạt theo cỡ mẫu cần thiết, phát hiện tác động đó với sức mạnh 80% cần khoảng 1,080 doanh nghiệp với thước đo hằng ngày và khoảng 110 với thước đo thực hiện. Vì toàn bộ tập hợp doanh nghiệp niêm yết của Việt Nam chỉ cỡ 1,600 doanh nghiệp trên ba sàn, và một nghiên cứu về hồ sơ báo cáo năm giới hạn trong các doanh nghiệp có dữ liệu liên tục sẽ chỉ là một phần nhỏ trong đó, thước đo cổ điển khiến kiểm định này bất khả thi với hầu hết các mẫu con, còn thước đo thực hiện biến nó thành thường quy.\n\nBa nhận xét nữa rút ra từ bảng.\n\n**Lợi thế tăng lên khi cửa sổ thu hẹp.** Tỷ lệ cỡ mẫu khoảng 5.8 ở 21 ngày, 10 ở mười ngày và 16.5 ở năm ngày. Vì các cửa sổ sự kiện hẹp nhất chính là nơi việc nhận diện sạch nhất, ít bị các tin tức gây nhiễu khác chi phối nhất, thước đo nhiễu áp đặt sự đánh đổi trực tiếp giữa sức mạnh thống kê và chất lượng nhận diện. Thước đo thực hiện nới lỏng sự đánh đổi này.\n\n**Kết quả không có ý nghĩa từ một kiểm định thanh khoản cửa sổ ngắn gần như không mang thông tin.** Với 200 doanh nghiệp và cửa sổ năm ngày, thước đo cổ điển chỉ bác bỏ một tác động thật 2% khoảng 9% số lần, chỉ cao hơn một chút so với mức ý nghĩa 5% của kiểm định. Báo cáo \"không có thay đổi có ý nghĩa thống kê về thanh khoản quanh thời điểm nộp hồ sơ\" theo thiết kế đó về cơ bản không nói gì về việc liệu có thay đổi xảy ra hay không. Bất kỳ kết quả không ý nghĩa nào như vậy trong văn liệu này cần được đọc cùng với sức mạnh thống kê của nó.\n\n**Trần được quyết định bởi sự không đồng nhất thực, không phải bởi đo lường.** Cỡ mẫu cần thiết của thước đo thực hiện chững lại quanh 35 đến 285 doanh nghiệp vì biến thiên thực giữa các doanh nghiệp trong phản ứng thanh khoản (`SD_RESP = 0.10`) cuối cùng chiếm ưu thế. Vượt quá một điểm nhất định, đo lường tốt hơn không còn giúp ích và chỉ có thêm doanh nghiệp mới có tác dụng.\n\n#### Triển khai\n\nThước đo thực hiện là sự thay thế trực tiếp cho tử số ở bất cứ đâu chương này tính phi thanh khoản. Đoạn mã dưới đây cho thấy phép thay thế đối với dữ liệu bảng theo năm; các đầu vào thực hiện lấy từ cách xây dựng HOSE có nhận biết phiên được mô tả trong @sec-micro-realized-illiq, vốn đòi hỏi dữ liệu trong ngày nằm ngoài quy trình chuẩn.\n\n::: {#realized-amihud-dq .cell execution_count=22}\n``` {.python .cell-code code-summary=\"Realized Amihud as the liquidity outcome\"}\n# `realized_daily` holds one row per symbol-day from the intraday pipeline:\n#   [ticker, date, rv, bv, n_active, dvol_continuous]\nK = np.sqrt(2 / np.pi)\n\nrd = realized_daily.copy()\nrd = rd[(rd[\"n_active\"] >= 20) & (rd[\"dvol_continuous\"] > 0)]     # thin-trading screen\nrd[\"ramihud_daily\"] = K * np.sqrt(rd[\"rv\"]) / rd[\"dvol_continuous\"]\nrd[\"ramihud_bv_daily\"] = K * np.sqrt(rd[\"bv\"].clip(lower=0)) / rd[\"dvol_continuous\"]\n\nrealized_annual = (\n    rd.assign(fiscal_year=rd[\"date\"].dt.year)\n      .groupby([\"ticker\", \"fiscal_year\"])\n      .agg(ramihud=(\"ramihud_daily\", \"mean\"),\n           ramihud_bv=(\"ramihud_bv_daily\", \"mean\"),\n           n_days=(\"ramihud_daily\", \"size\"))\n      .reset_index()\n)\nrealized_annual[\"log_ramihud\"] = np.log(realized_annual[\"ramihud\"] + 1e-10)\n\n# Compare against the daily-frequency measure on the overlapping sample.\ncompare = amihud_annual.merge(realized_annual, on=[\"ticker\", \"fiscal_year\"],\n                              how=\"inner\")\nprint(f\"Overlapping firm-years: {len(compare):,}\")\nprint(\"Rank correlation between the two measures: \"\n      f\"{compare[['log_amihud', 'log_ramihud']].corr(method='spearman').iloc[0, 1]:.3f}\")\n\n# Re-estimate the disclosure-quality regression with the realized outcome.\nliq_panel_r = (\n    realized_annual\n    .merge(quality_panel[[\"ticker\", \"fiscal_year\", \"dq_index\"]],\n           on=[\"ticker\", \"fiscal_year\"], how=\"inner\")\n    .merge(financials[[\"ticker\", \"fiscal_year\", \"market_cap\"]],\n           on=[\"ticker\", \"fiscal_year\"], how=\"left\")\n    .assign(log_size=lambda d: np.log(d[\"market_cap\"]))\n    .set_index([\"ticker\", \"fiscal_year\"])\n)\n\nliq_model_r = PanelOLS(\n    dependent=liq_panel_r[\"log_ramihud\"],\n    exog=sm.add_constant(liq_panel_r[[\"dq_index\", \"log_size\"]]),\n    entity_effects=True, time_effects=True, check_rank=False,\n).fit(cov_type=\"clustered\", cluster_entity=True)\n\nprint(\"Realized Amihud ~ Disclosure Quality:\")\nprint(liq_model_r.summary)\n```\n:::\n\n\n#### Hướng dẫn thực hành\n\n1.  **Không chạy lại các hồi quy theo năm trên dữ liệu trong ngày.** Lợi ích tối đa chỉ là vài phần trăm suy giảm, và mẫu sẽ co lại còn các doanh nghiệp thanh khoản tốt có dữ liệu trong ngày dùng được, một chi phí chọn mẫu vượt xa lợi ích đo lường.\n2.  **Nên dùng thước đo thực hiện cho các kiểm định cửa sổ sự kiện** trong @sec-dis-qual-consequences, nơi nó tạo nên khác biệt giữa thiết kế khả thi và bất khả thi.\n3.  **Báo cáo số ngày giao dịch $D_{i,t}$** cùng với bất kỳ thước đo phi thanh khoản đã biến đổi log nào. Đó là biến chi phối méo mó Jensen, nó tương quan với chất lượng công bố thông tin, và hầu như không bao giờ được báo cáo.\n4.  **Ưu tiên biến thể bipower quanh thời điểm nộp hồ sơ.** Một bất ngờ lợi nhuận chính là bước nhảy thông tin làm phồng phương sai thực hiện, và ngày nộp hồ sơ là lúc nó xuất hiện. @sec-liquidity-realized cho thấy biến thiên bipower vẫn gần như không thiên lệch khi có bước nhảy.\n5.  **Khi không có dữ liệu trong ngày, hãy nới rộng cửa sổ thay vì chấp nhận kết quả không ý nghĩa.** Chuyển từ năm sang 21 ngày khôi phục một phần đáng kể sức mạnh bị mất do nhiễu ở tử số, với cái giá là chấp nhận thêm các sự kiện gây nhiễu, một sự đánh đổi cần được thực hiện một cách tường minh và báo cáo, chứ không phải theo mặc định.\n\n### Nghiên cứu sự kiện: Phản ứng thị trường đối với độ trễ nộp hồ sơ\n\nChúng ta xem xét liệu thị trường có phản ứng khác nhau với các doanh nghiệp nộp sớm và nộp muộn hay không bằng cách tính lợi nhuận bất thường tích lũy (CAR) quanh ngày nộp hồ sơ:\n\n$$\nCAR_{i}[\\tau_1, \\tau_2] = \\sum_{t=\\tau_1}^{\\tau_2} (R_{i,t} - \\hat{R}_{i,t})\n$$ {#eq-car}\n\ntrong đó $\\hat{R}_{i,t}$ là lợi nhuận kỳ vọng từ một mô hình thị trường được ước lượng trên cửa sổ trước sự kiện $[-250, -30]$.\n\n::: {#event-study .cell execution_count=23}\n``` {.python .cell-code code-summary=\"Conduct event study around filing dates by timeliness group\"}\ndef compute_car(ticker, event_date, trading_df,\n                est_window=(-250, -30), event_window=(-5, 10)):\n    \"\"\"Compute CAR around an event date using market model.\"\"\"\n    firm_data = trading_df[trading_df['ticker'] == ticker].copy()\n    firm_data = firm_data.sort_values('date')\n\n    # Find event date index\n    event_idx = firm_data[firm_data['date'] >= event_date].index\n    if len(event_idx) == 0:\n        return None\n    event_idx = event_idx[0]\n    event_pos = firm_data.index.get_loc(event_idx)\n\n    # Check sufficient data\n    if event_pos + est_window[0] < 0:\n        return None\n\n    # Estimation window\n    est_start = event_pos + est_window[0]\n    est_end = event_pos + est_window[1]\n    est_data = firm_data.iloc[est_start:est_end + 1]\n\n    firm_ret = est_data['close'].pct_change()\n    mkt_ret = est_data['market_return']\n\n    valid = firm_ret.notna() & mkt_ret.notna()\n    if valid.sum() < 100:\n        return None\n\n    # Market model\n    X = sm.add_constant(mkt_ret[valid])\n    model = sm.OLS(firm_ret[valid], X).fit()\n\n    # Event window\n    ev_start = event_pos + event_window[0]\n    ev_end = event_pos + event_window[1]\n    ev_data = firm_data.iloc[ev_start:ev_end + 1]\n\n    ev_ret = ev_data['close'].pct_change()\n    ev_mkt = ev_data['market_return']\n    expected_ret = model.params['const'] + model.params['market_return'] * ev_mkt\n    abnormal_ret = ev_ret - expected_ret\n\n    return abnormal_ret.cumsum().values\n\n# Sample: compute CARs for annual filings\ncar_results = []\nfor _, row in annual_filings.sample(min(2000, len(annual_filings))).iterrows():\n    car = compute_car(row['ticker'], row['filing_date'], trading)\n    if car is not None and len(car) == 16:  # -5 to +10\n        car_results.append({\n            'ticker': row['ticker'],\n            'fiscal_year': row['fiscal_year'],\n            'lag_tercile': row['lag_tercile'],\n            'car': car\n        })\n\ncar_df = pd.DataFrame(car_results)\nprint(f\"Computed CARs for {len(car_df)} firm-year events\")\n```\n:::\n\n\n::: {#fig-event-study .cell execution_count=24}\n``` {.python .cell-code code-summary=\"Plot CAR paths by timeliness tercile\"}\nevent_days = range(-5, 11)\n\nfig, ax = plt.subplots(figsize=(10, 6))\ncolors = {'Early': '#27AE60', 'Middle': '#F1C40F', 'Late': '#C0392B'}\n\nfor tercile in ['Early', 'Middle', 'Late']:\n    subset = car_df[car_df['lag_tercile'] == tercile]\n    if len(subset) > 0:\n        avg_car = np.mean(np.stack(subset['car'].values), axis=0)\n        se_car = np.std(np.stack(subset['car'].values), axis=0) / np.sqrt(len(subset))\n        ax.plot(event_days, avg_car, color=colors[tercile],\n                linewidth=2, label=tercile)\n        ax.fill_between(event_days,\n                        avg_car - 1.96 * se_car,\n                        avg_car + 1.96 * se_car,\n                        color=colors[tercile], alpha=0.15)\n\nax.axvline(x=0, color='gray', linestyle='--', linewidth=0.8)\nax.axhline(y=0, color='gray', linewidth=0.5)\nax.set_xlabel('Event Day (Relative to Filing Date)')\nax.set_ylabel('Cumulative Abnormal Return')\nax.set_title('Market Reaction Around Filing Date by Timeliness')\nax.legend(title='Filing Tercile')\nplt.tight_layout()\nplt.show()\n```\n:::\n\n\n## Tính kịp thời của việc nộp hồ sơ và chất lượng lợi nhuận {#sec-dis-qual-timeliness-quality}\n\n@givoly1982timeliness và @chambers1984timeliness xác lập rằng nội dung của thông tin được công bố có tương quan với thời điểm công bố. Chúng ta kiểm định chính thức mối liên hệ này: các doanh nghiệp nộp muộn có chất lượng lợi nhuận kém hơn không?\n\n::: {#fig-timeliness-quality .cell execution_count=25}\n``` {.python .cell-code code-summary=\"Analyze relationship between filing lag and earnings quality\"}\ntq_panel = (\n    annual_filings[['ticker', 'fiscal_year', 'lag_tercile', 'reporting_lag']]\n    .merge(aq_df, on=['ticker', 'fiscal_year'], how='inner')\n    .merge(persistence_df[['ticker', 'persistence']], on='ticker', how='left')\n)\n\nfig, axes = plt.subplots(1, 2, figsize=(14, 5))\n\n# Panel A: Accruals quality by tercile\naq_by_tercile = tq_panel.groupby('lag_tercile')['accruals_quality'].mean()\naxes[0].bar(\n    range(3), aq_by_tercile.values,\n    color=['#27AE60', '#F1C40F', '#C0392B'], alpha=0.85,\n    edgecolor='white'\n)\naxes[0].set_xticks(range(3))\naxes[0].set_xticklabels(['Early', 'Middle', 'Late'])\naxes[0].set_ylabel('Accruals Quality (σ of DD Residuals)')\naxes[0].set_title('Panel A: Accruals Quality by Filing Tercile')\naxes[0].text(0.05, 0.95, 'Higher = lower quality',\n             transform=axes[0].transAxes, fontsize=9,\n             verticalalignment='top', style='italic', color='gray')\n\n# Panel B: Persistence by tercile\nper_by_tercile = tq_panel.groupby('lag_tercile')['persistence'].mean()\naxes[1].bar(\n    range(3), per_by_tercile.values,\n    color=['#27AE60', '#F1C40F', '#C0392B'], alpha=0.85,\n    edgecolor='white'\n)\naxes[1].set_xticks(range(3))\naxes[1].set_xticklabels(['Early', 'Middle', 'Late'])\naxes[1].set_ylabel('Earnings Persistence (AR(1) Coefficient)')\naxes[1].set_title('Panel B: Earnings Persistence by Filing Tercile')\n\nplt.tight_layout()\nplt.show()\n```\n:::\n\n\nChúng ta chính thức hóa điều này bằng một hồi quy có kiểm soát các đặc điểm doanh nghiệp:\n\n::: {#timeliness-quality-regression .cell execution_count=26}\n``` {.python .cell-code code-summary=\"Regression: accruals quality on filing lag with controls\"}\ntq_panel_reg = tq_panel.merge(\n    financials[['ticker', 'fiscal_year', 'total_assets', 'net_income',\n                'total_equity']],\n    on=['ticker', 'fiscal_year'], how='left'\n).merge(governance, on=['ticker', 'fiscal_year'], how='left')\n\ntq_panel_reg['log_size'] = np.log(tq_panel_reg['total_assets'])\ntq_panel_reg['roa'] = tq_panel_reg['net_income'] / tq_panel_reg['total_assets']\ntq_panel_reg['late'] = (tq_panel_reg['lag_tercile'] == 'Late').astype(int)\n\nmodel_tq = smf.ols(\n    'accruals_quality ~ late + log_size + roa + state_ownership_pct '\n    '+ big4_auditor + C(fiscal_year)',\n    data=tq_panel_reg\n).fit(cov_type='cluster', cov_kwds={'groups': tq_panel_reg['ticker']})\n\nprint(\"Accruals Quality ~ Late Filing:\")\nprint(model_tq.summary().tables[1])\n```\n:::\n\n\n::: callout-note\n## Lưu ý về nội sinh\n\nMối liên hệ giữa tính kịp thời của việc nộp hồ sơ và chất lượng lợi nhuận có khả năng mang tính nội sinh: các doanh nghiệp có vấn đề kế toán phức tạp mất nhiều thời gian hơn để chuẩn bị báo cáo tài chính, và chính sự phức tạp đó làm giảm chất lượng lợi nhuận. Vì vậy, độ trễ nộp hồ sơ được diễn giải tốt nhất như một *tín hiệu quan sát được* về khó khăn kế toán tiềm ẩn chứ không phải một yếu tố quyết định mang tính nhân quả. Các cách tiếp cận biến công cụ (ví dụ dùng mức độ bận rộn của kiểm toán viên trong mùa cao điểm nộp hồ sơ làm biến công cụ cho độ trễ nộp hồ sơ) có thể giải quyết một phần mối lo ngại này.\n:::\n\n## Chất lượng công bố thông tin và hiệu quả đầu tư {#sec-dis-qual-investment}\n\n@biddle2009does chứng minh rằng chất lượng báo cáo tài chính cao hơn gắn với đầu tư hiệu quả hơn. Cụ thể, nó làm giảm cả đầu tư quá mức (ở các doanh nghiệp có tiền mặt dư thừa) lẫn đầu tư dưới mức (ở các doanh nghiệp bị hạn chế tài chính). Cơ chế là công bố thông tin tốt hơn làm giảm bất cân xứng thông tin giữa nhà quản lý và nhà cung cấp vốn, cải thiện việc phân bổ vốn.\n\nChúng ta kiểm tra dự báo này ở Việt Nam bằng khung phân tích của @biddle2009does:\n\n$$\n\\text{Investment}_{i,t+1} = \\alpha + \\beta_1 \\text{SalesGrowth}_{i,t} + \\varepsilon_{i,t+1}\n$$ {#eq-inv-efficiency}\n\nPhần dư $\\hat{\\varepsilon}_{i,t+1}$ đo độ lệch so với đầu tư kỳ vọng. Phần dư dương cho thấy đầu tư quá mức; phần dư âm cho thấy đầu tư dưới mức. Sau đó chúng ta kiểm tra xem giá trị tuyệt đối của phần dư này có thấp hơn đối với các doanh nghiệp có chất lượng công bố thông tin cao hơn hay không.\n\n::: {#investment-efficiency .cell execution_count=27}\n``` {.python .cell-code code-summary=\"Estimate investment efficiency and test disclosure quality link\"}\ninv_panel = financials.sort_values(['ticker', 'fiscal_year']).copy()\n\n# Investment = change in total assets / lagged total assets\ninv_panel['investment'] = (\n    inv_panel.groupby('ticker')['total_assets'].pct_change()\n)\ninv_panel['sales_growth'] = (\n    inv_panel.groupby('ticker')['revenue'].pct_change()\n)\n\n# Expected investment model\ninv_model = smf.ols(\n    'investment ~ sales_growth',\n    data=inv_panel\n).fit()\ninv_panel['inv_residual'] = inv_model.resid\ninv_panel['abs_inv_residual'] = inv_panel['inv_residual'].abs()\n\n# Merge with disclosure quality\ninv_eff = (\n    inv_panel[['ticker', 'fiscal_year', 'abs_inv_residual',\n               'investment', 'total_assets']]\n    .merge(quality_panel[['ticker', 'fiscal_year', 'dq_index']].reset_index(drop=True),\n           on=['ticker', 'fiscal_year'], how='inner')\n)\ninv_eff['log_size'] = np.log(inv_eff['total_assets'])\ninv_eff = inv_eff.set_index(['ticker', 'fiscal_year'])\n\n# Panel regression\ninv_eff_model = PanelOLS(\n    dependent=inv_eff['abs_inv_residual'],\n    exog=sm.add_constant(inv_eff[['dq_index', 'log_size']]),\n    entity_effects=True,\n    time_effects=True,\n    check_rank=False\n).fit(cov_type='clustered', cluster_entity=True)\n\nprint(\"Investment Inefficiency ~ Disclosure Quality:\")\nprint(inv_eff_model.summary)\n```\n:::\n\n\nHệ số âm trên `dq_index` cho thấy chất lượng công bố thông tin cao hơn gắn với sự kém hiệu quả đầu tư thấp hơn: các doanh nghiệp công bố tốt hơn đưa ra quyết định đầu tư gần hơn với mức mà cơ hội tăng trưởng của họ đòi hỏi.\n\n## Bối cảnh thể chế Việt Nam {#sec-dis-qual-vietnam-context}\n\n### Sở hữu nhà nước và công bố thông tin\n\nCác doanh nghiệp nhà nước (SOE) chiếm một tỷ trọng đáng kể trong vốn hóa thị trường Việt Nam. Mối quan hệ giữa sở hữu nhà nước và chất lượng công bố thông tin là không rõ ràng về mặt lý thuyết. Một mặt, các mối quan hệ chính trị có thể làm giảm áp lực công bố minh bạch; các cổ đông nhà nước có thể chấp nhận sự thiếu minh bạch mà các cổ đông tư nhân sẽ không chấp nhận. Mặt khác, việc giám sát sau cổ phần hóa bởi nhiều bên liên quan (Bộ Tài chính, SCIC, cổ đông thiểu số) có thể tạo ra những yêu cầu công bố cạnh tranh nhau.\n\n::: {#soe-disclosure .cell execution_count=28}\n``` {.python .cell-code code-summary=\"Compare disclosure quality between SOEs and private firms\"}\nsoe_panel = (\n    quality_panel[['ticker', 'fiscal_year', 'dq_index',\n                    'reporting_lag']].reset_index(drop=True)\n    .merge(governance[['ticker', 'fiscal_year', 'state_ownership_pct']],\n           on=['ticker', 'fiscal_year'], how='inner')\n)\n\nsoe_panel['soe'] = (soe_panel['state_ownership_pct'] >= 50).astype(int)\nsoe_panel['soe_label'] = soe_panel['soe'].map(\n    {1: 'SOE (≥50%)', 0: 'Private (<50%)'}\n)\n\n# Compare means\ncomparison = (\n    soe_panel\n    .groupby('soe_label')\n    .agg(\n        n=('dq_index', 'count'),\n        mean_dq=('dq_index', 'mean'),\n        median_dq=('dq_index', 'median'),\n        mean_lag=('reporting_lag', 'mean'),\n        median_lag=('reporting_lag', 'median')\n    )\n    .round(3)\n)\nprint(\"SOE vs Private Firm Disclosure Comparison:\")\nprint(comparison)\n\n# Formal t-test\nsoe_dq = soe_panel[soe_panel['soe'] == 1]['dq_index']\npriv_dq = soe_panel[soe_panel['soe'] == 0]['dq_index']\nt_stat, p_val = stats.ttest_ind(soe_dq.dropna(), priv_dq.dropna())\nprint(f\"\\nt-test: t = {t_stat:.3f}, p = {p_val:.4f}\")\n```\n:::\n\n\n### Hội tụ IFRS và chất lượng công bố thông tin\n\nViệt Nam đang theo đuổi lộ trình hội tụ từng giai đoạn với IFRS, trong đó Bộ Tài chính ban hành lộ trình áp dụng tự nguyện cho các doanh nghiệp niêm yết lớn. Quá trình chuyển từ VAS sang các chuẩn mực phù hợp IFRS được kỳ vọng sẽ mở rộng yêu cầu công bố thông tin, đặc biệt đối với công cụ tài chính (IFRS 9), ghi nhận doanh thu (IFRS 15) và thuê tài sản (IFRS 16). @barth2008international cung cấp bằng chứng rằng việc áp dụng IFRS gắn với cải thiện chất lượng lợi nhuận và công bố thông tin, dù tác động phụ thuộc vào mức độ thực thi.\n\nChúng ta có thể khai thác thời điểm áp dụng IFRS tự nguyện so le giữa các doanh nghiệp Việt Nam như một thí nghiệm tự nhiên:\n\n::: {#ifrs-adoption .cell execution_count=29}\n``` {.python .cell-code code-summary=\"Difference-in-differences: IFRS adoption and disclosure quality\"}\n# Assume DataCore provides IFRS adoption dates\nifrs_adoption = client.get_ifrs_adoption(\n    exchanges=['HOSE', 'HNX'],\n    fields=['ticker', 'ifrs_adoption_year']\n)\n\n# Merge with quality panel\nifrs_panel = (\n    quality_panel[['ticker', 'fiscal_year', 'dq_index']].reset_index(drop=True)\n    .merge(ifrs_adoption, on='ticker', how='left')\n)\n\n# Treatment indicator\nifrs_panel['post_ifrs'] = (\n    ifrs_panel['fiscal_year'] >= ifrs_panel['ifrs_adoption_year']\n).astype(int).fillna(0)\n\nifrs_panel['treated'] = ifrs_panel['ifrs_adoption_year'].notna().astype(int)\n\n# Simple DiD\nifrs_panel = ifrs_panel.set_index(['ticker', 'fiscal_year'])\ndid_model = PanelOLS(\n    dependent=ifrs_panel['dq_index'],\n    exog=sm.add_constant(ifrs_panel[['post_ifrs']]),\n    entity_effects=True,\n    time_effects=True,\n    check_rank=False\n).fit(cov_type='clustered', cluster_entity=True)\n\nprint(\"DiD: IFRS Adoption and Disclosure Quality:\")\nprint(did_model.summary)\n```\n:::\n\n\n::: callout-note\n## Mối lo ngại về nhận diện\n\nViệc áp dụng IFRS tự nguyện mang tính nội sinh vì các doanh nghiệp chọn áp dụng sớm có thể đã có chất lượng công bố thông tin cao hơn. Phương pháp DiD với hiệu ứng cố định hai chiều hấp thụ các đặc điểm doanh nghiệp không đổi theo thời gian và các xu hướng thời gian chung, nhưng không thể xử lý hoàn toàn sự chọn lọc dựa trên các yếu tố không quan sát được biến đổi theo thời gian. Các nhà nghiên cứu nên cân nhắc các công cụ ước lượng ghép cặp (ví dụ ghép điểm xu hướng theo các đặc điểm trước khi áp dụng) hoặc các cách tiếp cận biến công cụ làm kiểm tra độ vững.\n:::\n\n## Dự báo việc nộp hồ sơ muộn {#sec-dis-qual-prediction}\n\nChúng ta có thể dự báo doanh nghiệp nào sẽ nộp muộn không? Điều này có giá trị cho việc xây dựng danh mục đầu tư (tránh các doanh nghiệp có thể có tin xấu) và cho các cơ quan quản lý (nhắm nguồn lực thực thi). Chúng ta dùng mô hình logistic với các biến dự báo tài chính và quản trị:\n\n$$\n\\Pr(\\text{Late}_{i,t} = 1) = \\Lambda\\left(\\alpha + \\boldsymbol{\\beta}'\\mathbf{X}_{i,t-1}\\right)\n$$ {#eq-prediction}\n\ntrong đó $\\Lambda(\\cdot)$ là hàm logistic và $\\mathbf{X}_{i,t-1}$ là các biến dự báo có độ trễ.\n\n::: {#predict-late-filing .cell execution_count=30}\n``` {.python .cell-code code-summary=\"Logistic model to predict late filings\"}\nfrom sklearn.metrics import roc_auc_score, classification_report\nfrom sklearn.model_selection import cross_val_score\nfrom sklearn.linear_model import LogisticRegression\n\npred_panel = (\n    annual_filings[['ticker', 'fiscal_year', 'late_filing']]\n    .merge(financials, on=['ticker', 'fiscal_year'], how='left')\n    .merge(governance, on=['ticker', 'fiscal_year'], how='left')\n)\n\n# Lagged predictors\npred_panel = pred_panel.sort_values(['ticker', 'fiscal_year'])\nfor col in ['total_assets', 'net_income', 'operating_cash_flow',\n            'total_equity', 'revenue']:\n    pred_panel[f'{col}_lag'] = pred_panel.groupby('ticker')[col].shift(1)\n\npred_panel['log_size_lag'] = np.log(pred_panel['total_assets_lag'])\npred_panel['roa_lag'] = (\n    pred_panel['net_income_lag'] / pred_panel['total_assets_lag']\n)\npred_panel['leverage_lag'] = (\n    (pred_panel['total_assets_lag'] - pred_panel['total_equity_lag'])\n    / pred_panel['total_assets_lag']\n)\npred_panel['cfo_ratio_lag'] = (\n    pred_panel['operating_cash_flow_lag'] / pred_panel['total_assets_lag']\n)\n\n# Previous late filing indicator\npred_panel['prev_late'] = (\n    pred_panel.groupby('ticker')['late_filing'].shift(1)\n)\n\nfeatures = [\n    'log_size_lag', 'roa_lag', 'leverage_lag', 'cfo_ratio_lag',\n    'state_ownership_pct', 'foreign_ownership_pct',\n    'big4_auditor', 'board_independence_pct', 'prev_late'\n]\n\nclean = pred_panel.dropna(subset=features + ['late_filing'])\nX = clean[features]\ny = clean['late_filing']\n\n# Standardize\nscaler = StandardScaler()\nX_scaled = scaler.fit_transform(X)\n\n# Logistic regression with cross-validation\nlr = LogisticRegression(max_iter=1000, penalty='l2', C=1.0)\ncv_scores = cross_val_score(lr, X_scaled, y, cv=5, scoring='roc_auc')\n\nprint(f\"5-Fold Cross-Validated AUC: {cv_scores.mean():.3f} ± {cv_scores.std():.3f}\")\n\n# Fit on full sample for coefficient interpretation\nlr.fit(X_scaled, y)\ncoef_df = pd.DataFrame({\n    'Feature': features,\n    'Coefficient': lr.coef_[0],\n    'Odds Ratio': np.exp(lr.coef_[0])\n}).sort_values('Coefficient', ascending=False)\n\nprint(\"\\nLogistic Regression Coefficients:\")\nprint(coef_df.to_string(index=False))\n```\n:::\n\n\n::: {#fig-roc-curve .cell execution_count=31}\n``` {.python .cell-code code-summary=\"Plot ROC curve for the late-filing prediction model\"}\nfrom sklearn.metrics import roc_curve, auc\n\nlr.fit(X_scaled, y)\ny_prob = lr.predict_proba(X_scaled)[:, 1]\nfpr, tpr, _ = roc_curve(y, y_prob)\nroc_auc = auc(fpr, tpr)\n\nfig, ax = plt.subplots(figsize=(7, 7))\nax.plot(fpr, tpr, color='#2C5F8A', linewidth=2,\n        label=f'Logistic Model (AUC = {roc_auc:.3f})')\nax.plot([0, 1], [0, 1], color='gray', linestyle='--', linewidth=1)\nax.set_xlabel('False Positive Rate')\nax.set_ylabel('True Positive Rate')\nax.set_title('Late Filing Prediction: ROC Curve')\nax.legend(loc='lower right')\nax.set_aspect('equal')\nplt.tight_layout()\nplt.show()\n```\n:::\n\n\n## Tóm tắt {#sec-dis-qual-summary}\n\nChương này đã xem xét chất lượng và thời điểm công bố thông tin doanh nghiệp ở Việt Nam theo nhiều chiều. Các phát hiện chính và đóng góp phương pháp luận được nêu trong @tbl-dis-qual-summary\n\n| Chủ đề | Kết quả chính | Tài liệu tham khảo |\n|------------------------|------------------------|------------------------|\n| Tin tốt công bố sớm | Các doanh nghiệp nộp sớm có CAR dương quanh ngày nộp hồ sơ | @givoly1982timeliness |\n| Chất lượng văn bản | Mật độ hướng tới tương lai và tính cụ thể về số liệu khác nhau đáng kể | @li2008annual |\n| Chỉ số DQ tổng hợp | Sở hữu nước ngoài và công ty kiểm toán Big 4 là các yếu tố quyết định mạnh nhất | @botosan1997disclosure |\n| Chi phí vốn | DQ cao hơn gắn với chi phí vốn cổ phần ngụ ý thấp hơn | @diamond1991disclosure |\n| Thanh khoản | Các doanh nghiệp có DQ cao hơn có phi thanh khoản Amihud thấp hơn | @lang2012transparency |\n| Hiệu quả đầu tư | DQ cao hơn làm giảm phần dư đầu tư tuyệt đối | @biddle2009does |\n| Thời điểm chiến lược | Bằng chứng về việc tin xấu dồn vào những ngày ùn tắc cao | @hirshleifer2009driven |\n| Áp dụng IFRS | Bằng chứng sơ bộ về cải thiện DQ sau khi áp dụng | @barth2008international |\n\n: Tóm tắt các phát hiện theo chủ đề. {#tbl-dis-qual-summary}\n\nMôi trường công bố thông tin của Việt Nam được định hình bởi sự kết hợp giữa các yêu cầu bắt buộc theo quy định (Thông tư 155, Luật Chứng khoán 2019), năng lực thực thi (các chế tài của SSC và việc đình chỉ giao dịch) và các động cơ ở cấp doanh nghiệp (cấu trúc sở hữu, lựa chọn kiểm toán viên, chất lượng quản trị). Khi Việt Nam tiếp tục hội tụ IFRS và phát triển thị trường vốn, môi trường thông tin được kỳ vọng sẽ tiếp tục thay đổi, tạo cơ hội cho các nhà nghiên cứu nghiên cứu động thái của chất lượng công bố thông tin trong một bối cảnh thể chế thay đổi nhanh chóng.\n\n<!-- ## Bài tập {#sec-dis-qual-exercises}\n\n1.  **Ý kiến kiểm toán và tính kịp thời.** Mở rộng phân tích độ trễ nộp hồ sơ bằng cách phân tách theo loại ý kiến kiểm toán (chấp nhận toàn phần, ngoại trừ, nhấn mạnh vấn đề, trái ngược). Các doanh nghiệp nhận ý kiến kiểm toán không phải là ý kiến chấp nhận toàn phần có nộp muộn một cách hệ thống không? Điều này hàm ý gì về nội dung thông tin của sự chậm trễ nộp hồ sơ?\n\n2.  **Mô hình mùa vụ.** Năm tài chính của Việt Nam hầu hết kết thúc vào ngày 31 tháng 12. Phân tích xem cửa sổ nộp báo cáo năm quý 4 (tháng 1–tháng 3) có đặc điểm chất lượng khác với các hồ sơ quý hay không. Mức độ bận rộn của kiểm toán viên trong mùa cao điểm có ảnh hưởng đến tính kịp thời của việc nộp hồ sơ không?\n\n3.  **Độ phức tạp văn bản và quản trị lợi nhuận.** Kết hợp các thước đo chất lượng văn bản từ chương này với các mô hình quản trị lợi nhuận từ chương Quản trị lợi nhuận. Các doanh nghiệp có dồn tích tùy ý cao hơn có tạo ra thông tin công bố phức tạp hơn hoặc khó đọc hơn không?\n\n4.  **Sở hữu nước ngoài và công bố thông tin tự nguyện.** Dùng dữ liệu quản trị, kiểm tra xem sự gia tăng sở hữu nước ngoài có *dẫn đến* cải thiện chất lượng công bố thông tin (nhân quả) hay các nhà đầu tư nước ngoài *tự chọn* vào những doanh nghiệp đã có công bố thông tin tốt hơn (chọn lọc). Đề xuất một chiến lược nhận diện.\n\n5.  **Nới lỏng quy định thời COVID-19.** Trong đại dịch COVID-19, SSC tạm thời gia hạn thời hạn nộp hồ sơ. Xem xét liệu việc nới lỏng quy định này có ảnh hưởng đến nội dung thông tin của các hồ sơ hay không: các doanh nghiệp tận dụng gia hạn có đặc điểm lợi nhuận khác với những doanh nghiệp nộp theo lịch ban đầu không?\n\n6.  **Dự báo bằng học máy.** Mở rộng mô hình dự báo nộp muộn từ @sec-prediction bằng gradient boosting hoặc rừng ngẫu nhiên. So sánh hiệu quả dự báo và xem xét mức độ quan trọng của biến. Những tương tác phi tuyến nào cải thiện dự báo vượt trên mô hình logistic cơ sở?\n\n7.  **Giám sát công bố thông tin theo thời gian thực.** Thiết kế một hệ thống dùng API của DataCore.vn để giám sát ngày nộp hồ sơ theo thời gian thực, gắn cờ các doanh nghiệp sắp đến thời hạn quy định và tính xác suất kỳ vọng nộp muộn bằng mô hình dự báo. Thảo luận cách một công cụ như vậy có thể được nhà đầu tư và cơ quan quản lý sử dụng.\n\n8.  **Niêm yết chéo và chất lượng công bố thông tin.** Một số doanh nghiệp Việt Nam niêm yết chéo hoặc phát hành chứng chỉ lưu ký trên các sàn nước ngoài, chịu thêm các yêu cầu công bố thông tin. Kiểm tra xem các doanh nghiệp niêm yết chéo có chất lượng công bố thông tin cao hơn các doanh nghiệp chỉ niêm yết trong nước hay không, kiểm soát các đặc điểm doanh nghiệp. -->\n\n",
    "supporting": [
      "37_disclosure_quality_and_timing_files\\figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}